### PR TITLE
Update pagination.cn.md

### PR DESCRIPTION
**Pull request by CoderFengZi**
将归并排序时间复杂度从O(n) 修改为 O(nlogn)

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
Could you fix the English doc too?

**Comment by tristaZero** [comment]
@CoderFengZi Hi Could you look at @terrymanu 's feedback on this PR or close this one? as it has been on this PR list for a long time.

**Comment by tristaZero** [comment]
Hi since there is no progress, I have to close it.

**Comment by carteruu** [comment]
合并n个长度为m的已排序数组的时间复杂度为O(mn(log n))，按照原文举的例子，n为2时，时间复杂度为O(mn)，其实原文并没有问题，只是表述有歧义。

**Pull request closed without merging**
