### PR TITLE
Update links

### PR DESCRIPTION
**Pull request by Swastyy**
Fixes #ISSUSE_ID.

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Review by TeslaCN — CHANGES_REQUESTED** [review]
The links are right.

**Comment by Swastyy** [comment]
> The links are right.

But the error 404 comes when I click on it, see the screenshot for reference 
image

**Comment by TeslaCN** [comment]
The corresponding page is here:
https://shardingsphere.apache.org/community/en/team/

**Comment by Swastyy** [comment]
> The corresponding page is here: https://shardingsphere.apache.org/community/en/team/

Okay, understood. Thanks @TeslaCN .

**Pull request closed without merging**
