### PR TITLE
Improve DistSQL DROP ENCRYPT RULE

### PR DESCRIPTION
**Pull request by Pace2Car**
For #22358 .

Changes proposed in this pull request:
  - Improve DROP ENCRYPT RULE, remove unused algorithms while dropping rule
  - Supplementary related test cases

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [x] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [x] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Comment by Pace2Car** [comment]
please add lables: `feature: DistSQL` `feature: encrypt` `type: enhancement`

**Review by RaigorJiang — APPROVED** [review]

**Comment by hhw3KevinHou** [comment]
still wrong logic about DROP ENCRYPT RULE in 5.4.1, what's your logic about:
rules.removeIf(each -> each.getConfiguration().getClass().isAssignableFrom(ruleConfig.getClass()));   
It delete all encrypt rule

**Comment by RaigorJiang** [comment]
@hhw3KevinHou Thanks for the feedback!
Hi, @Pace2Car  can you check it?

**Comment by Pace2Car** [comment]
> still wrong logic about DROP ENCRYPT RULE in 5.4.1, what's your logic about: rules.removeIf(each -> each.getConfiguration().getClass().isAssignableFrom(ruleConfig.getClass())); It delete all encrypt rule

Thanks for the feedback, all database rule will be rebuilt based on the remaining configuration after cleaning.

**Pull request merged**
