### PR TITLE
Update OracleSchemaMetaDataLoader.java

### PR DESCRIPTION
**Pull request by zhuoan**
Avoid null pointer exceptions for resultSet.getString("COLLATION") ,

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
Could you update the test case?

**Comment by zhuoan** [comment]
the test case not need change，this bugfix is to fix the resultSet.getString("COLLATION") may be null

**Comment by terrymanu** [comment]
> resultSet.getString("COLLATION")

It is better to test when `resultSet.getString("COLLATION")`

**Comment by terrymanu** [comment]
@zhuoan Hi, any update?

**Comment by terrymanu** [comment]
@zhuoan The progress of this PR has not been upgraded for a long time. If there is no update, I will close it soon.

**Comment by terrymanu** [comment]
@zhuoan The progress of this PR has not been upgraded for a long time. If there is no update, I will close it soon.

**Comment by terrymanu** [comment]
I just close this PR.

**Pull request closed without merging**
