### PR TITLE
Add about sharding-algorithms config to additional-spring-configuration-metadata.json

### LINKED ISSUE #13002: Shardingjdbc does not display configuration properly in YAML and Properties(For example:Cannot resolve configuration property)
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-beta
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
When configuring a property after the table name in YAML or Properties, the part after the table name is displayed normally, as sharding-jdbC-spring-boot-starter 4.1.1 does not give a warning. Sample source code for the project is provided 
from https://github.com/qiuxiaotong2021/catfish-sharding . The following is the application.
```properties
server.port=8080
spring.application.name=catfish-sharding
spring.main.allow-bean-definition-overriding=true

spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.shardingsphere.datasource.names=ds-0,ds-1
spring.shardingsphere.datasource.ds-0.jdbc-url=jdbc:mysql://localhost:3306/ds0?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.shardingsphere.datasource.ds-0.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.ds-0.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.ds-0.username=root
spring.shardingsphere.datasource.ds-0.password=root1234
spring.shardingsphere.datasource.ds-0.minimum-idle=5
spring.shardingsphere.datasource.ds-0.maximum-pool-size=10

spring.shardingsphere.datasource.ds-1.jdbc-url=jdbc:mysql://localhost:3306/ds1?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.shardingsphere.datasource.ds-1.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.ds-1.driver-class-name=com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.ds-1.username=root
spring.shardingsphere.datasource.ds-1.password=root1234
spring.shardingsphere.datasource.ds-1.minimum-idle=5
spring.shardingsphere.datasource.ds-1.maximum-pool-size=10

spring.shardingsphere.props.sql-show=true
spring.shardingsphere.props.max-connections-size-per-query=5
spring.shardingsphere.props.executor.size=5

spring.shardingsphere.rules.sharding.default-database-strategy.complex.sharding-columns=user_id,order_id
spring.shardingsphere.rules.sharding.default-database-strategy.complex.sharding-algorithm-name=order-db-complex
spring.shardingsphere.rules.sharding.sharding-algorithms.order-db-complex.type=OrderDbComplex
spring.shardingsphere.rules.sharding.sharding-algorithms.order-db-complex.props.algorithm-expression=com.catfish.sharding.algorithm.OrderDbComplexShardingAlgorithm

spring.shardingsphere.rules.sharding.binding-tables[0]=t_order,t_order_item
spring.shardingsphere.rules.sharding.broadcast-tables[0]=t_address

spring.shardingsphere.rules.sharding.tables.t_order.actual-data-nodes=ds-$->{0..1}.t_order_$->{0..1}

spring.shardingsphere.rules.sharding.tables.t_order.table-strategy.standard.sharding-column=order_id
spring.shardingsphere.rules.sharding.tables.t_order.table-strategy.standard.sharding-algorithm-name=order-volume-range-table
spring.shardingsphere.rules.sharding.sharding-algorithms.order-volume-range-table.type=VOLUME_RANGE
spring.shardingsphere.rules.sharding.sharding-algorithms.order-volume-range-table.props.range-lower=5
spring.shardingsphere.rules.sharding.sharding-algorithms.order-volume-range-table.props.range-upper=10
spring.shardingsphere.rules.sharding.sharding-algorithms.order-volume-range-table.props.sharding-volume=5

spring.shardingsphere.rules.sharding.tables.t_order_item.actual-data-nodes=ds-$->{0..1}.t_order_item_$->{0..1}
spring.shardingsphere.rules.sharding.tables.t_order_item.table-strategy.standard.sharding-column=order_id
spring.shardingsphere.rules.sharding.tables.t_order_item.table-strategy.standard.sharding-algorithm-name=t-order-item-inline
spring.shardingsphere.rules.sharding.sharding-algorithms.t-order-item-inline.type=INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.t-order-item-inline.props.algorithm-expression=t_order_item_$->{order_id % 2}

spring.shardingsphere.rules.sharding.tables.t_address.key-generate-strategy.column=id
spring.shardingsphere.rules.sharding.tables.t_address.key-generate-strategy.key-generator-name=snowflake
spring.shardingsphere.rules.sharding.tables.t_order.key-generate-strategy.column=order_id
spring.shardingsphere.rules.sharding.tables.t_order.key-generate-strategy.key-generator-name=snowflake
spring.shardingsphere.rules.sharding.tables.t_order_item.key-generate-strategy.column=order_item_id
spring.shardingsphere.rules.sharding.tables.t_order_item.key-generate-strategy.key-generator-name=snowflake
spring.shardingsphere.rules.sharding.key-generators.snowflake.type=SNOWFLAKE
spring.shardingsphere.rules.sharding.key-generators.snowflake.props.worker-id=123
```
### Actual behavior
Most attributes throw a warning that the configuration key cannot be found.I have configured ShardingJDBC according to the use case on the official website. In my environment, the use case on the official website is still Cannot resolve Configuration Property. My environment is IntelliJ IDEA2021.2.2,Eclipse Adoptium builds of OpenJDK 8U302, Spring-boot-starter-parent 2.5.5.
I tested shardingsphere-jdbC-core-spring-boot-starter on 5.0.0-beta and 5.0.0-alpha, both throwing the same warning. However, in Sharding-JDBC-spring-boot-Starter 4.1.1, I tested no such problem according to the official website documents.
```text
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.default-database-strategy.complex.sharding-columns'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.default-database-strategy.complex.sharding-algorithm-name'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.sharding-algorithms.order-db-complex.type'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.sharding-algorithms.order-db-complex.props.algorithm-expression'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.binding-tables[0]'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.broadcast-tables[0]'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.tables.t_order.actual-data-nodes'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.tables.t_order.table-strategy.standard.sharding-column'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.tables.t_order.table-strategy.standard.sharding-algorithm-name'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.sharding-algorithms.order-volume-range-table.type'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.sharding-algorithms.order-volume-range-table.props.range-lower'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.sharding-algorithms.order-volume-range-table.props.range-upper'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.sharding-algorithms.order-volume-range-table.props.sharding-volume'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.tables.t_order_item.actual-data-nodes'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.tables.t_order_item.table-strategy.standard.sharding-column'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.tables.t_order_item.table-strategy.standard.sharding-algorithm-name'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.sharding-algorithms.t-order-item-inline.type'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.sharding-algorithms.t-order-item-inline.props.algorithm-expression'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.tables.t_address.key-generate-strategy.column'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.tables.t_address.key-generate-strategy.key-generator-name'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.tables.t_order.key-generate-strategy.column'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.tables.t_order.key-generate-strategy.key-generator-name'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.tables.t_order_item.key-generate-strategy.column'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.tables.t_order_item.key-generate-strategy.key-generator-name'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.key-generators.snowflake.type'
Cannot resolve configuration property 'spring.shardingsphere.rules.sharding.key-generators.snowflake.props.worker-id'
```

image

image

### PR DESCRIPTION
**Pull request by zjcnb**
Fixes #13002

adjust before:

image

adjust after:

image

### CODE REVIEW

**Comment by totalo** [comment]
The meaning of this adjustment will be different, and there is no way to locate props.

**Comment by zjcnb** [comment]
> The problem now is that the keys of `props` cannot be automatically identified, but the `props` can be located. After such modification, there is no way to locate `props`.

I know your mean, but i think it 's same to datasource config, such as:

```
spring.shardingsphere.datasource.names=ds0

spring.shardingsphere.datasource.ds0.username=root
spring.shardingsphere.datasource.ds0.password=123456
spring.shardingsphere.datasource.ds0.url=jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
spring.shardingsphere.datasource.ds0.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.ds0.driver-class-name=com.mysql.jdbc.Driver
```

We can also discuss it.

**Comment by zjcnb** [comment]
As @totalo said, If this configuration is added, the auto prompt will be lost. So i will continue to investigate it.

**Comment by linghengqian** [comment]
Has this problem been resolved? I noticed that in version `5.0.0` there are still cases where the attributes cannot be resolved.
image

**Comment by zjcnb** [comment]
> Has this problem been resolved? I noticed that in version `5.0.0` there are still cases where the attributes cannot be resolved. image

@linghengqian Hi，we are looking for a better solution, and it does not affect the use it.

**Pull request closed without merging**
