### PR TITLE
Issue10979

### LINKED ISSUE #10979: [Doc] Optimize change history of ShardingSphere-JDBC Java API (Chinese)
Hi community,

This issue is for [#10887](https://github.com/apache/shardingsphere/issues/10887).

### Background

Refor to #10972

### Aim

Optimize change history of ShardingSphere-JDBC Java API (Chinese version). 

### How to

1. Migrate `Java API` change history from

   `4.1.2.Configuration Manual`->`Java API`->`Change History` to

   `7.2.API Change History`->`7.2.1.ShardingSphere-JDBC`->`Java API`;

2. Refer to the documents of each version on the official website, check whether the change history is correct, and fill in the missing parts.

3. The content organization of the change history is as follows:

   - ShardingSphere-5.0.0-beta
     - Sharding
     - Readwrite-splitting
     - Encryption
     - Shadow DB
     - Governance
   - ShardingSphere-4.x
     - Sharding
     - Readwrite-splitting
     - Data Masking
     - Orchestration
   - ShardingSphere-3.x
     - Sharding
     - Readwrite-splitting
     - Orchestration
   - ShardingSphere-2.x
     - Sharding
     - Readwrite-splitting
     - Orchestration

### Reference

- [Apache ShardingSphere website](https://shardingsphere.apache.org/)

- [Java API change history](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/configuration/java-api/change-history/)

### PR DESCRIPTION
**Pull request by yx9o**
Fixes #10979 .

Changes proposed in this pull request:
Optimize change history of ShardingSphere-JDBC Java API (Chinese version).

### CODE REVIEW

**Comment by menghaoranss** [comment]
> Fixes #10979 .
> 
> Changes proposed in this pull request:
> Optimize change history of ShardingSphere-JDBC Java API (Chinese version).

If the PR is just only part of this issue, please use For #issue_no or Refer to #issue_no

**Comment by tristaZero** [comment]
Hi Great to see you again, let's wait @RaigorJiang 's reveiw.

**Comment by RaigorJiang** [comment]
Hi @yx9o 
Should there be another file that needs to be removed?  
> https://github.com/apache/shardingsphere/blob/master/docs/document/content/user-manual/shardingsphere-jdbc/configuration/java-api/change-history.cn.md

**Comment by yx9o** [comment]
> Hi @yx9o
> Should there be another file that needs to be removed?
> 
> > https://github.com/apache/shardingsphere/blob/master/docs/document/content/user-manual/shardingsphere-jdbc/configuration/java-api/change-history.cn.md

Done.

**Review by RaigorJiang — APPROVED** [review]
Thank you for your careful editing, and also fixed the problems in the English version. Great work!

**Review by taojintianxia — APPROVED** [review]

**Review by menghaoranss — APPROVED** [review]

**Pull request merged**
