### PR TITLE
[SQL Definition Collation][Oracle]Collate the SQL definition of ROLLBACK

### LINKED ISSUE #9018: [SQL Definition Collation][Oracle]Collate the SQL definition of ROLLBACK
### Target
- Collate SQL definition of `ROLLBACK` to make SQL definition of `Apache ShardingSphere` the same with Oracle's.
- Add a test case

### How

1. Compare `ROLLBACK` definition in [Oficial SQL Doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ROLLBACK.html#GUID-94551F0C-A47F-43DE-BC68-9B1C1ED38C93) and [ShardingSphere SQL Doc](https://github.com/apache/shardingsphere/tree/master/shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle)
2. If there is any difference in ShardingSphere SQL Doc, please correct them referring to Official SQL Doc (**g4 file of ANTLR**)
3. Run `mvn install shardingsphere-sql-parser-oracle` 
4. Check whether there are any exceptions. If exists, please fix them. (Please pay attention to `xxxVisitor.class`)
5. Add new corresponding SQL case in `shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/main/resources/sql` and expected parsed result in `shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/main/resources/case`
6. Run SQLParserParameterizedTest (`shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/SQLParserParameterizedTest.java`).

### Tips
- Since this issue is a child one of #6480, I guess the PRs relevant to #6480 will give you some examples or hints.

### PR DESCRIPTION
**Pull request by ThanoshanMV**
Fixes #9018 

SQL definition of ROLLBACK

Changes proposed in this pull request:
- Modified `TCLStatement.g4` for ROLLBACK definition
- Added keyword `WORK` inside `OracleKeyword.g4`

### CODE REVIEW

**Comment by ThanoshanMV** [comment]
rollbackEPS
In this ROLLBACK Backus-Naur Form Syntax:
1. I considered keyword `WORK` as an Oracle Keyword. Is that okay or should we consider it as a Keyword?
2. How can we substitute the placeholders `savepoint` and `string`? 

Currently, I substituted `string` as `stringLiterals` imported from `BaseRule`

**Comment by tristaZero** [comment]
Hi @ThanoshanMV ，

This draft looks like a good start. I guess you have learned the basic rules of ANTLR. Please go ahead. :)

**Comment by ThanoshanMV** [comment]
Hi @tristaZero, I substituted placeholder `savepoint` in ROLLBACK definition as `savepointName`  imported from `BaseRule.g4`. Are there any changes we need to make for ROLLBACK definition. After these changes, I ran `mvn install` inside `shardingsphere-sql-parser-oracle` directory and build was success.

**Comment by tristaZero** [comment]
Hi @ThanoshanMV ,

It is a simple one, right? I think your PR has a correct definition for `ROLLBACK`, could you consider adding a test for your change? Like item 5, 6 said in #9018.

**Comment by tristaZero** [comment]
BTW, if you want to have an anther try, #9059 is still a good one for you.

**Comment by ThanoshanMV** [comment]
@tristaZero based on the existing codes on those files, I've done items 5 and 6 specified in #9018. Can you please check it?

**Comment by ThanoshanMV** [comment]
Yes, I would like to work on #9059

**Review by tristaZero — APPROVED** [review]
Looks nice.

**Pull request merged**
