### PR TITLE
add java version adapt for linux shell

### LINKED ISSUE #14941: proxy can not run where java11 configed. please adapt it!
## Feature Request

**For English only**, other languages will not accept.
 java8 run ss-proxy is OK, but java11 raise Exception:

_OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a futu release.
**Unrecognized VM option 'UseFastAccessorMethods'**
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit
### Is your feature request related to a problem?
Yes, java11 can not directly run, I need delete the report java_vm args._

### Describe the feature you would like.
I want run ss-proxy in multi java version for perfermance test.so I want start.sh auto check java version for it's java_vm args.

### PR DESCRIPTION
**Pull request by justbk2015**
Fixes #14941.

Changes proposed in this pull request:
- cur java options support java8、java11 and java17
- the java version format must be: `1.x.x_x`  or `1x.xx.xx`
- both support linux shell and windows bat

### CODE REVIEW

**Review by TeslaCN — CHANGES_REQUESTED** [review]
I tried the command `java -version 2>&1 | sed '1!d' | sed -e 's/"//g' | awk '{print $3}'`, but the result is not expected:
```
{22-01-22 22:43}bogon:~ wuweijie% java -version 2>&1 | sed '1!d' | sed -e 's/"//g' | awk '{print $3}'
JAVA_TOOL_OPTIONS:
```

The output of my `java -version`:
```
{22-01-22 22:44}bogon:~ wuweijie% java -version
Picked up JAVA_TOOL_OPTIONS: -Djava.net.preferIPv4Stack=true
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Zulu 8.58.0.13-CA-macos-aarch64) (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (Zulu 8.58.0.13-CA-macos-aarch64) (build 25.312-b07, mixed mode)
```

**Review by terrymanu — APPROVED** [review]
Great, thank you for contribution.

**Comment by terrymanu** [comment]
> I tried the command `java -version 2>&1 | sed '1!d' | sed -e 's/"//g' | awk '{print $3}'`, but the result is not expected:
> 
> ```
> {22-01-22 22:43}bogon:~ wuweijie% java -version 2>&1 | sed '1!d' | sed -e 's/"//g' | awk '{print $3}'
> JAVA_TOOL_OPTIONS:
> ```
> 
> The output of my `java -version`:
> 
> ```
> {22-01-22 22:44}bogon:~ wuweijie% java -version
> Picked up JAVA_TOOL_OPTIONS: -Djava.net.preferIPv4Stack=true
> openjdk version "1.8.0_312"
> OpenJDK Runtime Environment (Zulu 8.58.0.13-CA-macos-aarch64) (build 1.8.0_312-b07)
> OpenJDK 64-Bit Server VM (Zulu 8.58.0.13-CA-macos-aarch64) (build 25.312-b07, mixed mode)
> ```

I try `java -version` in my laptop, the result is 

```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment Corretto-8.292.10.1 (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM Corretto-8.292.10.1 (build 25.292-b10, mixed mode)
```

So the result of `java -version 2>&1 | sed '1!d' | sed -e 's/"//g' | awk '{print $3}'` are: `1.8.0_292`

I think the problem is in the first line `Picked up JAVA_TOOL_OPTIONS: -Djava.net.preferIPv4Stack=true`

Is there any way to find the java version line and awk it?

**Comment by justbk2015** [comment]
> > I tried the command `java -version 2>&1 | sed '1!d' | sed -e 's/"//g' | awk '{print $3}'`, but the result is not expected:
> > ```
> > {22-01-22 22:43}bogon:~ wuweijie% java -version 2>&1 | sed '1!d' | sed -e 's/"//g' | awk '{print $3}'
> > JAVA_TOOL_OPTIONS:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The output of my `java -version`:
> > ```
> > {22-01-22 22:44}bogon:~ wuweijie% java -version
> > Picked up JAVA_TOOL_OPTIONS: -Djava.net.preferIPv4Stack=true
> > openjdk version "1.8.0_312"
> > OpenJDK Runtime Environment (Zulu 8.58.0.13-CA-macos-aarch64) (build 1.8.0_312-b07)
> > OpenJDK 64-Bit Server VM (Zulu 8.58.0.13-CA-macos-aarch64) (build 25.312-b07, mixed mode)
> > ```
> 
> I try `java -version` in my laptop, the result is
> 
> ```
> openjdk version "1.8.0_292"
> OpenJDK Runtime Environment Corretto-8.292.10.1 (build 1.8.0_292-b10)
> OpenJDK 64-Bit Server VM Corretto-8.292.10.1 (build 25.292-b10, mixed mode)
> ```
> 
> So the result of `java -version 2>&1 | sed '1!d' | sed -e 's/"//g' | awk '{print $3}'` is: `1.8.0_292`
> 
> I think the problem is in the first line `Picked up JAVA_TOOL_OPTIONS: -Djava.net.preferIPv4Stack=true`
> 
> Is there any way to find the java version line and awk it?

I noticed this problem , I will handle it.

**Review by TeslaCN — APPROVED** [review]
LGTM

**Pull request merged**
