### PR TITLE
Support governance for JDBC scenario

### PR DESCRIPTION
**Pull request by dmsolr**
Fixes #ISSUSE_ID.

refer to #10082

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
The travis is OOM, please check

**Comment by terrymanu** [comment]
The travis still OOM

**Comment by tristaZero** [comment]
@dmsolr Hi How is it going? We are clearing open PRs, please have a look here.

**Comment by tristaZero** [comment]
Since we haven't received any feedback, I have to close it.

**Pull request closed without merging**
