### PR TITLE
improve(it): Delete the docker-compose file and adjust the docker dir…

### PR DESCRIPTION
**Pull request by JiekerTime**
The first step of the planned restructuring of integration testing is to remove the redundant docker-compose files and use testContainer instead.
#15089

### CODE REVIEW

**Comment by TeslaCN** [comment]
Hi @JiekerTime 
Is there any related issue?

**Comment by JiekerTime** [comment]
> 



> Hi @JiekerTime Is there any related issue?



> Hi @JiekerTime Is there any related issue?

Not yet, but some related will be submitted next

**Comment by TeslaCN** [comment]
Hi @JiekerTime 
Could you please resolve the conflicts?

**Comment by JiekerTime** [comment]
> Hi @JiekerTime Could you please resolve the conflicts?

Done~

**Review by terrymanu — APPROVED** [review]

**Pull request merged**
