### PR TITLE
Add more test cases for ShardingSphere-Proxy #7321

### LINKED ISSUE #7321: Add more test cases for ShardingSphere-Proxy
Please add test cases for proxy, the tasks are:

**shardingsphere-proxy-backend**
-  ~~ProxySQLExecutorCallback~~

**shardingsphere-proxy-frontend-core**
- ~~ShardingSphereProxy **(jian365066744)~~
- ~~FrontendChannelInboundHandler~~
- ~~ServerHandlerInitializer **(jian365066744)~~

**shardingsphere-proxy-frontend-mysql**
- ~~MySQLFrontendEngine~~
- ~~MySQLCommandExecuteEngine~~
- ~~MySQLUnsupportedCommandExecutor~~

**shardingsphere-proxy-frontend-postgresql**
- [x] PostgreSQLFrontendEngine **(sandynz)**
- [x] PostgreSQLCommandExecutorFactory **(sandynz)**
- [x] PostgreSQLUnsupportedCommandExecutor **(sandynz)**
- [x] PostgreSQLComTerminationExecutor **(gzdzss)**
- [x] PostgreSQLComDescribeExecutor **(gzdzss)**
- [x] PostgreSQLComExecuteExecutor **(gzdzss)**
- [x] PostgreSQLComParseExecutor **(gzdzss)**
- [x] PostgreSQLComSyncExecutor **(gzdzss)**
- [x] PostgreSQLUnsupportedCommandExecutor **(gzdzss)**
- [x] PostgreSQLErrPacketFactory  **(gzdzss)**

### PR DESCRIPTION
**Pull request by jian365066744**
Fixes #7321.

Changes proposed in this pull request:
-add test FrontendChannelInboundHandler
-add test ServerHandlerInitializer

### CODE REVIEW

**Review by tristaZero — CHANGES_REQUESTED** [review]
Thanks@jian365066744.

Glad to see your PR here, but I supposed fixing the CI test issue is expected.

**Comment by jian365066744** [comment]
I don't know&nbsp; why I get the error in build with maven compile .it show that lack of org.apache.shardingsphere.proxy.backend.communication.jdbc.connection.ResourceSynchronizer.but it run correctly in local.The detail like this.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/shardingsphere"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月17日(星期四) 上午10:32
收件人:&nbsp;"apache/shardingsphere"<shardingsphere@noreply.github.com&gt;;
抄送:&nbsp;"123"<365066744@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/shardingsphere] Add more test cases for ShardingSphere-Proxy #7321 (#7485)





 
@tristaZero requested changes on this pull request.
 
Thanks@jian365066744.
 
Glad to see your PR here, but I supposed fixing the CI test issue is expected.

**Comment by tristaZero** [comment]
@jian365066744 Hi, you mean the following error log is irrelated to your PR, don't you? I triggered the CI Test to rerun with your PR. Let us wait for the test result this time.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:testCompile (default-testCompile) on project shardingsphere-proxy-frontend-core: Compilation failure: Compilation failure: 
18313[ERROR] /home/travis/build/apache/shardingsphere/shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-core/src/test/java/org/apache/shardingsphere/proxy/frontend/netty/FrontendChannelInboundHandlerTest.java:[28,77] cannot find symbol
18314[ERROR]   symbol:   class ResourceSynchronizer
18315[ERROR]   location: package org.apache.shardingsphere.proxy.backend.communication.jdbc.connection
18316[ERROR] /home/travis/build/apache/shardingsphere/shardingsphere-proxy/shardingsphere-proxy-frontend/shardingsphere-proxy-frontend-core/src/test/java/org/apache/shardingsphere/proxy/frontend/netty/FrontendChannelInboundHandlerTest.java:[76,13] cannot find symbol
18317[ERROR]   symbol:   class ResourceSynchronizer
18318[ERROR]   location: class org.apache.shardingsphere.proxy.frontend.netty.FrontendChannelInboundHandlerTest
```

**Comment by tristaZero** [comment]
@jian365066744 Hi, the latest CI test result failed also. Since other PR could pass the CI test, I suppose you need to give the CI test a look. Have you built the master branch successfully with your changes locally?

**Comment by jian365066744** [comment]
juan:
&nbsp; &nbsp; &nbsp;thanks your details reply.The code is run correctly in location(mvn clean install&nbsp; -DskipTests&nbsp; -Dmaven.javadoc.skip=true) ,all test case also can pass.I don't konw why the CI test run failed ,and the logs show that cannot find symbol:&nbsp; &nbsp;class ResourceSynchronizer.can you give some suggestions or thoughts?





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "apache/shardingsphere"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月21日(星期一) 上午10:53
收件人:&nbsp;"apache/shardingsphere"<shardingsphere@noreply.github.com&gt;;
抄送:&nbsp;"123"<365066744@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/shardingsphere] Add more test cases for ShardingSphere-Proxy #7321 (#7485)





 
@jian365066744 Hi, the latest CI test result failed also. Since other PR could pass the CI test, I suppose you need to give the CI test a look. Have you built the master branch successfully with your changes locally?

**Comment by tristaZero** [comment]
Maybe a new PR for your changes can be raised. BTW, did you pull upstream from the master branch?

**Pull request closed without merging**
