### PR TITLE
add testcase for InsertValue

### LINKED ISSUE #6784: Add test case for InsertValue.toString method

### PR DESCRIPTION
**Pull request by herozeng**
Fixes #6784

Add test case for InsertValue.toString method
-
-
-

### CODE REVIEW

**Comment by herozeng** [comment]
anyone can help me review this pull request

**Comment by herozeng** [comment]
image


checkstyle build issue has beed fixed, but the CI build is still failed

**Comment by terrymanu** [comment]
The class `InsertValueTest ` is missing copyright

**Comment by herozeng** [comment]
CI build has been fixed

**Pull request merged**
