### PR TITLE
removes unused file and package

### LINKED ISSUE #23457: Remove unused annotation ShardingSphereTransactionType
Please remove unused annotation ShardingSphereTransactionType and the empty package.

### PR DESCRIPTION
**Pull request by CoderMayhem**
Fixes #23457 .

Changes proposed in this pull request:
  - Remove unused annotation ShardingSphereTransactionType

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Comment by zhaojinchao95** [comment]
@FlyingZC Hi, can you check it.

**Comment by FlyingZC** [comment]
@RaigorJiang Hi, have we removed the integration with Spring using `@ShardingSphereTransactionType`? Could we remove this `@ShardingSphereTransactionType`.

**Review by terrymanu — APPROVED** [review]

**Comment by terrymanu** [comment]
> @RaigorJiang Hi, have we removed the integration with Spring using `@ShardingSphereTransactionType`? Could we remove this `@ShardingSphereTransactionType`.

The spring namespaces are removed, so the related ShardingSphereTransactionType can be removed.

**Comment by RaigorJiang** [comment]
Yes, it's useless.

**Pull request merged**
