### PR TITLE
Creating `single-feature-example` for `shardingsphere-jdbc-example`.

### LINKED ISSUE #12563: [Examples] Create `single-feature-example` for `shardingsphere-jdbc-example`.
Hi community,

This issue is for #10887.

### Background
Refor to #12557.

### Aim
Create module `single-feature-example` for `shardingsphere-jdbc-example`, and move the existed example modules into the new module.

### How to
1. Create new module `single-feature-example` in `shardingsphere-jdbc-example`.
2. Move the following modules into `single-feature-example`:
   - cluster-mode-example
   - encrypt-example
   - extension-example
   - future-shadow-example
   - shadow-example
   - sharding-example
   - transaction-example
3. `hint-example` does not need to be moved, it will be processed in another task.

### PR DESCRIPTION
**Pull request by Swastyy**
Fixes #12563 

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Comment by RaigorJiang** [comment]
There are a lot of files affected by this PR, and I have started to review.

**Comment by RaigorJiang** [comment]
@Swastyy 
Thank you for the great work, I only found some minor problems:
After the module adjustment, the parent of the following modules should be changed to `single-feature-example`:
- cluster-mode-example
- encrypt-example
- extension-example
- future-shadow-example
- shadow-example
- sharding-example
- transaction-example

**Comment by RaigorJiang** [comment]
Due to the merger of #12796, there is a little conflict here. Please resolve.

**Comment by Swastyy** [comment]
> Due to the merger of #12796, there is a little conflict here. Please resolve.

@RaigorJiang I am not sure if the file I have imported (in the newest commit) is from the correct location. Please let me know if there is something wrong.

**Comment by Swastyy** [comment]
Also @RaigorJiang I am not able to resolve conflicts directly, it maybe because of the files have been moved to another location(which are moved in this PR).

**Comment by RaigorJiang** [comment]
Hi @Swastyy 
Don't worry, to resolve this conflict, you need to:
1. Checkout to your `local master branch`(any branch name) and synchronize from the `apache master`;
2. Checkout back to `Swastyy:12563`, and merge local master branch into current branch;
3. Resolve the conflict and modify it to the desired state;
4. Commit and push;

**Comment by RaigorJiang** [comment]
I am so sorry. @Swastyy 
It is a pity that the adjustment of a shadow example was merged before this, which brought us trouble again.
Sorry, can you consider starting from the master branch again?

**Comment by Swastyy** [comment]
> I am so sorry. @Swastyy It is a pity that the adjustment of a shadow example was merged before this, which brought us trouble again. Sorry, can you consider starting from the master branch again? Refer to ##12866.

Ah, okk I will close this PR and create a new PR.

**Comment by RaigorJiang** [comment]
Thanks a lot!

**Pull request closed without merging**
