### PR TITLE
Add sql execution release template method and adjust logic.

### PR DESCRIPTION
**Pull request by totalo**
Ref #12227.
Changes proposed in this pull request:
- Add sql execution release template method.
- release statement.

### CODE REVIEW

**Review by tristaZero — CHANGES_REQUESTED** [review]
Hi @totalo thanks, does this PR have a relevant issue?

**Comment by totalo** [comment]
> Hi @totalo thanks, does this PR have a relevant issue?

Sorry, not yet, I think I should create an issue specifically to improve the efficiency of integration testing.

**Review by tristaZero — APPROVED** [review]

**Comment by tristaZero** [comment]
@totalo Hi, sorry for my late response. 
But good job. ;-)

**Comment by totalo** [comment]
> @totalo Hi, sorry for my late response.
> But good job. ;-)

It's ok.😁

**Pull request merged**
