### PR TITLE
Add test case for DialectTableMetaDataLoaderFactory 

### LINKED ISSUE #16698: Add test case for DialectTableMetaDataLoaderFactory

### PR DESCRIPTION
**Pull request by weihubeats**
Fixes #16698.

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Review by terrymanu — COMMENTED** [review]
Hi, please split the test cases to multiple methods, one assertion only assert one case.

**Comment by terrymanu** [comment]
Could you change the PR title more make sense to describe the PR meaning?

**Comment by weihubeats** [comment]
ok, edited

**Review by terrymanu — APPROVED** [review]
Great

**Pull request merged**
