### PR TITLE
Upgrade antlr4 to 4.10.1

### LINKED ISSUE #19990: Update antlr4 to 4.10+
Hibernate 6.0.1+ was ues antlr4: 4.10+
when I force to use  antlr4: 4.10+，I got error：
org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version **4** (expected 3).
then when I force to use  antlr4: 4.9.x，I got error
org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version **3** (expected 4).

### PR DESCRIPTION
**Pull request by zhfeng**
Fixes #19990.

Changes proposed in this pull request:
  - Bump antlr4 to 4.10.1
  - Only run `antlr4-maven-plugin` in JDK 11
  - Add generated sources in JDK 8
  - After merging this PR, we should clarify on docs and wiki that it needs to use **JDK 11** to build sources at first as it can generate codes for the g4 parseres.

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [ ] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Comment by zhfeng** [comment]
@TeslaCN @terrymanu can you take a review?

**Review by terrymanu — APPROVED** [review]

**Comment by terrymanu** [comment]
LGTM

**Comment by TeslaCN** [comment]
Hi @zhfeng 
It seems that you have moved generated directory outside the `target`. The IDEA cannot recognize the code automatically.

image

**Comment by zhfeng** [comment]
Sorry for the inconvenience. I took these changes because it could build with `JDK 11` to generate the parser codes only once, and `mvn clean install` could work with `JDK 8`. Ony when you change `g4` files, you have to re-generate these codes by `JDK  11`. I suppose that this could less impact on the developers with `JDK 8`.

The for IDEA, I think you have to add source directory manually. such as `src/main/generated`. Do you have any other thought?

**Comment by TeslaCN** [comment]
> Sorry for the inconvenience. I took these changes because it could build with `JDK 11` to generate the parser codes only once, and `mvn clean install` could work with `JDK 8`. Ony when you change `g4` files, you have to re-generate these codes by `JDK 11`. I suppose that this could less impact on the developers with `JDK 8`.
> 
> The for IDEA, I think you have to add source directory manually. such as `src/main/generated`. Do you have any other thought?

I don't think manually add source directory is acceptable. Because we need to add 15 modules manually to start Proxy in IDEA, and these settings might be lost after doing some operation.

I will raise a PR to restore the path of generated codes.

**Comment by zhfeng** [comment]
@TeslaCN can you try this setting?

**Comment by TeslaCN** [comment]
> @TeslaCN can you try this setting?
> 

Of course I can. But I prefer the way that developers could open the project without addtional settings.

**Comment by zhfeng** [comment]
OK, I just wonder why IDEA could find `target\generate-sources\antlr4` as a source directory? It seems that `antlr-maven-plugin` is also running with `generate-sources` phase.

**Comment by zhfeng** [comment]
Hmm, it detects `target` and subdirectory automatically.

**Pull request merged**
