### PR TITLE
Added support for STRRIGHT alias in Doris (#31508)

### PR DESCRIPTION
**Pull request by danigiri**
Continuing with Doris parsing support. 
In this case `RIGHT` is already implemented and supported by both MySQL and Doris so ammended the tests and added `STRRIGHT` support which is an alias in Doris.

Continues to address #31508.

Changes proposed in this pull request:
- Added parsing support for the `STRRIGHT` alias in Doris
- Updated existing MySQL test to reflect that `RIGHT` is also supported by Doris
- Added `STRRIGHT`-specific test
- Marked `// DORIS ADDED BEGIN|END` Doris-specific changes, and fixed a typo in existing one
- Added as a `regularFunctionName` which is where `RIGHT` is so no java changes should be needed
- Executed `SELECT STRRIGHT('foobarbar',4)` in Doris 3.0.2 correctly

#### Next
- ~~get PR id to update release notes~~
- ~~finish compiling Doris v3 to test the query code~~ my local machine is not powerful enough

---

Before committing this PR, I'm sure that I have checked the following options:
- [✅] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [✅] I have self-reviewed the commit code.
- [✅] I have (or in comment I request) added corresponding labels for the pull request.
- [✅] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [✅] I have made corresponding changes to the documentation.
- [✅] I have added corresponding unit tests for my changes.
- [✅] `mvn spotless:apply -Pcheck`
- [✅] `mvn test -Dit.test=InternalDorisParserIT` in `shardingsphere/parser/sql/dialect/doris` (need to specify it.test)
- [✅] Executed test case in Doris v2.0.3 – `SELECT STRRIGHT('foobarbar',4)`

### CODE REVIEW

**Comment by danigiri** [comment]
I will look at the test results again as [76b9007](https://github.com/apache/shardingsphere/pull/33393/commits/76b9007633ac4a154c52d196087a2e931037f442) was supposed to fix the failing test

**Comment by danigiri** [comment]
Looks like on the most current code `mvn test -Dtest=InternalDorisParserIT` is no longer picking up the tests, using `mvn test -Dit.test=InternalDorisParserIT` does not give an error but looks like it does not pick it up either.
The most consistent way for me to test is to do a full rebuild in one of my separate test machines after a commit but that is a bit slow.

Waiting for that full rebuild to finish and issuing a fresh commit

**Comment by danigiri** [comment]
All checks passed and it looks good, just did a merge with upstream to have it up to date. Checks will be redone but not expecting any issues there. Ready to be reviewed

**Review by strongduanmu — APPROVED** [review]
Looks great, merged. @danigiri Thank you for your excellent code.

**Pull request merged**
