### PR TITLE
Added tests for MetaDataContextsFactory

### LINKED ISSUE #19262: Add test case for MetaDataContextsFactory

### PR DESCRIPTION
**Pull request by mayank-aggarwal28**
Fixes #19262.

Changes proposed in this pull request:
- Added 3 tests for MetaDataContextsFactory
- Covers 2 success scenarios and 1 failure scenario

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
1. Please fix compile error
2. The test method are too long, could you split them into smaller methods?

**Comment by mayank-aggarwal28** [comment]
@terrymanu I did not see any compilation errors while running locally on my system. So I am not sure why the pipeline is breaking.

Regarding the test methods, I have refactored them and pushed in a new commit.

**Review by terrymanu — CHANGES_REQUESTED** [review]
CI break reason: You have 5 Checkstyle violations.

Details:

Error:  src/test/java/org/apache/shardingsphere/mode/MetaDataContextsFactoryTest.java:[74,5] (coding) DeclarationOrder: Variable access definition in wrong order.
Error:  src/test/java/org/apache/shardingsphere/mode/MetaDataContextsFactoryTest.java:[75,40] (design) VisibilityModifier: Variable 'mockDatabaseConfigs' must be private and have accessor methods.
Error:  src/test/java/org/apache/shardingsphere/mode/MetaDataContextsFactoryTest.java:[110] (whitespace) EmptyLineSeparator: 'VARIABLE_DEF' should be separated from previous statement.
Error:  src/test/java/org/apache/shardingsphere/mode/MetaDataContextsFactoryTest.java:[110,5] (coding) DeclarationOrder: Variable access definition in wrong order.
Error:  src/test/java/org/apache/shardingsphere/mode/MetaDataContextsFactoryTest.java:[114,24] (whitespace) WhitespaceAround: '{' is not preceded with whitespace.

**Comment by terrymanu** [comment]
The CI still failed

**Comment by terrymanu** [comment]
@mayank-aggarwal28 The progress of this PR has not been upgraded for a long time. If there is no update, I will close it soon.

**Comment by mayank-aggarwal28** [comment]
> @mayank-aggarwal28 The progress of this PR has not been upgraded for a long time. If there is no update, I will close it soon.

@terrymanu Please close it for now as I am unable to work on this at the moment due to some urgent commitments. I will open a fresh PR once I am working on this again.

**Comment by terrymanu** [comment]
> > @mayank-aggarwal28 The progress of this PR has not been upgraded for a long time. If there is no update, I will close it soon.
> 
> @terrymanu Please close it for now as I am unable to work on this at the moment due to some urgent commitments. I will open a fresh PR once I am working on this again.

Ok, welcome come back again.

**Pull request closed without merging**
