### PR TITLE
set writeonly hint based on connection username

### LINKED ISSUE #14472: route sql to write datasource based on username or listen address.
### Describe the feature you would like.
read write split datasource can be routed through hint. but it'll be more convenient to use username or connection host to set hint automatically.

example:
when user name is `db_writeonly`, session could set writeonly hint automatically;

or we can add a new property `writeOnlyHost` to read write split configuration, if user connect to database use `writeOnlyHost` then set writeonly hint automatically on that session. (it may difficult to get connection host, since host is always converted to IP address before connect to database. however, if user connect to database use lo network, we can distinguish different host ip, like 127.0.0.1, 127.0.0.2, and etc)

### PR DESCRIPTION
**Pull request by roodkcab**
Fixes #14472 .

Changes proposed in this pull request:
- set write only hint based on session username

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
This feature is for readwrite split, could we consider enclosure it into readwrite-splitting module?

**Comment by roodkcab** [comment]
> This feature is for readwrite split, could we consider enclosure it into readwrite-splitting module?

then I guess we have to encapsulate session information into sql context ?

**Comment by terrymanu** [comment]
> > This feature is for readwrite split, could we consider enclosure it into readwrite-splitting module?
> 
> then I guess we have to encapsulate session information into sql context ?

Yes, it is the better way

**Comment by terrymanu** [comment]
This pull request is long time ago, I just close it.

**Pull request closed without merging**
