### PR TITLE
Update sql-parser.cn.md

### PR DESCRIPTION
**Pull request by Swastyy**
related to #21477

### CODE REVIEW

**Review by strongduanmu — CHANGES_REQUESTED** [review]
Hi @Swastyy, can you fix code conflict?

**Comment by Swastyy** [comment]
> Hi @Swastyy, can you fix code conflict?

done

**Comment by strongduanmu** [comment]
@Swastyy Does this PR seem to be no different from the existing documentation?

**Comment by Swastyy** [comment]
Oh I see, its been already corrected, I will close it.

**Pull request closed without merging**
