### PR TITLE
Automatically publish docs to shardingsphere-doc repository when released.

### LINKED ISSUE #9697: Realizing automatic standard process through github actions.
- [ ] Automatically publish docs to [shardingsphere-doc](https://github.com/apache/shardingsphere-doc) repository when released.
- [ ] Automate the issue standard handling process.
- [ ] Automatically publish image to docker registry when released.

### PR DESCRIPTION
**Pull request by QiliangFan**
Feature #9697
`Task 1`

Changes proposed in this pull request:
- `doc.yml`: When releases are created, the relative workflow of the repo [shardingsphere-doc](https://github.com/apache/shardingsphere-doc) is invoked
- `document/current` => `document/preview`
- The token,  `PERSONAL_TOKEN` , must be configured to invoke other repositorys' workflow

### CODE REVIEW

**Comment by tristaZero** [comment]
Hi @QiliangFan ,

Welcome your virgin PR here. @avalon5666 could you have a review?

**Comment by tristaZero** [comment]
So is there any progress? @QiliangFan @avalon5666

**Comment by QiliangFan** [comment]
> So is there any progress? @QiliangFan @avalon5666

@tristaZero  Some changes are under development. More versions of the document will be displayed on the homepage

**Comment by tristaZero** [comment]
@avalon5666 so is it ready to merge this one?

**Pull request closed without merging**
