### PR TITLE
Add ShardingAlgorithmType enum to replace the sharing algorithm type with magic string. 

### PR DESCRIPTION
**Pull request by likly**
Add ShardingAlgorithmType enum to replace the sharing algorithm type with magic string.

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
Sharding algorithms are dynamic and loaded via SPI.
The enum is static config and broken OCP.
So it is better to do not use enum to define sharding algorithm types.

**Comment by likly** [comment]
This enum only be used in build-in sharding algorithms, just for easy manage the SPI type of build-in sharding algorithms.
The user also can define custom sharidng algotithm with magic string or custom enum.

**Comment by likly** [comment]
> Sharding algorithms are dynamic and loaded via SPI.
> The enum is static config and broken OCP.
> So it is better to do not use enum to define sharding algorithm types.

This Enum only used for build-in sharding algorithms to manage the SPI types easily.
And this enum is not broken OCP,  Sharding algorithms still are dynamic and loaded via SPI.

**Comment by terrymanu** [comment]
> > Sharding algorithms are dynamic and loaded via SPI.
> > The enum is static config and broken OCP.
> > So it is better to do not use enum to define sharding algorithm types.
> 
> This Enum only used for build-in sharding algorithms to manage the SPI types easily.
> And this enum is not broken OCP, Sharding algorithms still are dynamic and loaded via SPI.

If user custom a new sharding algorithm, do they need to update the enum? 
If yes, OCP is broken; 
If not the custom sharding algorithm is different with built-in one, we'd like keep the customization sharding algorithm consist with built-in one.

**Comment by likly** [comment]
> > > Sharding algorithms are dynamic and loaded via SPI.
> > > The enum is static config and broken OCP.
> > > So it is better to do not use enum to define sharding algorithm types.
> > 
> > 
> > This Enum only used for build-in sharding algorithms to manage the SPI types easily.
> > And this enum is not broken OCP, Sharding algorithms still are dynamic and loaded via SPI.
> 
> If user custom a new sharding algorithm, do they need to update the enum?
> If yes, OCP is broken;
> If not the custom sharding algorithm is different with built-in one, we'd like keep the customization sharding algorithm consist with built-in one.

Broken the OCI maybe appecd when the  `getType()` method  return type change to a enum type.
But this enum just for replace the magic string with `enum.name()`.

The getType method just changed like this:

```java
    public String getType() {
        // old: return "INLINE";
        // now: return the name of `INLINE` enum constant.
        return ShardingAlgorithmType.INLINE.name();
    }
```

The method definition is not changed.

**Comment by likly** [comment]
The user also can find how many built-in algorithms quickly throught the enum of ShardingAlgorithmType.

**Comment by terrymanu** [comment]
we'd like keep the customization sharding algorithm consist with built-in one.

**Comment by terrymanu** [comment]
May I close this pr?

**Pull request closed without merging**
