### PR TITLE
ORDER BY merge result NPE

### LINKED ISSUE #7877: NPE at order by
**About:**
version: 5.0.0-RC1-SNAPSHOT
env: mybatis/druid
Sharding: user % 8

origin_sql:  SELECT id, user,  type FROM user_t WHERE (id > 0) ORDER BY id ASC limit 10;
actual_sql: SELECT id, user,  type FROM user_t_0 WHERE (id > 0) ORDER BY id ASC limit 10;

Exception at: **_tableMetaData_**

stack[0]: 	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.getOrderValuesCaseSensitiveFromTables(OrderByValue.java:74)

**code:**

    private boolean getOrderValuesCaseSensitiveFromTables(final SelectStatementContext selectStatementContext,
                                                          final PhysicalSchemaMetaData schemaMetaData, final OrderByItem eachOrderByItem) throws SQLException {
        for (SimpleTableSegment eachSimpleTableSegment : selectStatementContext.getAllTables()) {
            String tableName = eachSimpleTableSegment.getTableName().getIdentifier().getValue();
            PhysicalTableMetaData tableMetaData = schemaMetaData.get(tableName);
            Map<String, PhysicalColumnMetaData> columns = **tableMetaData**.getColumns();
            OrderByItemSegment orderByItemSegment = eachOrderByItem.getSegment();
            if (orderByItemSegment instanceof ColumnOrderByItemSegment) {
                String columnName = ((ColumnOrderByItemSegment) orderByItemSegment).getColumn().getIdentifier().getValue();
                if (columns.containsKey(columnName)) {
                    return columns.get(columnName).isCaseSensitive();
                }
            } else if (orderByItemSegment instanceof IndexOrderByItemSegment) {
                int columnIndex = ((IndexOrderByItemSegment) orderByItemSegment).getColumnIndex();
                String columnName = queryResult.getColumnName(columnIndex);
                if (columns.containsKey(columnName)) {
                    return columns.get(columnName).isCaseSensitive();
                }
            } else {
                return false;
            }
        }
        return false;
    }

### PR DESCRIPTION
**Pull request by waylink**
https://github.com/apache/shardingsphere/issues/7877

Fixes #7877.

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Comment by tristaZero** [comment]
Thanks for your issue and the first PR @waylink ! Welcome your joining. I guess the author @terrymanu  of the relevant programming can help review this one. Let us leave him some time. :)

**Review by terrymanu — CHANGES_REQUESTED** [review]
It perhaps not the root cause.
Merge for order by should only process with sharding table only, if we pass all tables (allSchemaMetaData) can not help the root cause of NPE thrown.
It is better to investigate why sharding table got NPE first.

**Comment by kimmking** [comment]
I test it works well.

**Comment by kimmking** [comment]
I think we should close this pr.

**Comment by terrymanu** [comment]
Closed because changes are invalid

**Pull request closed without merging**
