### PR TITLE
Create SingleTableSQLRouterTest.java

### PR DESCRIPTION
**Pull request by zzs52**
Fixes Add test case for SingleTableSQLRouter #12214.

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Review by strongduanmu — CHANGES_REQUESTED** [review]
Hi @zzs52, thank you for your contribution, but can you fix ci error first?

**Comment by zzs52** [comment]
> Hi @zzs52, thank you for your contribution, but can you fix ci error first?

Ok,I am checking for errors.

**Comment by strongduanmu** [comment]
> Hi @strongduanmu , there is an error and I don’t know how to solve it. I am wondering whether to modify a small configuration problem in pom.xml.

@zzs52 It seems that it is caused by the environment. I will re-trigger ci.

**Comment by zzs52** [comment]
> > Hi @strongduanmu , there is an error and I don’t know how to solve it. I am wondering whether to modify a small configuration problem in pom.xml.
> 
> @zzs52 It seems that it is caused by the environment. I will re-trigger ci.

Ok,thanks.

**Review by strongduanmu — APPROVED** [review]

**Comment by strongduanmu** [comment]
Hi @zzs52, thank you very much for your PR, but can you add some more test cases to ensure that different logical branches can be covered? In addition, the `decorateRouteContext` method also requires some unit testing.

**Comment by zzs52** [comment]
> Hi @zzs52, thank you very much for your PR, but can you add some more test cases to ensure that different logical branches can be covered? In addition, the `decorateRouteContext` method also requires some unit testing.

Ok,I will add a few more tests later.

**Pull request merged**
