### PR TITLE
Use Parameterized + XML instead of static test with DistSQLStatementParserEngineTest

### LINKED ISSUE #10581: Use Parameterized + XML instead of static test with DistSQLStatementParserEngineTest
The DistSQLStatementParserEngineTest is split to:

- DistSQLStatementParserEngineTest
- EncryptRuleStatementParserEngineTest
- DatabaseDiscoveryRuleStatementParserEngineTest
- ReadwriteSplittingRuleStatementParserEngineTest
- ShardingRuleStatementParserEngineTest

FYI: SQLParserParameterizedTest

### PR DESCRIPTION
**Pull request by totalo**
Fixes #10581 .

Changes proposed in this pull request:
- Use Parameterized + XML instead of static test with DistSQLStatementParserEngineTest

### CODE REVIEW

**Review by terrymanu — COMMENTED** [review]
The code is similar with original SQL parser test, could we consider about reuse them?

**Comment by totalo** [comment]
> The code is similar with original SQL parser test, could we consider about reuse them? 

Of course. I will do that.

**Comment by terrymanu** [comment]
> > The code is similar with original SQL parser test, could we consider about reuse them?
> 
> Of course. I will do that.

Thank you, reuse same SQL parser test engine with the common SQL parser is better.
Maybe we just need to consider about extend the JAXB sql cases and assertion.

**Comment by terrymanu** [comment]
The class DistSQLStatementParserEngineTest split to multiple classes, I just update the issue, please check.

**Comment by totalo** [comment]
> The class DistSQLStatementParserEngineTest split to multiple classes, I just update the issue, please check.

ok,Get it!

**Comment by terrymanu** [comment]
Thank you for the excellent PR!

**Review by terrymanu — APPROVED** [review]

**Comment by terrymanu** [comment]
@totalo Hi, I create a new issue #11014 for improve DistSQL parser test engine, do you interest it?

**Pull request merged**
