### PR TITLE
Fix nightly builds and release profile of ShardingSphere Proxy Native

### PR DESCRIPTION
**Pull request by linghengqian**
For #23873 and #21347.

Changes proposed in this pull request:
  - Fix nightly builds of ShardingSphere Proxy Native. Refer to https://github.com/apache/shardingsphere/actions/runs/4076339389/jobs/7023936873 .
  - Fix release profile of ShardingSphere Proxy Native. Previously this Profile did not contain GraalVM Native Image binaries. Since the Release Profile is always executed after the Native Profile for ShardingSphere Proxy Native, it is a more reasonable choice to merge the two profiles.
  - Update protobuf-java-util to match GraalVM reachability metadata. Reference https://github.com/oracle/graalvm-reachability-metadata/pull/167 .
  - Update zookeeper to resolve ZOOKEEPER-4460 that prevents GraalVM Native Image from compiling, see https://github.com/oracle/graalvm-reachability-metadata/issues/163 .
  - Update jetcd-core to match GraalVM reachability metadata, see https://github.com/oracle/graalvm-reachability-metadata/pull/170 .
  - Split caffeine version in native profile to match GraalVM reachability metadata. Reference https://github.com/oracle/graalvm-reachability-metadata/pull/193 .
  - Update LICENSE.

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [x] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Comment by linghengqian** [comment]
- The volume expansion problem of Docker Image continues to be tracked in the issue mentioned in https://github.com/apache/shardingsphere/issues/21347#issuecomment-1415672232 .  This PR is not affected.

**Comment by linghengqian** [comment]
> * The volume expansion problem of Docker Image continues to be tracked in the issue mentioned in [Make ShardingSphere Proxy in GraalVM Native Image form available #21347 (comment)](https://github.com/apache/shardingsphere/issues/21347#issuecomment-1415672232) .  This PR is not affected.
> * update in 2023.02.04: Listed as a draft for now as I'm testing a new Dockerfile against the contents of [Cannot allow to specify not to download `native-image` component graalvm/graalvm-jdk-downloader#5](https://github.com/graalvm/graalvm-jdk-downloader/issues/5) .

- Done.

**Comment by linghengqian** [comment]
- According to https://github.com/apache/shardingsphere/discussions/21724 , Ping @zhaojinchao95 to help review.

**Comment by linghengqian** [comment]
- Since https://github.com/oracle/graal/commit/4a70d11be7c1c554c5e6b671491345835a883fcd deprecated the GRAALVM_HOME system environment variable in GraalVM CE 23.0, I made additional changes.

**Review by terrymanu — APPROVED** [review]

**Pull request merged**
