### PR TITLE
Simplify Sharing Specification in Create View Oracle

### LINKED ISSUE #29551: Simplify Sharing Specification in Create View Oracle
## Feature Request

Simplify Sharing Specification in Create View.

### Is your feature request related to a problem?

N/A

### Describe the feature you would like.

Use function declaration of `createSharingClause` instead of defining the logic.

### PR DESCRIPTION
**Pull request by ilyasahsan123**
Fixes #29551.

Changes proposed in this pull request:
  - Simplify Sharing Specification in Create View Oracle

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Comment by ilyasahsan123** [comment]
This is just a minor nitpick, @strongduanmu. Is it acceptable?

**Review by strongduanmu — CHANGES_REQUESTED** [review]
Hi @ilyasahsan123, thank you for your contribution. Can you show the original sql sytax in oracle offical doc? And add sql parse test case for this change?

**Review by strongduanmu — APPROVED** [review]
Sorry, I checked the createSharingClause syntax and they do have redundancy. Thank you for your contribution, merged.

```
createSharingClause
    : (SHARING EQ_ (METADATA | DATA | EXTENDED DATA | NONE))?
    ;
```

**Comment by ilyasahsan123** [comment]
Thanks for your feedback and approval, @strongduanmu. It is also my bad in giving PR name. I should rename it to something like "remove redundancy". 

Thanks anyway.

**Comment by strongduanmu** [comment]
> Thanks for your feedback and approval, @strongduanmu. It is also my bad in giving PR name. I should rename it to something like "remove redundancy".
> 
> Thanks anyway.

Yes, you can try to modify the PR title. In addition, it seems that you are familiar with ANTLR, are you interested in getting involved in more SQL parsing tasks? For example, Oracle and SQLServer. ShardingSphere SQL parsing will get much better if you can get involved. 😁

**Comment by ilyasahsan123** [comment]
Yes, I am very interested in getting involved in the parsing world and I am currently looking into following issues: 

- Oracle: [here](https://github.com/apache/shardingsphere/issues?q=is%3Aopen+is%3Aissue+label%3A%22in%3A+SQL+parse%22+label%3A%22db%3A+Oracle%22)
- SQLServer: [here](https://github.com/apache/shardingsphere/issues/29149)

Are there any GitHub issues that I can get involved in?

**Comment by strongduanmu** [comment]
@ilyasahsan123 You can participate in these missions first, and we will post new missions later, so you can follow and participate in them.

**Comment by ilyasahsan123** [comment]
Excited. Thanks for the info, @strongduanmu.

**Pull request merged**
