### PR TITLE
[Issue#18446] Add test case for AlterTransactionRuleHandler

### LINKED ISSUE #18446: Add test case for AlterTransactionRuleHandler

### PR DESCRIPTION
**Pull request by git000**
Fixes #18446 .

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
Please fix the CI

**Comment by git000** [comment]
Error on jdk11:
ShowTransactionRuleHandlerTest.assertExecutorWithLocal:71 » NullPointer
ShowTransactionRuleHandlerTest.assertExecutorWithXA:52 » NullPointer

 java.lang.NullPointerException
2022-06-26T05:29:39.4540896Z 	at org.apache.shardingsphere.proxy.backend.text.distsql.ral.common.queryable.ShowTransactionRuleHandler.getRows(ShowTransactionRuleHandler.java:52)
2022-06-26T05:29:39.4542025Z 	at org.apache.shardingsphere.proxy.backend.text.distsql.ral.QueryableRALBackendHandler.createMergedResult(QueryableRALBackendHandler.java:63)
2022-06-26T05:29:39.4543055Z 	at org.apache.shardingsphere.proxy.backend.text.distsql.ral.QueryableRALBackendHandler.execute(QueryableRALBackendHandler.java:54)
2022-06-26T05:29:39.4544257Z 	at org.apache.shardingsphere.proxy.backend.text.distsql.ral.common.queryable.ShowTransactionRuleHandlerTest.assertExecutorWithLocal(ShowTransactionRuleHandlerTest.java:71)

execute ShowTransactionRuleHandlerTest on the local environment without error

**Comment by git000** [comment]
> Please fix the CI

Error on jdk11:
ShowTransactionRuleHandlerTest.assertExecutorWithLocal:71 » NullPointer
ShowTransactionRuleHandlerTest.assertExecutorWithXA:52 » NullPointer

java.lang.NullPointerException
2022-06-26T05:29:39.4540896Z at org.apache.shardingsphere.proxy.backend.text.distsql.ral.common.queryable.ShowTransactionRuleHandler.getRows(ShowTransactionRuleHandler.java:52)
2022-06-26T05:29:39.4542025Z at org.apache.shardingsphere.proxy.backend.text.distsql.ral.QueryableRALBackendHandler.createMergedResult(QueryableRALBackendHandler.java:63)
2022-06-26T05:29:39.4543055Z at org.apache.shardingsphere.proxy.backend.text.distsql.ral.QueryableRALBackendHandler.execute(QueryableRALBackendHandler.java:54)
2022-06-26T05:29:39.4544257Z at org.apache.shardingsphere.proxy.backend.text.distsql.ral.common.queryable.ShowTransactionRuleHandlerTest.assertExecutorWithLocal(ShowTransactionRuleHandlerTest.java:71)

execute ShowTransactionRuleHandlerTest on the local environment without error

**Review by terrymanu — CHANGES_REQUESTED** [review]
Please fix CI

**Comment by terrymanu** [comment]
The issue is merged by other PR, I just close it.

**Pull request closed without merging**
