### PR TITLE
Support Parsing `DROP RULE` in PostgreSQL

### PR DESCRIPTION
**Pull request by everly-gif**
Related to issue #14015 

Changes proposed in this pull request:
- Adds `DROP RULE`
- Adds `Tests`

### CODE REVIEW

**Comment by everly-gif** [comment]
I get an error : `1 counts of IllegalAnnotationExceptions
Two classes have the same XML type name "dropRuleStatementTestCase"`

```
this problem is related to the following location:
		at org.apache.shardingsphere.test.sql.parser.parameterized.jaxb.cases.domain.statement.ddl.DropRuleStatementTestCase
		at private final java.util.List org.apache.shardingsphere.test.sql.parser.parameterized.jaxb.cases.domain.SQLParserTestCases.dropRuleTestCases
		at org.apache.shardingsphere.test.sql.parser.parameterized.jaxb.cases.domain.SQLParserTestCases
	this problem is related to the following location:
		at org.apache.shardingsphere.test.sql.parser.parameterized.jaxb.cases.domain.statement.DropRuleStatementTestCase
		at org.apache.shardingsphere.test.sql.parser.parameterized.jaxb.cases.domain.statement.distsql.rdl.drop.DropReadwriteSplittingRuleStatementTestCase
		at private final java.util.List org.apache.shardingsphere.test.sql.parser.parameterized.jaxb.cases.domain.SQLParserTestCases.dropReadwriteSplittingRuleTestCase
		at org.apache.shardingsphere.test.sql.parser.parameterized.jaxb.cases.domain.SQLParserTestCases
```
That's the one failing CI

**Comment by Liangda-w** [comment]
> I get an error : `1 counts of IllegalAnnotationExceptions Two classes have the same XML type name "dropRuleStatementTestCase"`
> 
> ```
> this problem is related to the following location:
> 		at org.apache.shardingsphere.test.sql.parser.parameterized.jaxb.cases.domain.statement.ddl.DropRuleStatementTestCase
> 		at private final java.util.List org.apache.shardingsphere.test.sql.parser.parameterized.jaxb.cases.domain.SQLParserTestCases.dropRuleTestCases
> 		at org.apache.shardingsphere.test.sql.parser.parameterized.jaxb.cases.domain.SQLParserTestCases
> 	this problem is related to the following location:
> 		at org.apache.shardingsphere.test.sql.parser.parameterized.jaxb.cases.domain.statement.DropRuleStatementTestCase
> 		at org.apache.shardingsphere.test.sql.parser.parameterized.jaxb.cases.domain.statement.distsql.rdl.drop.DropReadwriteSplittingRuleStatementTestCase
> 		at private final java.util.List org.apache.shardingsphere.test.sql.parser.parameterized.jaxb.cases.domain.SQLParserTestCases.dropReadwriteSplittingRuleTestCase
> 		at org.apache.shardingsphere.test.sql.parser.parameterized.jaxb.cases.domain.SQLParserTestCases
> ```
> 
> That's the one failing CI

as the error text indicate, there are two classes named `dropRuleStatementTestCase`, another one is [here](https://github.com/lanchengx/shardingsphere/blob/b43c530a1a91fde26e66c623b69fee24bc12bc2e/shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/DropRuleStatementTestCase.java) for `distsql drop rule`, maybe you can try to annotate that class with `@XmlType(name="distsql")`

**Comment by everly-gif** [comment]
Thanks @Liangda-w , I wanted to know if there was some other way to go about it, thanks for always guiding me. I have made the changes , please do review them! Also the tag for this PR should be `db: PostgreSQL` :)

**Comment by strongduanmu** [comment]
Hi @everly-gif, can you solve code conflict?

**Comment by everly-gif** [comment]
Sure, fixed it @strongduanmu

**Review by strongduanmu — APPROVED** [review]
@everly-gif Great job, please go ahead.

**Pull request merged**
