### PR TITLE
fix load all "TableMetaData" twice for "Improve the initialization of OptimizeContextFactory" (#10678)

### LINKED ISSUE #10678: Improve the initialization of OptimizeContextFactory
Hi,

If you're interested in this one, please comment below so I can assign it to u. :)

### Background
`OptimizeContextFactory` is created in the constructor of `StandardMetaDataContexts` with `metaDataMap`.
If you dive into the constructor of `OptimizeContextFactory` and `MetaDataContextsBuilder`,  you will find both handlings of them need loading table metadata. Therefore, this issue is to reduce the unnecessary and duplicated table metadata loading.

### Expected result
- Create `OptimizeContextFactory` in `MetaDataContextsBuilder`
- Share the table metadata loading between `OptimizeContextFactory` and `Map<String, ShardingSphereMetaData>` of `StandardMetaDataContexts`

### How
- The entrance is `buildSchema()` of `MetaDataContextsBuilder`
- Change the result of `SchemaBuilder.build()` to `Map<ActualTableMetadata, LogicTableMetadata>`
In `SchemaBuilder`,
`addRuleConfiguredTables` returns `logicTableMetadata`. On the other hand `appendRemainTables(materials, result);` returns `actualTableMetadata`. So we need to call `load()` and `decorate()` of `TableMetaDataBuilder` respectively to get the acutal and logic ones.
- Assemble `ShardingSphereSchema` using the list of logic table metadata
- Create `OptimizeContextFactory` by the list of actual table metadata
- Remove the deprecated constructors of `FederateSchemaMetadata` and `FederateTableMetadata`

### PR DESCRIPTION
**Pull request by Beyondeclipse**
Fixes #10678.

Changes proposed in this pull request:
- fix load all "TableMetaData" twice

### CODE REVIEW

**Comment by tristaZero** [comment]
Hi @Beyondeclipse Thanks for your PR, 
Could you give a look at #10840? Do you think this PR covers what you changed?

**Review by tristaZero — CHANGES_REQUESTED** [review]
Hi @Beyondeclipse Thanks for your PR,
Could you give a look at #10840? Do you think this PR covers what you changed?

**Comment by Beyondeclipse** [comment]
> Hi @Beyondeclipse Thanks for your PR,
> Could you give a look at #10840? Do you think this PR covers what you changed?

Oh, yes, it does. But that PR seams a little complicate, and may has room for improvement.

**Review by tristaZero — CHANGES_REQUESTED** [review]
Hi? Only one new line?

**Comment by tristaZero** [comment]
Hi there?

**Comment by Beyondeclipse** [comment]
> Hi there?

I am sorry for my late reply. I have made another PR #11345, and this PR can be canceled.

**Pull request closed without merging**
