### PR TITLE
Add more unit test for ShardingTokenGenerateBuilder

### LINKED ISSUE #14911: Add more unit test for ShardingTokenGenerateBuilder
Hi, community:

This issue is to add more unit tests for the ShardingTokenGenerateBuilder class. Welcome to claim them.

The specific subtasks are as follows:

- [ ] Add unit test for ShardingTokenGenerateBuilder#getSQLTokenGenerators

### PR DESCRIPTION
**Pull request by LeeGuoPing**
Fixes #14911.

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Review by strongduanmu — CHANGES_REQUESTED** [review]
Hi @LeeGuoPing, thank you for your contribution, can you sync the master branch? The logic of ShardingTokenGenerateBuilder may be changed.

**Comment by LeeGuoPing** [comment]
> Hi @LeeGuoPing, thank you for your contribution, can you sync the master branch? The logic of ShardingTokenGenerateBuilder may be changed.

@strongduanmu ok, I commited again

**Review by strongduanmu — CHANGES_REQUESTED** [review]
@LeeGuoPing There are some it error, can you check it?

**Comment by LeeGuoPing** [comment]
> @LeeGuoPing There are some it error, can you check it?

merge master to my own branch now

**Comment by strongduanmu** [comment]
> > @LeeGuoPing There are some it error, can you check it?
> 
> merge master to my own branch now

@LeeGuoPing Ok, let's wait the result.

**Review by strongduanmu — APPROVED** [review]
@LeeGuoPing Good job, thank you.

**Pull request merged**
