### PR TITLE
Add table rule in identifierKeywordsUnambiguous

### PR DESCRIPTION
**Pull request by zihaoAK47**
Refer #25535.

Changes proposed in this pull request:
  - EXECUTE ps1 USING @expected, @db, @table
  - Add table rule in identifierKeywordsUnambiguous

---

Before committing this PR, I'm sure that I have checked the following options:
- [  ✓] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [  ✓] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [  ✓] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [  ✓] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Comment by zihaoAK47** [comment]
@strongduanmu Please review thank :smirk:

**Review by strongduanmu — CHANGES_REQUESTED** [review]
@zihaoAK47 Can you test sql parser test case for this change?

**Comment by zihaoAK47** [comment]
@strongduanmu
 Hi mentor, I have added the test but this error occurred in CI
`
Error:  Failed to execute goal on project shardingsphere-test-e2e-sql: Could not resolve dependencies for project org.apache.shardingsphere:shardingsphere-test-e2e-sql:jar:5.3.3-SNAPSHOT: Could not find artifact org.apache.shardingsphere:shardingsphere-test-e2e-env:jar:tests:5.3.3-SNAPSHOT in apache.snapshots (https://repository.apache.org/snapshots) -> [Help 1]
`
The above error seems to be that the corresponding jar package was not found in the repository.
This error often appears in my submitted PR. Can you tell me how to solve it? Thank you.

**Comment by strongduanmu** [comment]
> @strongduanmu Hi mentor, I have added the test but this error occurred in CI `Error: Failed to execute goal on project shardingsphere-test-e2e-sql: Could not resolve dependencies for project org.apache.shardingsphere:shardingsphere-test-e2e-sql:jar:5.3.3-SNAPSHOT: Could not find artifact org.apache.shardingsphere:shardingsphere-test-e2e-env:jar:tests:5.3.3-SNAPSHOT in apache.snapshots (https://repository.apache.org/snapshots) -> [Help 1]` The above error seems to be that the corresponding jar package was not found in the repository. This error often appears in my submitted PR. Can you tell me how to solve it? Thank you.

I have triggered the ci, let's see the new result.

**Comment by zihaoAK47** [comment]
> > @strongduanmu Hi mentor, I have added the test but this error occurred in CI `Error: Failed to execute goal on project shardingsphere-test-e2e-sql: Could not resolve dependencies for project org.apache.shardingsphere:shardingsphere-test-e2e-sql:jar:5.3.3-SNAPSHOT: Could not find artifact org.apache.shardingsphere:shardingsphere-test-e2e-env:jar:tests:5.3.3-SNAPSHOT in apache.snapshots (https://repository.apache.org/snapshots) -> [Help 1]` The above error seems to be that the corresponding jar package was not found in the repository. This error often appears in my submitted PR. Can you tell me how to solve it? Thank you.
> 
> I have triggered the ci, let's see the new result.

Aha, everything has passed the inspection :blush:

**Review by strongduanmu — APPROVED** [review]
@zihaoAK47 Good job, merged.

**Pull request merged**
