### PR TITLE
18591 test case instance definition

### LINKED ISSUE #18591: Add test cases of InstanceMetaData

### PR DESCRIPTION
**Pull request by kvaithin**
Fixes #18591.

Changes proposed in this pull request:
Updated test cases for InstanceDefinition

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
The class InstanceDefinition is updated, could merge the new code and submit again?

**Comment by kvaithin** [comment]
Hi could we start the workflow on this pls. Thanks.

**Comment by kvaithin** [comment]
Seems like this class may no longer exist. Pls close PR if that's the case.

**Comment by terrymanu** [comment]
@kvaithin Hi, the class is renamed to InstanceMetaData, please go ahead if you want.

**Comment by terrymanu** [comment]
The test cases are completed. I just close the issue.

**Pull request closed without merging**
