### PR TITLE
Proofread SQLServer DENY statement

### PR DESCRIPTION
**Pull request by ThanoshanMV**
For #6478 

Changes proposed in this pull request:
- I've proofread the SQLServer [DENY](https://docs.microsoft.com/en-us/sql/t-sql/statements/deny-transact-sql?view=sql-server-ver15) statement.
- I've renamed the common rules to generic which belong to `GRANT`, `REVOKE`, and `DENY` statements and removed previous unnecessary rules.
- Although SQL case id `deny_execute_on_xml_schema_collection_to_user` doesn't belong to `objectPermission` due to ANTLR rule order, it matches with the `objectPermission`. Therefore, I had to expect the table in sql-case-id `deny_execute_on_xml_schema_collection_to_user` in the test case to successfully pass the all the test cases.

Please let me know if there is anything to improve.

### CODE REVIEW

**Review by strongduanmu — CHANGES_REQUESTED** [review]
Hi @ThanoshanMV, can you fix ci error first?

**Comment by ThanoshanMV** [comment]
Hi @strongduanmu, I checked locally, the build passed for the command `mvn clean install -Prelease`. I'm not sure where the error comes from.
 
shardingsphere-build-results

**Comment by strongduanmu** [comment]
> Hi @strongduanmu, I checked locally, the build passed for the command `mvn clean install -Prelease`. I'm not sure where the error comes from.
> 
> shardingsphere-build-results

@ThanoshanMV The ci error is not caused by this pr, it has been fixed in the master branch.

**Review by strongduanmu — APPROVED** [review]
@ThanoshanMV Good job, merged.

**Pull request merged**
