### PR TITLE
Added more unit tests for ContextManager (13758)

### LINKED ISSUE #13758: Add more unit tests for ContextManager
- [ ] addSchema
- [ ] deleteSchema
- [ ] addResource
- [ ] alterResource
- [ ] dropResource
- [ ] alterRuleConfiguration
- [ ] alterDataSourceConfiguration
- [ ] alterSchema
- [ ] alterGlobalRuleConfiguration
- [ ] alterProps
- [ ] reloadMetaData

### PR DESCRIPTION
**Pull request by shankeerthan-kasilingam**
Fixes #13758.

Changes done in this pull request:

- [x] addSchema
- [x] deleteSchema
- [x] addResource
- [x] alterResource
- [x] dropResource
- [x] alterRuleConfiguration
- [x] alterDataSourceConfiguration
- [x] alterSchema
- [x] alterGlobalRuleConfiguration
- [x] alterProps
- [x] reloadMetaData

### CODE REVIEW

**Comment by menghaoranss** [comment]
@shankeerthan-kasilingam there are conflicting files.

**Comment by shankeerthan-kasilingam** [comment]
> @shankeerthan-kasilingam there are conflicting files.

@menghaoranss  Thanks for checking. I have resolved the conflicts.

**Comment by menghaoranss** [comment]
@shankeerthan-kasilingam ci build failed.

**Comment by shankeerthan-kasilingam** [comment]
> @shankeerthan-kasilingam ci build failed.

I'll look into it.

**Comment by shankeerthan-kasilingam** [comment]
@menghaoranss I have fixed the CI failures. Could you please check the PR ?

**Comment by menghaoranss** [comment]
> @menghaoranss I have fixed the CI failures. Could you please check the PR ?

@shankeerthan-kasilingam I will review later

**Review by menghaoranss — APPROVED** [review]

**Pull request merged**
