### PR TITLE
Add new committer

### PR DESCRIPTION
**Pull request by Liangda-w**

### CODE REVIEW

**Review by menghaoranss — APPROVED** [review]

**Comment by menghaoranss** [comment]
congratulations

**Comment by tristaZero** [comment]
Hey @Liangda-w Congrats! You did a nice job. ;-) We announced this news to the community official mail list and will later Twitter.

**Comment by Liangda-w** [comment]
Thank you! @tristaZero 😄 Looking forward to the journey!

**Comment by tristaZero** [comment]
If you need any help, please be free to ping the team, Apache ShardingSphere committer. You're part of this community!
Thanks to his initiative, @ThanoshanMV joined OpenForce 2022 as the ShardingSphere mentor. If you want to take part in such activities or want to host some meetups and want some stuff, etc., just tell us. We are in the team and glad to provide any helps. ;-)
M V

**Comment by Liangda-w** [comment]
@tristaZero sounds great, pls let me know what I need to do to become an OpenForce mentor:)

**Comment by ThanoshanMV** [comment]
Hi @Liangda-w, you can join in [ShardingSphere Slack channel](https://join.slack.com/t/apacheshardingsphere/shared_invite/zt-sbdde7ie-SjDqo9~I4rYcR18bq0SYTg). There, we can take part in this programme.

**Comment by Liangda-w** [comment]
Thanks @ThanoshanMV, I joined the channel:)

**Comment by ThanoshanMV** [comment]
Hi @Liangda-w, I've added you to the `# openforce2022` channel.

**Comment by Liangda-w** [comment]
> Hi @Liangda-w, I've added you to the `# openforce2022` channel.

Great, thanks! I'll try my best to help 😄

**Pull request merged**
