### PR TITLE
ShardingSelectStatementValidator extracted

### PR DESCRIPTION
**Pull request by sluk3r**
for  #7531  Aim-1.

Changes proposed in this pull request:
- ShardingSelectStatementValidator added to contain validation logic that origines in ShardingRouteDecorator
- ShardingRouteDecoratorTest added

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
Please fix CI

**Comment by tristaZero** [comment]
Hi @sluk3r Friendly ping.

**Comment by sluk3r** [comment]
> Hi @sluk3r Friendly ping.

Hi

**Comment by tristaZero** [comment]
@sluk3r As this PR has remained CI failed for a long time, ICYMI, I brought it to your attention. Take it easy, follow your schedule to do it. :) 
BTW, If you need any help or have something blocked, I think @strongduanmu will provide helpful suggestions.

**Comment by terrymanu** [comment]
Will close soon if no update anymore

**Pull request closed without merging**
