### PR TITLE
fix IllegalStateException for 19449

### LINKED ISSUE #19449: IllegalStateException occurrd when excute DistSQL `SHOW DB_DISCOVERY RULES`
### Which version of ShardingSphere did you use?
master https://github.com/apache/shardingsphere/commit/23fae80b23ce1188b3d890a3e2b3aefc8ce36ad3

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
When there is no `DatabaseDiscoveryRule`, `SHOW DB_DISCOVERY RULES` should return empty result rest.

### Actual behavior
```sql
mysql> SHOW DB_DISCOVERY RULES;
ERROR 1997 (C1997): Runtime exception: [null]
```

#### Error log
```
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:492)
	at org.apache.shardingsphere.dbdiscovery.distsql.handler.query.DatabaseDiscoveryRuleQueryResultSet.init(DatabaseDiscoveryRuleQueryResultSet.java:70)
	at org.apache.shardingsphere.proxy.backend.text.distsql.rql.RQLBackendHandler.execute(RQLBackendHandler.java:51)
	at org.apache.shardingsphere.proxy.backend.text.distsql.rql.RQLBackendHandler.execute(RQLBackendHandler.java:40)
	at org.apache.shardingsphere.proxy.backend.text.DatabaseRequiredBackendHandler.execute(DatabaseRequiredBackendHandler.java:51)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:95)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:112)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Reason analyze (If you can)
There is no need to assert rule must exist in the init method:
```java
public void init(final ShardingSphereDatabase database, final SQLStatement sqlStatement) {
        Optional<DatabaseDiscoveryRule> rule = database.getRuleMetaData().findSingleRule(DatabaseDiscoveryRule.class);
        Preconditions.checkState(rule.isPresent());
        DatabaseDiscoveryRuleConfiguration ruleConfig = (DatabaseDiscoveryRuleConfiguration) rule.get().getConfiguration();
        dataSourceRules = ruleConfig.getDataSources().iterator();
        discoveryTypes = ruleConfig.getDiscoveryTypes();
        discoveryHeartbeats = ruleConfig.getDiscoveryHeartbeats();
        primaryDataSources = rule.get().getDataSourceRules().entrySet().stream().collect(Collectors.toMap(Entry::getKey, entry -> entry.getValue().getPrimaryDataSourceName(), (a, b) -> b));
    }
```

### PR DESCRIPTION
**Pull request by huangdx0726**
Fixes #19449 .

Changes proposed in this pull request:
-
 fix IllegalStateException occurrd when excute DistSQL SHOW DB_DISCOVERY RULES
-

### CODE REVIEW

**Comment by yx9o** [comment]
@huangdx0726 Hello, can you add unit tests for empty rules?

**Comment by huangdx0726** [comment]
ok



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 29, 2022 09:22 AM
To: ***@***.***&gt;;
Cc: "Da Xiang ***@***.******@***.***&gt;;
Subject: Re: [apache/shardingsphere] fix IllegalStateException for 19449 (PR#19610)




 
@huangdx0726 Hello, can you add unit tests for empty rules?

**Comment by RaigorJiang** [comment]
Hi @huangdx0726 
Thanks for the PR, but why change the order of imports?
The order you changed is incorrect, please follow the code conduct of ShardingSphere:
https://shardingsphere.apache.org/community/en/contribute/code-conduct/

If you use IDEA, please import settings, this will better keep the format correct.
\
image

**Comment by huangdx0726** [comment]
I‘v revert the order of imports

**Review by RaigorJiang — APPROVED** [review]

**Pull request merged**
