### PR TITLE
Support SQLServer trim function parse (#29162)

### LINKED ISSUE #29162: Support parsing SQL Server SELECT TRIM( sql
# Background
Hi community.
This issue is for #29149.

The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for `SQL Server` SQL parsing in ShardingSphere.

More details:
https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/

# Task
This issue is to support more `SQL Server` sql parsing, as follows:
```sql
SELECT TRIM( '.,! ' FROM '     #     test    .') AS Result
```
[link](https://learn.microsoft.com/zh-cn/sql/t-sql/functions/trim-transact-sql?view=sql-server-ver16)

```sql
SELECT TRIM(LEADING '.,! ' FROM  '     .#     test    .') AS Result
```
[link](https://learn.microsoft.com/zh-cn/sql/t-sql/functions/trim-transact-sql?view=sql-server-ver16)

```sql
SELECT TRIM(TRAILING '.,! ' FROM '     .#     test    .') AS Result
```
[link](https://learn.microsoft.com/zh-cn/sql/t-sql/functions/trim-transact-sql?view=sql-server-ver16)

```sql
SELECT TRIM(BOTH '123' FROM '123abc123') AS Result
```
[link](https://learn.microsoft.com/zh-cn/sql/t-sql/functions/trim-transact-sql?view=sql-server-ver16)

```sql
INSERT INTO [HR].[Employees]
        ([SSN]
        ,[FirstName]
        ,[LastName]
        ,[Salary])
    VALUES
        ('795-73-9838'
        , N'Catherine'
        , N'Abel'
        , $31692)
```
[link](https://learn.microsoft.com/zh-cn/azure/azure-sql/database/always-encrypted-enclaves-getting-started-vbs?view=azuresql)

# Process
1. First confirm that this is a correct `SQL Server` sql syntax, if not please leave a message under the issue and ignore it;
2. Compare SQL definitions in Official SQL Doc and ShardingSphere SQL Doc;
3. If there is any difference in ShardingSphere SQL Doc, please correct them by referring to the Official SQL Doc;
4. Run mvn install the current_file_module;
5. Check whether there are any exceptions. If indeed, please fix them. (Especially xxxVisitor.class);
6. Add new corresponding SQL case in SQL Cases and expected parsed result in Expected Statement XML;
7. Run SQLParserParameterizedTest to make sure no exceptions.

# Relevant Skills
1. Master JAVA language
2. Have a basic understanding of Antlr `g4` file
3. Be familiar with `SQL Server` SQLs

### PR DESCRIPTION
**Pull request by venkatdatta0**
Fixes #29162 

Changes proposed in this pull request:
  - Support TRIM function for SQL Server

Cases:
```
SELECT TRIM( '.,! ' FROM '     #     test    .') AS Result
```
```
SELECT TRIM(LEADING '.,! ' FROM  '     .#     test    .') AS Result
```
```
SELECT TRIM(TRAILING '.,! ' FROM '     .#     test    .') AS Result
```
```
SELECT TRIM(BOTH '123' FROM '123abc123') AS Result
```

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [x] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Comment by strongduanmu** [comment]
Hi @venkatdatta0, can you fix error first?

**Comment by venkatdatta0** [comment]
> Hi @venkatdatta0, can you fix error first?

I have fixed the build errors. Please approve the workflows

**Comment by strongduanmu** [comment]
> > Hi @venkatdatta0, can you fix error first?
> 
> I have fixed the build errors. Please approve the workflows

Hi @venkatdatta0 It seems that there are still problems with the code format check, please execute the commands in E2E and fix them.

**Comment by strongduanmu** [comment]
Hi @venkatdatta0, can you solve code conflict?

**Comment by strongduanmu** [comment]
Hi @venkatdatta0, can you take a look?

**Comment by strongduanmu** [comment]
Since this pr has long time no response, I will close it. You can submit new pr when you are free.

**Pull request closed without merging**
