### PR TITLE
Test Calcite doing query between two sharding tables.

### PR DESCRIPTION
**Pull request by lmhmhl**
Ref #9528

### CODE REVIEW

**Review by tristaZero — CHANGES_REQUESTED** [review]
Hi Please look at the CI tests.

**Comment by lmhmhl** [comment]
Hi @tristaZero, When I ran the test, some error happened like follows:
I test every single test method, It was all good, but if I run the all the method of the class, this error happen.
```
java.lang.RuntimeException: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.""t_order_calcite_sharding_0""(""order_id_sharding"")"; SQL statement:


INSERT INTO t_order_calcite_sharding_0 VALUES(1000, 10, 'init') [23505-196]

	at org.apache.shardingsphere.driver.jdbc.base.AbstractShardingSphereDataSourceForCalciteTest.initTable(AbstractShardingSphereDataSourceForCalciteTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.""t_order_calcite_sharding_0""(""order_id_sharding"")"; SQL statement:


INSERT INTO t_order_calcite_sharding_0 VALUES(1000, 10, 'init') [23505-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.mvstore.db.MVPrimaryIndex.add(MVPrimaryIndex.java:139)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:705)
	at org.h2.command.dml.Insert.insertRows(Insert.java:156)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:260)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:192)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:164)
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:290)
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:290)
	at org.h2.tools.RunScript.execute(RunScript.java:171)
	at org.apache.shardingsphere.driver.jdbc.base.AbstractShardingSphereDataSourceForCalciteTest.initTable(AbstractShardingSphereDataSourceForCalciteTest.java:69)
	... 24 more
```

**Comment by tristaZero** [comment]
> I test every single test method, It was all good, but if I run the all the method of the class, this error happen.

Hi @lmhmhl ,

If this exception arise when all unit tests run together, it is more likely that some UTs are affected by others. 

> java.lang.RuntimeException: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.""t_order_calcite_sharding_0""(""order_id_sharding"")"; SQL statement:
INSERT INTO t_order_calcite_sharding_0 VALUES(1000, 10, 'init') [23505-196]

Especially, you tried to insert same primary keys I guess.

**Comment by lmhmhl** [comment]
Hi @tristaZero ,the thing is that because of primary key violation, then I delete the primary key of a sharding table, my sql
statement is ` select o.order_id_sharding, i.order_id from t_order_calcite_sharding o, t_order_item_calcite_sharding i where o.order_id_sharding = i.item_id;` where `order_id_sharding` is the primary key before, the weird thing is there are a lot of repeated record like  follows



```
CREATE TABLE IF NOT EXISTS t_order_calcite_sharding_0 (order_id_sharding INT NOT NULL, user_id INT NOT NULL, status VARCHAR(45) NULL);
CREATE TABLE IF NOT EXISTS t_order_calcite_sharding_1 (order_id_sharding INT NOT NULL, user_id INT NOT NULL, status VARCHAR(45) NULL);
```
```
CREATE TABLE IF NOT EXISTS t_order_item_calcite_sharding_0 (item_id INT NOT NULL, order_id INT NOT NULL, user_id INT NOT NULL, status VARCHAR(45) NULL, remarks VARCHAR(45) NULL, PRIMARY KEY (item_id));
CREATE TABLE IF NOT EXISTS t_order_item_calcite_sharding_1 (item_id INT NOT NULL, order_id INT NOT NULL, user_id INT NOT NULL, status VARCHAR(45) NULL, remarks VARCHAR(45) NULL, PRIMARY KEY (item_id));
```
```
INSERT INTO t_order_calcite_sharding_0 VALUES(1010, 10, 'init');
INSERT INTO t_order_calcite_sharding_1 VALUES(1011, 11, 'init');
INSERT INTO t_order_calcite_sharding_0 VALUES(1100, 10, 'init');
INSERT INTO t_order_calcite_sharding_1 VALUES(1101, 11, 'init');
```
```
INSERT INTO t_order_item_calcite_sharding_0 VALUES(1000, 10000, 10, 'init', 't_order_item_calcite_sharding');
INSERT INTO t_order_item_calcite_sharding_1 VALUES(1001, 10001, 11, 'init', 't_order_item_calcite_sharding');
INSERT INTO t_order_item_calcite_sharding_0 VALUES(1010, 10001, 10, 'init', 't_order_item_calcite_sharding');
INSERT INTO t_order_item_calcite_sharding_1 VALUES(1011, 10001, 10, 'init', 't_order_item_calcite_sharding');

```

**Comment by lmhmhl** [comment]
Screen Shot 2021-03-03 at 2 07 58 PM

**Comment by lmhmhl** [comment]
Screen Shot 2021-03-03 at 2 07 58 PM

**Comment by tristaZero** [comment]
Hi @lmhmhl 

> before, the weird thing is there are a lot of repeated record like follows

Does it due to our configuration and initialized SQL files?

Why did you modify `SELECT_SQL_BY_ID_ACROSS_TWO_SHARDING_TABLES `with `=` condition? Do you think `>` can not work well?

**Comment by tristaZero** [comment]
Hi @lmhmhl ?

**Comment by lmhmhl** [comment]
> Hi @lmhmhl ?

I will solve this today.

**Comment by lmhmhl** [comment]
@tristaZero ,I checked many times, all the sql statements are SELECT, and the initial value are unique, when I use primary key in sharding table, `Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.""t_order_calcite_sharding_0""(""order_id_sharding"")` are as still, but I didn't insert duplicate value of `order_id_sharding` column, and when I run single test method are ok, but when all tests method run together, this problem happens, and every single test method are INSERT type, It seems like doesn't produce duplicate value of `t_order_calcite_sharding_0`. So I don't know how does this happened. Can you help me?

**Comment by tristaZero** [comment]
Hi @lmhmhl ,

Sorry for my coming late.

> INSERT INTO t_order_calcite_sharding_0 

It looks strange, the initialized SQL does define primary key, doesn't it?

> CREATE TABLE IF NOT EXISTS t_order_calcite_sharding_0 (order_id_sharding INT NOT NULL, user_id INT NOT NULL, status VARCHAR(45) NULL);

**Comment by tristaZero** [comment]
Here my two suggestion,

1. Please provide complete log info for us to locate the cause.
2. Did that exception happen when you prepare env or run the unit tests? Could you check the existing rows in the databases by `ShardingSpherePreparedStatement.getShardingSphereConnection().getDataSources()`?

**Comment by tristaZero** [comment]
Hi @lmhmhl , does anything go well?

**Comment by lmhmhl** [comment]
@tristaZero ,I am so sorry that I reply u late, recently, I am a little bit overwhelmed by all kinds of stuff, I hope u can understand me. As the same, It still doesn't work when I ran all the test method together, but if I run test method one by one, It's PERFECT. 
```
java.lang.RuntimeException: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.""t_order_calcite_sharding_0""(""order_id_sharding"")"; SQL statement:


INSERT INTO t_order_calcite_sharding_0 VALUES(1010, 10, 'init') [23505-196]

	at org.apache.shardingsphere.driver.jdbc.base.AbstractShardingSphereDataSourceForCalciteTest.initTable(AbstractShardingSphereDataSourceForCalciteTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.""t_order_calcite_sharding_0""(""order_id_sharding"")"; SQL statement:


INSERT INTO t_order_calcite_sharding_0 VALUES(1010, 10, 'init') [23505-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.mvstore.db.MVPrimaryIndex.add(MVPrimaryIndex.java:139)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:705)
	at org.h2.command.dml.Insert.insertRows(Insert.java:156)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:260)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:192)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:164)
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:290)
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:290)
	at org.h2.tools.RunScript.execute(RunScript.java:171)
	at org.apache.shardingsphere.driver.jdbc.base.AbstractShardingSphereDataSourceForCalciteTest.initTable(AbstractShardingSphereDataSourceForCalciteTest.java:69)
	... 24 more

```

**Comment by tristaZero** [comment]
@lmhmhl 
Take it easy. :-)
Please take care of your issues first, and let us leave this PR some time to review later.

Once you have time and want to go ahead or have any updates, just ping me here.

**Comment by lmhmhl** [comment]
Hi @tristaZero,
I check the sql file carefully, and found that I forget to DELETE the table when every single test execute initTable method. 
I am so sorry that I took such a long time on this issue and I appreciate that you still trust me.
```
DELETE FROM t_order_calcite_sharding_0;
DELETE FROM t_order_calcite_sharding_1;
```

**Comment by tristaZero** [comment]
So there will be some progress, aren't there?

**Comment by lmhmhl** [comment]
> So there will be some progress, aren't there?

Yes, The problem has been solved. It my mistake. Sorry to that.

**Comment by tristaZero** [comment]
But this CI still failed.

**Review by Baoanh217 — COMMENTED** [review]
@[]()

**Pull request closed without merging**
