### PR TITLE
improve the RDL documentation related to Drop Sharding Table Rule

### PR DESCRIPTION
**Pull request by Swastyy**
For task 1 of #19898 

- Hey @JiekerTime , let me know if we want to do it this way, or I have interpreted wrong then reply here. Thanks

### CODE REVIEW

**Review by RaigorJiang — CHANGES_REQUESTED** [review]
Hi @Swastyy
Nice to see you!

I saw your PR and found that the task may not be clearly described:
1. Refer to the DistSQL document in refactoring, there are some changes in the syntax format, such as [CREATE SHARDING TABLE RULE](https://shardingsphere.apache.org/document/current/en/reference/distsql/syntax/rdl/rule-definition/sharding/create-sharding-table-rule/);

2. The new syntax uses EBNF notation, which can be easily converted to railroad diagrams, like this:
image



3. You can go to https://www.bottlecaps.de/rr/ui to experience the edited grammar and see diagrams;

4. In the future, the front end will be adapted to display the EBNF content as a railway diagrams.

Hope the above information is helpful to you.

**Comment by Swastyy** [comment]
Hey @RaigorJiang , I get your point but can you tell me what URL did you used in https://www.bottlecaps.de/rr/ui to see the railroad diagram of Create Sharding Table Rule? Thanks.

**Comment by RaigorJiang** [comment]
> Hey @RaigorJiang , I get your point but can you tell me what URL did you used in https://www.bottlecaps.de/rr/ui to see the railroad diagram of Create Sharding Table Rule? Thanks.

Copy the EBNF of the grammar to the `Edit Grammar` tab, then switch to `View Diagram` to see the graph
image

**Comment by RaigorJiang** [comment]
Hi @Swastyy 
Since this PR has been inactive for long time, I just close it, please submit a new PR next time.

**Pull request closed without merging**
