### PR TITLE
Fixed Typo in Images

### LINKED ISSUE #11356: Typo on proxy_architecture images
The image has an Typing Error. It should be 'database cluster' instead of ''database cluser'' Also the red error lines needs to be removed.

image

### PR DESCRIPTION
**Pull request by ManasviGoyal**
**Fixes #11356**

- Removed Red Error Lines
- Changed 'Cluser' to 'Cluster'
- Changed Sharding-Proxy to ShardingSphere-Proxy
- Maintained the size and dimensions

**Previous images**
image
image
image
image

**Fixed images**
image
image
image
image

### CODE REVIEW

**Comment by ManasviGoyal** [comment]
This is my first PR so please tell me If there is anything I could improve. Really Hope it gets merged.

Do provide Feedback as it will help me improve.

**Comment by strongduanmu** [comment]
@ManasviGoyal Thank you very much for your PR, `ShardingSphere-Proxy` is better.

**Comment by ManasviGoyal** [comment]
> @ManasviGoyal Thank you very much for your PR, `ShardingSphere-Proxy` is better.

Thank you for your comment. Have are done everything correctly? How will I know if my changes are approved and merged?

**Comment by RaigorJiang** [comment]
@ManasviGoyal   LGTM, but the length and width of the picture have changed. Does this affect the display of the webpage?

**Review by strongduanmu — COMMENTED** [review]
@ManasviGoyal The `Sharding-Proxy` in the picture needs to be changed to `ShardingSphere-Proxy`.

**Comment by ManasviGoyal** [comment]
> @ManasviGoyal The `Sharding-Proxy` in the picture needs to be changed to `ShardingSphere-Proxy`.

the original pictures had `Sharding-Proxy` thats why i added that. In which Proxy architecture? 1 or 2 or both?

**Comment by ManasviGoyal** [comment]
> @ManasviGoyal LGTM, but the length and width of the picture have changed. Does this affect the display of the webpage?

should I restore to the original dimensions?

**Comment by RaigorJiang** [comment]
If possible, it’s better not to change the size.

**Comment by ManasviGoyal** [comment]
> If possible, it’s better not to change the size.

@RaigorJiang sure. do i need to make another pull request ? if not how to make changes to this one?
also  should i keep it as Sharding-Proxy or ShardingSphere-Proxy? @strongduanmu

**Comment by RaigorJiang** [comment]
Hi @ManasviGoyal 
Sorry for the late reply. I checked the style of the page. The maximum rendering size of the image is 800px, so you can adjust the size as long as you keep the proportions.

As @strongduanmu  said,  The `Sharding-Proxy` in the picture needs to be changed to `ShardingSphere-Proxy`.  
Thank you!  

By the way, there is no need to open new PR, you only need to commit again.

**Comment by ManasviGoyal** [comment]
@RaigorJiang Thank you so much for your feedback. Will make the required changes and commit again.

**Comment by ManasviGoyal** [comment]
made the required changes please check @RaigorJiang  @strongduanmu

**Comment by RaigorJiang** [comment]
@ManasviGoyal  It is perfect, thanks for your contribution.

**Review by strongduanmu — APPROVED** [review]

**Pull request merged**
