### PR TITLE
Remove useless worker-id props in snowflake

### PR DESCRIPTION
**Pull request by strongduanmu**
Changes proposed in this pull request:
- Remove useless worker-id props in snowflake

### CODE REVIEW

**Comment by totalo** [comment]
I think maybe we have to support workid setting, if we want to set workid how should we set it?

**Comment by strongduanmu** [comment]
> 

@totalo The shown setting workerId will cause problems in Cluster mode, so the snowflake algorithm has built-in workerId generation logic now.

**Comment by totalo** [comment]
> 

Get it,thx~

**Comment by totalo** [comment]
> > 
> 
> @totalo The shown setting workerId will cause problems in Cluster mode, so the snowflake algorithm has built-in workerId generation logic now.

Get it,thx~

**Review by totalo — APPROVED** [review]

**Pull request merged**
