### PR TITLE
Add unit test for shardingsphere-encrypt (Issue#10964)

### PR DESCRIPTION
**Pull request by Franco-H**
Fixes #ISSUSE_10964.

Issue was assigned to another contributor on Jul 15, 2021, but it is still in progress as of today. Since I have already completed the issue for the school project, I still want to make a PR. The code maintainers could reject my PR if the PR has to be made by the assigned contributor.

### CODE REVIEW

**Comment by menghaoranss** [comment]
@Franco-H ci build failed.

**Comment by Franco-H** [comment]
> 

Im fixing it. will update soon

**Comment by Franco-H** [comment]
Accidentally closed the branch. Just reopened it

**Comment by Franco-H** [comment]
Strange. It says "NewlineAtEndOfFile: File does not end with a newline". Is that an issue with the checkstyle configuration? Or is it the problem of my code?

**Comment by Franco-H** [comment]
Strange. It says "NewlineAtEndOfFile: File does not end with a newline". Is that an issue with the checkstyle configuration? Or is it the problem of my code?

**Comment by Franco-H** [comment]
Need to re-run it again. The build before the last build only had a checkstyle error (add line). I fixed it and the project built successfully at my end. However, there were two new issues in the last built from the VM and these issues never happen at my end.

**Comment by Franco-H** [comment]
@menghaoranss  Looks like there are more issues found now but I did not touch my code at all except adding a new empty line to pass the checkstyle violation. Does this have something to do with new merge in the last couple days?

**Comment by menghaoranss** [comment]
> @menghaoranss Looks like there are more issues found now but I did not touch my code at all except adding a new empty line to pass the checkstyle violation. Does this have something to do with new merge in the last couple days?

@Franco-H Ci must be triggered manually when you commit a PR for the first time, this PR build failed now, please check again, and you modified 19 files altogether, I suggest you split these files into multiple PRs to help them be reviewed more easily.

**Comment by terrymanu** [comment]
Hello, any update?

**Comment by RaigorJiang** [comment]
Since this PR has been inactive for more than 30 days, I just close it. 
If you wish to continue contributing, please fix the conflicting files and reopen it, thank you!

**Pull request closed without merging**
