### PR TITLE
proofread SQLServer TCL statements

### PR DESCRIPTION
**Pull request by ThanoshanMV**
For #6478

Hi @jingshanglu, I've added SQL definitions for SQLServer [TCL](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/transactions-transact-sql?view=sql-server-ver15) statements. Please check it.

Changes proposed in this pull request:
- Proofread SQLServer TCL statements.
- Add corresponding test cases.

### CODE REVIEW

**Comment by ThanoshanMV** [comment]
Which case do we need to follow for `sql-case-id`? Currently, `sql-case-id`s are specified in both camel case and snake case.

**Review by terrymanu — APPROVED** [review]

**Review by terrymanu — APPROVED** [review]

**Comment by terrymanu** [comment]
> Which case do we need to follow for `sql-case-id`? Currently, `sql-case-id`s are specified in both camel case and snake case.

Thank you for remind. 
It is better to use `snake-case`. Please submit a new pull request to unify the `sql-case-id` if you are interested.
Thanks again.

**Comment by terrymanu** [comment]
I just create the issue #12830 for it

**Comment by ThanoshanMV** [comment]
> > Which case do we need to follow for `sql-case-id`? Currently, `sql-case-id`s are specified in both camel case and snake case.
> 
> Thank you for remind. It is better to use `snake-case`. Please submit a new pull request to unify the `sql-case-id` if you are interested. Thanks again.

Thank you. I'll try to unify all `sql-case-id` in `snake-case`.

**Pull request merged**
