### PR TITLE
Support the fuzzy query of encrypted fields

### LINKED ISSUE #20435: How to support the fuzzy query of encrypted fields
Solutions: @strongduanmu 

1. Homomorphism algorithm, but there is no good homomorphic encryption algorithm implemented for now.
2. Besides the cipherColumn and assistedQueryColumn columns, add additional fuzzyColumn and fuzzyAlgorithm which works like  the cipherColumn and assistedQueryColumn columns, rewrite `LIKE plainColumn` into `LIKE fuzzyColumn` to meet user requirements. The `API` changed as below:
```
public final class EncryptColumnRuleConfiguration {
    
    private final String logicColumn;
    
    private final String cipherColumn;
    
    private final String assistedQueryColumn;
    
    private final String plainColumn;
    
    private final String encryptorName;
    
    private final String assistedQueryEncryptorName;
    
    private final Boolean queryWithCipherColumn;

    // new added
    private final String fuzzyQueryColumn;

    // new added
    private final String fuzzyQueryEncryptorName;
 
```

Any other ideas?

Related: #19026

### PR DESCRIPTION
**Pull request by gxxiong**
Fixes #20435.

Changes proposed in this pull request:
  -Support the fuzzy query of encrypted fields
  -Add the fuzzyQueryColumn and fuzzyQueryEncryptorName
  -Provider fuzzy query algorithm, FuzzyChineseEncryptAlgorithm

---

Before committing this PR, I'm sure that I have checked the following options:
- [X] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [X] I have self-reviewed the commit code.
- [X] I have passed maven check: `mvn clean install -B -T2C -DskipTests -Dmaven.javadoc.skip=true -e`.
- [ ] I have made corresponding changes to the documentation.
- [X] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Comment by cheese8** [comment]
Thanks for your pr,  but it's too big, could you split it into pieces? refer to the subtasks in #20435

**Comment by cheese8** [comment]
> Thanks for your pr, but it's too big, could you split it into pieces? refer to the subtasks in #20435

Sorry, I means split it into 5 or 6 prs ? And could your provide your wchat code that I invite you into the kernel group.

**Comment by gxxiong** [comment]
my wechat id:xionggaoxiang

**Review by terrymanu — CHANGES_REQUESTED** [review]
This PR is too big, we need the design document first.

**Comment by gxxiong** [comment]
@terrymanu #20435 Design Reference assistedQueryColumn, just rewrite LIKE plainColumn into LIKE fuzzyColumn.Then,this pr is to big,I will split the pr into several parts。Now close this pr

**Pull request closed without merging**
