### PR TITLE
introduce flatten_maven_plugin to revision version

### PR DESCRIPTION
**Pull request by lovepoem**
introduce flatten_maven_plugin to revision version

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
Please check github action

**Comment by lovepoem** [comment]
image
```perilog
 [INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.188 s
[INFO] Finished at: 2020-10-30T10:09:54+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project config-utility: Could not resolve dependencies for project org.apache.shardingsphere.example:config-utility:jar:5.0.0-RC1-SNAPSHOT: Failed to collect dependencies at org.apache.shardingsphere:shardingsphere-sharding-api:jar:5.0.0-RC1-SNAPSHOT: Failed to read artifact descriptor for org.apache.shardingsphere:shardingsphere-sharding-api:jar:5.0.0-RC1-SNAPSHOT: Failure to find org.apache.shardingsphere:shardingsphere-sharding:pom:${revision} in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :config-utility
```

Now the examples project failed

**Comment by kimmking** [comment]
ci has not passed.

**Comment by lovepoem** [comment]
> ci has not passed.

@kimmking @tristaZero   

In examples project, it faild 

```
Failed to execute goal on project config-utility: Could not resolve dependencies for project org.apache.shardingsphere.example:config-utility:jar:5.0.0-RC1-SNAPSHOT: Failed to collect dependencies at org.apache.shardingsphere:shardingsphere-sharding-api:jar:5.0.0-RC1-SNAPSHOT: Failed to read artifact descriptor for org.apache.shardingsphere:shardingsphere-sharding-api:jar:5.0.0-RC1-SNAPSHOT: Failure to find org.apache.shardingsphere:shardingsphere-sharding:pom:${revision} in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

```

`5.0.0-RC1-SNAPSHOT` cannot be found here"
https://repository.apache.org/content/repositories/snapshots/org/apache/shardingsphere/  

Do we need to release a `5.0.0-RC1-SNAPSHOT` version of the main repository?

**Comment by tristaZero** [comment]
@lovepoem Hi `5.0.0-alpha` is expected for the next incoming release. Currently, we are in the middle of the release from the master branch. Accordingly, you can see we have changed the `<version>` to `5.0.0-alpha` in [example pom](https://github.com/apache/shardingsphere/blob/master/examples/pom.xml)

**Review by terrymanu — CHANGES_REQUESTED** [review]
The build of github action is failed

**Comment by lovepoem** [comment]
> The build of github action is failed
On the master branch , when I run ` mvn clean install -DskipTests=true`
It throws Exception 
```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.777 s
[INFO] Finished at: 2020-11-18T10:55:37+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project config-utility: Could not resolve dependencies for project org.apache.shardingsphere.example:config-utility:jar:5.0.0-alpha: Failed to collect dependencies at org.apache.shardingsphere:shardingsphere-sharding-api:jar:5.0.0-RC1-SNAPSHOT: Failed to read artifact descriptor for org.apache.shardingsphere:shardingsphere-sharding-api:jar:5.0.0-RC1-SNAPSHOT: Failure to find org.apache.shardingsphere:shardingsphere-sharding:pom:${revision} in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :config-utility


```

Do you have the same issue ?  Shall resolve it at first ?

**Comment by tristaZero** [comment]
So @lovepoem @terrymanu we closed this one? as this PR stays unchanged for a long time.

**Comment by lovepoem** [comment]
> So @lovepoem @terrymanu we closed this one? as this PR stays unchanged for a long time.

@tristaZero Ok ， you can close it now , I will try it again some day

**Pull request closed without merging**
