### PR TITLE
Update ComplexInlineShardingAlgorithm.java

### PR DESCRIPTION
**Pull request by xjt520**
Fix `table not exists` when query with `in`

### CODE REVIEW

**Comment by RaigorJiang** [comment]
Hi @xjt520 , 
**For English only**, other languages will not accept.

**Review by strongduanmu — CHANGES_REQUESTED** [review]
Hi @xjt520, thank you for your contribution. Can you add some unit test for this change?

**Comment by xjt520** [comment]
Hi, why Merging is blocked ，what can I do for this code.

**Comment by RaigorJiang** [comment]
> Hi, why Merging is blocked ，what can I do for this code.

@xjt520 Looks like some unit tests need to be added.

**Comment by TeslaCN** [comment]
Hi @xjt520 
Any update here?

**Comment by strongduanmu** [comment]
Since this pr has long time no response, I will close it now.

**Pull request closed without merging**
