### PR TITLE
Routing failure when solving left join associated query. Change hashset to linkedHashSet

### PR DESCRIPTION
**Pull request by lmandy**
I have changed the Hashset to LinkedHashSet, This mysql #25170

### CODE REVIEW

**Comment by lmandy** [comment]
CI failed, as fllows
image
Please deal with this pr

**Comment by strongduanmu** [comment]
Hi @lmandy, thank you for your contribution. Can you add unit test for this logic?

**Comment by lmandy** [comment]
Ok, which module should I add? Is there an example for reference?

**Comment by terrymanu** [comment]
Close because of staled.

**Pull request closed without merging**
