### PR TITLE
Add space between english and chinese words

### LINKED ISSUE #15843: [OpenForce 2022] Optimize official documents
Hi community,

This issue is for [OpenForce](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Aim

Check the source file below, keep a space between Chinese and English words

Source file:
https://github.com/apache/shardingsphere/blob/master/docs/community/content/contribute/code-conduct.cn.md

Official document link:
https://shardingsphere.apache.org/community/cn/contribute/code-conduct/

### Example

`您可以报告bug，提交一个新的功能增强建议或者直接对以上内容提交改进补丁。`

After optimization：

`您可以报告 bug，提交一个新的功能增强建议或者直接对以上内容提交改进补丁。`

### PR DESCRIPTION
**Pull request by developer-diganta**
Fixes #15843.

Changes proposed in this pull request:
-Added space between English and Chinese words.
image

### CODE REVIEW

**Comment by Swastyy** [comment]
Hi @developer-diganta , there are so many files edited, and also resolve the conflicts.

**Comment by developer-diganta** [comment]
I think someone has already worked on this issue.... Shall I close the pr?

**Comment by menghaoranss** [comment]
@developer-diganta sorry, the issue has been fixed, could you try another one?

**Comment by menghaoranss** [comment]
> I think someone has already worked on this issue.... Shall I close the pr?

@developer-diganta sure, you can pick another one.

**Comment by menghaoranss** [comment]
Closed because it was resolved

**Pull request closed without merging**
