### PR TITLE
Federated SQL query and Query optimization 

### LINKED ISSUE #8284: [New feature] Federated SQL query and Query optimization are going to sail out.
Hi  community,

As you know, ShardingSphere has made a lot of efforts on SQL  parser and **provided a great independent SQL parser** to help users parse SQL.

Based on this substantial work, we **plan to do query optimization** to optimize the input SQLs from users and produce an optimized SQL query plan to improve query efficiency. Plus, **the federated SQL query feature** (Like join query from different instances)  is another essential highlight for our next release. : )

We will leverage [Apache Calcite](https://calcite.apache.org), an excellent framework to implement two of the features.  Currently, three main work focus are presented here. 
- [x] The investigation of **RBO** (Rule-Based Optimization) and **CBO**  (Cost-Based optimization) ,i.e.,  Hep planner engine and Volcano planner engine.   (**Mechanism, usage, pros and cons**).
- [x] The investigation of Calcite adaptor, especially `TranslatableTable` API.
- [x] How to transform the parsed result of ShardingSphere to the algebra of Calcite
- [x] Call some of the optimization rules to process the relational expression
- [x] Implement Calcite adaptor to join SQLs from different instances
- [x] Combine sharding tables with Calcite adaptors.

Actually, there are plenty of works to do on this issue. We are **in the investigation phase** now and will seek contributors for this issue later. If you are interested in this one, please give it a watch. 😉 

---
### 10th January 2021 Task Update

Hi, community,

Here is the progress update so far.

### Functions

- [x] The **research** on the source code and API of Apache Calcite
- [x] The **design plan** on Apache ShardingSphere and  Apache Calcite
- [x] The implementation of `CalciteLogicSchemaFactory`, `CalciteLogicSchema`, and `CalciteFilterableTable`
- [x] The Calcite JDBC executor
- [x] The **work embedding with** initialization, router, and executor with ShardingSphere
- [ ] Use ShardingSphere **parser** instead of the Calcite parser to parse SQL (SqlNodeConverter, @guimingyue)  (Q2)
- [ ] Custom **planner** for SQL Optimization(PlannerInitializer, @guimingyue )  (Q2)
- [ ] SQL Optimization for `CalciteFilterableTable` (CalciteExecutionSQLGenerator)  (Q2)
- [ ] The implement for `CalciteRawExecutor` (Especially `ResultSetMetadata`)  (Q2)
- [ ] The **SQLRouter** of ShardingSphere to route SQL to `CalciteExecutor`  (Q2)

### Unit test (Q2)
- [x] CalciteContextFactory
- [x] CalciteLogicSchemaFactory(Doing, #8965)
- [x] CalciteJDBCExecutor(Doing, #8883)
- [ ] CalciteRawExecutor(TODO)
- [ ] CalciteExecutionSQLGenerator(TODO)
- [x] CalciteExecutionContextGenerator

### SQL Federation
- [x] Binding tables (Native)
- [x] Single table and Broadcast table  (Native)
- [x] Sharding table and Broadcast table  (Native)
- [x] Broadcast table and Broadcast table  (Native)
- [x] Single table and Single table + UT
- [x] Single table and Sharding table  + UT(Q2)
- [x] Sharding table and Sharding table  + UT (Q2)

### Scenario
- [x] Sharding
- [ ] Sharding + ReplicaQuery  (Q2)
- [ ] Sharding + Encryption  (Q2)
- [x] Sharding + Encryption + ReplicaQuery  (Q2)

### PR DESCRIPTION
**Pull request by guimingyue**
Fixes #8284.

Changes proposed in this pull request:
- add calcite as optimization framework for sql optimization, `org.apache.shardingsphere.infra.optimize.planner.Compiler` is the entrance of sql optimization.
- add optimization rules based on calcite heuristic and volcano optimization planner, theses rule files are packaged in `org.apache.shardingsphere.infra.optimize.planner.rule` , `shardingsphere-infra-optimize` module.
- add a volcano executor framework and some implementation classes to execute the physical plan, which is in `shardingsphere-infra-executor` module. 
- add an evaluator framework for the execution of expressions and functions in distribution sql layer, this is just in the beginning phase.
- other changes include SQL AST converter, meta data converter and so on.

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
Sorry, the PR is so big, I think nobody can review it, could you split them to smaller PRs?

**Comment by guimingyue** [comment]
> Sorry, the PR is so big, I think nobody can review it, could you split them to smaller PRs?

Hi, @terrymanu , sorry for the late reply. In my perspective, this PR is regraded as a whole of federated SQL query. Most of the classes of this PR are newly added. Let me try to explain the PR in detail.

This PR can be divided into three parts, `shardingsphere-infra-optimize` module, `shardingsphere-infra-executor` module and the glue code(mainly in shardingsphere-jdbc-core module) which is responsible for connecting the `shardingsphere-infra-optimize` and `shardingsphere-infra-executor`.

0. The `shardingsphere-infra-optimize` module is a new module, and is based on Apache Calcite framework. It contains the converter of converting ShardingSphere ast to Calcite ast, or `SqlNode` in Calcite world, and the Converter of converting `SqlNode` to `RelNode` of Calcite. The most important part of this module is the optimizer based on Calcite Planner framework, containing planner rules, logical RelNode and physical RelNode, please refer to `DefaultPlanner` for this process. `org.apache.shardingsphere.infra.optimize.planner.Compiler#compileQuery` this method is the entrance of converting ast and optimizing relnode, and this method alse return the physical RelNode to execute in `shardingsphere-infra-executor` module.
1. The `shardingsphere-infra-executor` module is an existing module. But there is a new package `exec`, in this package, the main part is `Executor`s，and they are the implementation of phycical RelNode. For example the NestedLoopJoinExecutor is the implemantation of physical RelNode SSNestedLoopJoin. Some Executors need to execute function to filter or aggregate rows, so that's what `BuiltinFunction` does. When building Executor instance,  `BuiltinFunction` may be created and passed to `Executor` instance, for example, `org.apache.shardingsphere.infra.executor.exec.CalcExecutor#build` create `BuiltinFunction` for filter operator to filter rows. 
2. Besides the optimizer and executor, some glue code is added to implementation a whole query process. In `ShardingSphereStatement`, there is a new method `org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement#executeSql` to execute SQL with optimizer and executor, this method is enabled by a preperty `federated-sql-query-optimization` in `org.apache.shardingsphere.infra.config.properties.ConfigurationPropertyKey`. In the same module, a new class `SSResultSet` is also newly added for retrieving `Row` from `Executor` in  `shardingsphere-infra-executor` module.

I alse deleted previous calcite related method and testcase, because most of them have nothing to do with federated SQL query.

**Comment by zhujunxxxxx** [comment]
Unbelievable. This is the biggest PR I've ever worked on for so long. Any committer of the person in charge will reject it. I suggest you split it up. If you can't spilt it, there's something wrong with your design

**Comment by guimingyue** [comment]
> Unbelievable. This is the biggest PR I've ever worked on for so long. Any committer of the person in charge will reject it. I suggest you split it up. If you can't spilt it, there's something wrong with your design

@terrymanu @zhujunxxxxx Thanks for your suggestions. I will split this PR into three parts as I mentioned above during the incoming holiday. Do you have any other suggestions?

**Pull request closed without merging**
