### PR TITLE
Fix: The cache is not updated after DistSQL modifies props in non-cluster mode

### PR DESCRIPTION
**Pull request by lanchengx**
Fixes https://github.com/apache/shardingsphere/issues/17444.

Changes proposed in this pull request:
- Add `TypedProperties#reload()` to update `cache`

### CODE REVIEW

**Review by RaigorJiang — DISMISSED** [review]

**Review by terrymanu — CHANGES_REQUESTED** [review]
Is the PROXY_FRONTEND_FLUSH_THRESHOLD can be changed dynamically without restart proxy?

**Comment by terrymanu** [comment]
How about create new instance when TypedProperties refresh?

**Comment by lanchengx** [comment]
> How about create new instance when TypedProperties refresh?

Update `props` by creating new `MetaDataContexts`.
The last commit message is wrong, please delete it when merging

**Comment by lanchengx** [comment]
@terrymanu please review

**Review by RaigorJiang — APPROVED** [review]

**Comment by RaigorJiang** [comment]
> @terrymanu @RaigorJiang please review

LGTM.

**Review by terrymanu — APPROVED** [review]

**Pull request merged**
