### PR TITLE
Adding the test cases for ShardingSQLRewriteContextDecorator and ShardingParameterRewriterBuilder

### LINKED ISSUE #13054: Add more unit tests
- [ ] ShardingSQLRewriteContextDecorator
- [ ] ShardingParameterRewriterBuilder

### PR DESCRIPTION
**Pull request by backdoor20**
Fixes #13054.

Changes proposed in this pull request:
Added the test case for 

- [x] ShardingSQLRewriteContextDecorator

- [x] ShardingParameterRewriterBuilder

### CODE REVIEW

**Comment by strongduanmu** [comment]
> @strongduanmu / @terrymanu can you help with approving the workflow

@backdoor20 Sorry for late reply, I just approve the workflow.

**Comment by strongduanmu** [comment]
@backdoor20 Can you fix ci error first?

**Comment by backdoor20** [comment]
@strongduanmu can you help me with adding the label **Hacktoberfest** and **Hacktoberfest-accepted**

**Comment by strongduanmu** [comment]
> @strongduanmu can you help me with adding the label **Hacktoberfest** and **Hacktoberfest-accepted**

@backdoor20 Of course.

**Comment by backdoor20** [comment]
@strongduanmu can you trigger the workflow.

**Comment by strongduanmu** [comment]
> @strongduanmu can you review the changes as requested and also re-approve the workflow.

@backdoor20 Ok, I will review it.

**Pull request merged**
