### PR TITLE
Adjust the select sql statement in OracleParserStatementExample.

### PR DESCRIPTION
**Pull request by jiangML**
Fixes https://github.com/apache/shardingsphere/issues/18680
Changes proposed in this pull request:
- Adjust the select sql statement in OracleParserStatementExample.

### CODE REVIEW

**Review by RaigorJiang — CHANGES_REQUESTED** [review]
There is more than one space between `table1` and  `t`, please fix.

**Review by terrymanu — CHANGES_REQUESTED** [review]
Oracle can support AS, the example is ok, please update oracle parser G4 file

**Comment by jiangML** [comment]
The select syntax is explained on pages 345, 347, and 350 of oracle's official documentation https://download.oracle.com/otn_hosted_doc/timesten/703/TimesTen-Documentation/sql.pdf.
Oracle column aliases support AS, table aliases do not support AS.

**Comment by RaigorJiang** [comment]
Agree, in Oracle, table alias does not support `AS`, and `AS` is optional between column and column_alias.
Refer to [doc](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/SELECT.html#GUID-CFA006CA-6FF1-4972-821E-6996142A51C6) and search `t_alias`.

**Review by RaigorJiang — APPROVED** [review]

**Review by terrymanu — APPROVED** [review]
Thank you for the wonderful investigate

**Pull request merged**
