### PR TITLE
Update snakeyaml to 1.32 to fix yaml deserialization problem

### LINKED ISSUE #21043: Update snakeyaml to 1.31 or 1.32 to fix unit tests
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

- Yes, refer to https://github.com/apache/shardingsphere/pull/15260 .

### Describe the feature you would like.

- At https://github.com/apache/shardingsphere/pull/15260, the yaml 1.1 deserialization bug introduced since snakeyaml 1.19 was discovered for the first time.  This issue was reported at https://bitbucket.org/snakeyaml/snakeyaml/issues/387/support-for-generic-types-when-serializing and fixed in Snakeyaml 1.31.  Although the corresponding unit tests have been changed directly, raising to a higher version will still help explain some unreasonable yaml deserialization errors.

### PR DESCRIPTION
**Pull request by linghengqian**
Fixes #21043.

Changes proposed in this pull request:
  - Update pom.xml and LICENSE.

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [x] I have triggered maven check: `mvn clean install -B -T2C -DskipTests -Dmaven.javadoc.skip=true -e`.
- [x] I have made corresponding changes to the documentation.
- [x] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Review by sandynz — APPROVED** [review]

**Comment by pjfanning** [comment]
@linghengqian apologies but I only discovered this a few hours ago - snakeyaml 1.32 has a change that makes 3Mb the default limit on the size of yaml file it will parse. To parse bigger files, you need to update a LoaderOptions instance and use that when creating a YAMLParser.

https://bitbucket.org/snakeyaml/snakeyaml/src/26624702fab8e0a1c301d7fad723c048528f75c3/src/main/java/org/yaml/snakeyaml/LoaderOptions.java#lines-146

https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes

**Comment by linghengqian** [comment]
> @linghengqian apologies but I only discovered this a few hours ago - snakeyaml 1.32 has a change that makes 3Mb the default limit on the size of yaml file it will parse. To parse bigger files, you need to update a LoaderOptions instance and use that when creating a snakeyaml ParserImpl.
> 
> https://bitbucket.org/snakeyaml/snakeyaml/src/26624702fab8e0a1c301d7fad723c048528f75c3/src/main/java/org/yaml/snakeyaml/LoaderOptions.java#lines-146
> 
> https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes 

- I can hardly imagine a situation in which ShardingSphere would export or import a yaml `> 3MB`, since there has never been such a unit test before.  I noticed that Spring Boot often uses very long YAML files, but the corresponding commit does not reflect this, refer to https://github.com/spring-projects/spring-boot/commit/59448ce5d2d622dfc53813c0389e017142443388 .  It would be nice if a friend found a failing unit test in an new open issue.😂

**Comment by pjfanning** [comment]
If you are happy to stick with snakeyaml's 3Mb limit than that's fine - some projects may have use cases that require overriding snakeyaml's default but it seems like shardingsphere is not one of them.

**Comment by linghengqian** [comment]
- https://bitbucket.org/snakeyaml/snakeyaml/issues/553/loaderoptionssetcodepointlimit-not-honored was resolved in SnakeYAML 1.33, which to a certain extent facilitates the process of opening the 3MB limit. It would be great if someone would be happy to open a new issue.

**Comment by linghengqian** [comment]
- I opened https://github.com/apache/shardingsphere/pull/21351. SnakeYAML's API has silenced me a bit, and I'm leaving it as a draft for now to investigate two other related issues.

**Pull request merged**
