### PR TITLE
resolve issue 5289

### PR DESCRIPTION
**Pull request by edidada**
Fixes #I5289.

Changes proposed in this pull request:
- modify five configuretion files to new API

### CODE REVIEW

**Comment by tristaZero** [comment]
@edidada Hi 
Glad to see your first PR to ShardingSphere community, however, there is comment needed to look at. :-)

**Comment by edidada** [comment]
OK， I will modify the target configure instad of replace hole file through ftp

**Comment by tristaZero** [comment]
Hi @edidada do you think this PR is supported to closed? If so, please make it.

**Comment by tristaZero** [comment]
@edidada Hi, We have not received your response for more than seven days. Besides, This PR has a lot of conflicts already. So we have to close this one and welcome your new one.

Best,
Trista

**Pull request closed without merging**
