### PR TITLE
fix data node suffix pattern(#19423)

### LINKED ISSUE #19423: A bug in the binding table at version 5.1.1
A bug in the binding table, the table is divided according to order_id and user_id, and an exception is displayed
image

image

### PR DESCRIPTION
**Pull request by marker-wu**
Fixes #19423 

Changes proposed in this pull request:
- fix data node suffix pattern

### CODE REVIEW

**Review by strongduanmu — CHANGES_REQUESTED** [review]
@marker-wu Can you add some unit test for this logic.

**Comment by marker-wu** [comment]
> 



> @marker-wu Can you add some unit test for this logic.
Add test case to the TableRuleTest class?
image

**Comment by strongduanmu** [comment]
@marker-wu Yes, we need to add some unit test in TableRuleTest for this new logic.

**Comment by marker-wu** [comment]
> @marker-wu Yes, we need to add some unit test in TableRuleTest for this new logic.
is this OK？
image

**Comment by marker-wu** [comment]
Any problem with my test case? If not, I'm ready to submit the code

**Comment by strongduanmu** [comment]
> @strongduanmu Any problem with my test case? If not, I'm ready to submit the code

@marker-wu You can submit the unit test, I will review this pr later.

**Comment by marker-wu** [comment]
> > @strongduanmu Any problem with my test case? If not, I'm ready to submit the code
> 
> @marker-wu You can submit the unit test, I will review this pr later.

Done!

**Review by strongduanmu — APPROVED** [review]

**Pull request merged**
