### PR TITLE
Add MySQL parse support for `DESCRIBE Statement`

### PR DESCRIPTION
**Pull request by totalo**
For #14110.

Changes proposed in this pull request:
- add MySQL parse support for `DESCRIBE Statement`
- add test case

### CODE REVIEW

**Review by terrymanu — APPROVED** [review]

**Comment by tristaZero** [comment]
Hello @totalo Thanks for your active contributions! I am curious whether you'd like to be the committer of Apache ShardingSphere? [Apache committer](https://community.apache.org/contributors/) will introduce more about this hat.

**Comment by totalo** [comment]
> Hello @totalo Thanks for your active contributions! I am curious whether you'd like to be the committer of Apache ShardingSphere? [Apache committer](https://community.apache.org/contributors/) will introduce more about this hat.

hi @tristaZero ,Of course, I am very happy to have the opportunity to be a committer.

**Comment by tristaZero** [comment]
@totalo Cool, then I will start the voting of the committer these days.

**Comment by totalo** [comment]
> 

All right! thanks.very excited, I will continue to work hard.

**Comment by totalo** [comment]
> @totalo Cool, then I will start the voting of the committer these days.

All right! thanks.very excited, I will continue to work hard.

**Pull request merged**
