### PR TITLE
add checkstyle for IDEA 

### PR DESCRIPTION
**Pull request by lovepoem**
fix https://github.com/apache/shardingsphere/issues/7694 to 
add checkstyle for IDEA

### CODE REVIEW

**Comment by tristaZero** [comment]
@lovepoem Thanks, it looks like @terrymanu has the context of this one.

**Review by terrymanu — COMMENTED** [review]
Is it checkstyle or just code format file?
How to use it?

**Comment by lovepoem** [comment]
> @lovepoem Thanks, it looks like @terrymanu has the context of this one.

Now I use the latest version of IDEA, It no longer supports [jar version style](https://shardingsphere.apache.org/community/en/contribute/code-conduct/)

But the file `checkstyle_for_IDEA.xml` ，It doesn't seem to work ：`Line breaks will be generated automatically`

image

**Comment by lovepoem** [comment]
It's better to use https://shardingsphere.apache.org/community/en/contribute/code-conduct/

**Pull request closed without merging**
