### PR TITLE
Updates ElasticJob to 3.0.4 to block CVEs for SnakeYAML delivery

### LINKED ISSUE #25291: Sharding startup failed after upgrading the snake yml component to version 2.0
sharding version：   
     <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core</artifactId>
            <version>5.3.2</version>	
       <dependency>
snakeYaml version：
     <dependency>
	<groupId>org.yaml</groupId>
	<artifactId>snakeyaml</artifactId>
	<version>2.0</version>  
     </dependency>

at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.7.10.jar:2.7.10]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164) ~[spring-boot-2.7.10.jar:2.7.10]
	at com.huawei.hdn.explorer.Application.main(Application.java:71) ~[classes/:?]
Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method <init>()V not found
	at org.apache.shardingsphere.infra.util.yaml.representer.ShardingSphereYamlRepresenter.<init>(ShardingSphereYamlRepresenter.java:42) ~[shardingsphere-infra-util-5.3.2.jar:5.3.2]
	at org.apache.shardingsphere.infra.util.yaml.YamlEngine.marshal(YamlEngine.java:113) ~[shardingsphere-infra-util-5.3.2.jar:5.3.2]
	at org.apache.shardingsphere.mode.metadata.persist.service.config.global.PropertiesPersistService.persist(PropertiesPersistService.java:45) ~[shardingsphere-mode-core-5.3.2.jar:5.3.2]
	at org.apache.shardingsphere.mode.metadata.persist.service.config.global.PropertiesPersistService.conditionalPersist(PropertiesPersistService.java:39) ~[shardingsphere-mode-core-5.3.2.jar:5.3.2]
	at org.apache.shardingsphere.mode.metadata.persist.MetaDataPersistService.persistConfigurations(MetaDataPersistService.java:86) ~[shardingsphere-mode-core-5.3.2.jar:5.3.2]
	at org.apache.shardingsphere.mode.manager.standalone.StandaloneContextManagerBuilder.persistConfigurations(StandaloneContextManagerBuilder.java:61) ~[shardingsphere-standalone-mode-core-5.3.2

### LINKED ISSUE #27370: The service starts the error when upgrade snakeyaml to version 2.0
Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method <init>()V not found
	at org.apache.shardingsphere.underlying.common.yaml.representer.DefaultYamlRepresenter.<init>(DefaultYamlRepresenter.java:33) ~[shardingsphere-common-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.underlying.common.yaml.engine.YamlEngine.marshal(YamlEngine.java:170) ~[shardingsphere-common-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.core.log.ConfigurationLogger.log(ConfigurationLogger.java:65) ~[sharding-core-common-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.core.log.ConfigurationLogger.log(ConfigurationLogger.java:54) ~[sharding-core-common-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.context.AbstractRuntimeContext.<init>(AbstractRuntimeContext.java:58) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.context.MultipleDataSourcesRuntimeContext.<init>(MultipleDataSourcesRuntimeContext.java:50) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.context.ShardingRuntimeContext.<init>(ShardingRuntimeContext.java:49) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.datasource.ShardingDataSource.<init>(ShardingDataSource.java:54) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.api.ShardingDataSourceFactory.createDataSource(ShardingDataSourceFactory.java:48) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]

### LINKED ISSUE #28067: Please support snakeyaml 2.0.
## Feature Request

**For English only**, other languages will not be accepted.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
When snakeyaml 2.0 is used in a project, an error is reported and the project cannot be started.

### Describe the feature you would like.
Please support snakeyaml 2.0.

### LINKED ISSUE #28233: Snakeyml 2.1 compatibility issue with shardingsphere-jdbc-core-spring-boot-starter 5.2.1
**Tech Stack** - Java 17, Springboot 3.1.2, Spring Framework 6, shardingsphere-jdbc-core-spring-boot-starter 5.2.1
**Exception** - 

**Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found
    at org.apache.shardingsphere.infra.util.yaml.representer.ShardingSphereYamlRepresenter.<init>**(ShardingSphereYamlRepresenter.java:41) ~[shardingsphere-infra-util-5.2.1.jar:5.2.1]
    at org.apache.shardingsphere.infra.util.yaml.YamlEngine.marshal(YamlEngine.java:113) ~[shardingsphere-infra-util-5.2.1.jar:5.2.1]
    at org.apache.shardingsphere.mode.metadata.persist.service.config.global.PropertiesPersistService.persist(PropertiesPersistService.java:45) ~[shardingsphere-mode-core-5.2.1.jar:5.2.1]
    at org.apache.shardingsphere.mode.metadata.persist.service.config.global.PropertiesPersistService.conditionalPersist(PropertiesPersistService.java:39) ~[shardingsphere-mode-core-5.2.1.jar:5.2.1]
    at org.apache.shardingsphere.mode.metadata.persist.MetaDataPersistService.persistConfigurations(MetaDataPersistService.java:86) ~[shardingsphere-mode-core-5.2.1.jar:5.2.1]
    at org.apache.shardingsphere.mode.manager.standalone.StandaloneContextManagerBuilder.persistConfigurations(StandaloneContextManagerBuilder.java:55) ~[shardingsphere-standalone-mode-core-5.2.1.jar:5.2.1]
    at org.apache.shardingsphere.mode.manager.standalone.StandaloneContextManagerBuilder.build(StandaloneContextManagerBuilder.java:46) ~[shardingsphere-standalone-mode-core-5.2.1.jar:5.2.1]
    at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.createContextManager(ShardingSphereDataSource.java:76) ~[shardingsphere-jdbc-core-5.2.1.jar:5.2.1]
    at org.apache.shardingsphere.driver.jdbc.core.datasource.ShardingSphereDataSource.<init>(ShardingSphereDataSource.java:64) ~[shardingsphere-jdbc-core-5.2.1.jar:5.2.1]
    at org.apache.shardingsphere.driver.api.ShardingSphereDataSourceFactory.createDataSource(ShardingSphereDataSourceFactory.java:93) ~[shardingsphere-jdbc-core-5.2.1.jar:5.2.1]
    at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration.shardingSphereDataSource(ShardingSphereAutoConfiguration.java:91) ~[shardingsphere-jdbc-core-spring-boot-starter-5.2.1.jar:5.2.1]
    at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration$$SpringCGLIB$$0.CGLIB$shardingSphereDataSource$2(<generated>) ~[shardingsphere-jdbc-core-spring-boot-starter-5.2.1.jar:5.2.1]
    at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration$$SpringCGLIB$$2.invoke(<generated>) ~[shardingsphere-jdbc-core-spring-boot-starter-5.2.1.jar:5.2.1]
    at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[spring-core-6.0.11.jar:6.0.11]
    at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-6.0.11.jar:6.0.11]
    at org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration$$SpringCGLIB$$0.shardingSphereDataSource(<generated>) ~[shardingsphere-jdbc-core-spring-boot-starter-5.2.1.jar:5.2.1]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:647) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:888) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:550) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByType(AbstractAutowireCapableBeanFactory.java:1498) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1407) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:597) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337) ~[spring-beans-6.0.11.jar:6.0.11]
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:713) ~[spring-beans-6.0.11.jar:6.0.11]

### PR DESCRIPTION
**Pull request by linghengqian**
Fixes #24636.

Changes proposed in this pull request:
  - Updates ElasticJob to 3.0.4 to block CVEs for SnakeYAML delivery. Refer to https://github.com/apache/shardingsphere-elasticjob/releases/tag/3.0.4 .
  - Also fixes #28233.
  - Also fixes #28067.
  - Also fixes #27370.
  - Also fixes #25291.
  - Since the CI of the Exmaple module is broken on JDK21, I am not handling the changes to the Example module in this PR. Refer to https://github.com/apache/shardingsphere/actions/runs/6563502380 .

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [x] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [x] I have made corresponding changes to the documentation.
- [x] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Review by terrymanu — APPROVED** [review]

**Comment by xiohuchi** [comment]
不知道修复版本什么时候发布，有大佬知道怎么临时解决吗

**Comment by linghengqian** [comment]
> 不知道修复版本什么时候发布，有大佬知道怎么临时解决吗

@xiohuchi 

- You can manually compile the project by following the steps below, and upload the corresponding products in the local Maven repository to your private repository. This uses `SDKMAN!`.
```shell
sdk install java 21.0.2-graalce
sdk use java 21.0.2-graalce

git clone git@github.com:apache/shardingsphere.git
cd ./shardingsphere/

./mvnw clean install -Prelease -T1C -DskipTests -Djacoco.skip=true -Dcheckstyle.skip=true -Drat.skip=true -Dmaven.javadoc.skip=true -B
```

- I'm not the PMC for the project, so I can't make any subjective assumptions about when the next release will be. If you need a release sooner, you should start a discussion thread on the mailing list.

**Comment by 1Yangc** [comment]
`<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc</artifactId>
            <version>5.4.2-SNAPSHOT</version>
        </dependency>`

Pay attention. Use `shardingsphere-jdbc` replace `shardingsphere-jdbc-core`

It's worked! 
it bothered me for two days.
Thanks!

and how long can we use in new 5.4.2 release version?

**Comment by linghengqian** [comment]
> Pay attention. Use `shardingsphere-jdbc` replace `shardingsphere-jdbc-core`

- This is the change brought by #30182 .

> and how long can we use in new 5.4.2 release version?

- If you expect a faster release, you should leave a message in the mail thread at https://lists.apache.org/thread/0kwvkzclnhn312vjlcyyr02md995yfv9 . It seems that the several delays to the 5.5.0 milestone are due to the need to adjust the metadata structure.
- As a committer, I personally only have non-binding release voting right. In any case, according to ASF regulations, the release process must be completed on the mailing list, which has nothing to do with github.com.

**Comment by 1Yangc** [comment]
> > Pay attention. Use `shardingsphere-jdbc` replace `shardingsphere-jdbc-core`
> 
> * This is the change brought by [Merge shardingsphere-jdbc-core to shardingsphere-jdbc module and update doc #30182](https://github.com/apache/shardingsphere/pull/30182) .
> 
> > and how long can we use in new 5.4.2 release version?
> 
> * If you expect a faster release, you should leave a message in the mail thread at https://lists.apache.org/thread/0kwvkzclnhn312vjlcyyr02md995yfv9 . It seems that the several delays to the 5.5.0 milestone are due to the need to adjust the metadata structure.
> * As a committer, I personally only have non-binding release voting right. In any case, according to ASF regulations, the release process must be completed on the mailing list, which has nothing to do with github.com.

Thanks!

I have another question. In a single database, only 1-2  tables need to be sharded, and other tables do not need to be sharded. How do I configure the YAML file?

**Comment by 1Yangc** [comment]
> > Pay attention. Use `shardingsphere-jdbc` replace `shardingsphere-jdbc-core`
> 
> * This is the change brought by [Merge shardingsphere-jdbc-core to shardingsphere-jdbc module and update doc #30182](https://github.com/apache/shardingsphere/pull/30182) .
> 
> > and how long can we use in new 5.4.2 release version?
> 
> * If you expect a faster release, you should leave a message in the mail thread at https://lists.apache.org/thread/0kwvkzclnhn312vjlcyyr02md995yfv9 . It seems that the several delays to the 5.5.0 milestone are due to the need to adjust the metadata structure.
> * As a committer, I personally only have non-binding release voting right. In any case, according to ASF regulations, the release process must be completed on the mailing list, which has nothing to do with github.com.

Thanks!

**Comment by lizhongyue248** [comment]
> ```
>    <dependency>
>         <groupId>org.apache.shardingsphere</groupId>
>         <artifactId>shardingsphere-jdbc</artifactId>
>         <version>5.4.2-SNAPSHOT</version>
>     </dependency>
> ```
> 
> Pay attention. Use `shardingsphere-jdbc` replace `shardingsphere-jdbc-core`
> 
> It's worked! it bothered me for two days. Thanks!
> 
> and how long can we use in new 5.4.2 release version?

Hello, did you manually compile the version  `5.4.2-SNAPSHOT`?

**Comment by linghengqian** [comment]
- @lizhongyue248 Refer to https://github.com/apache/shardingsphere/issues/30318#issuecomment-2002341706 .

**Comment by Coding-Cooking-Cooling** [comment]
I found that even with ShardingSphere 5.4.1 and SnakeYaml 2.1, the startup was successful. Why?

**Comment by linghengqian** [comment]
> I found that even with ShardingSphere 5.4.1 and SnakeYaml 2.1, the startup was successful. Why?

- There are many possible reasons. For example, you did not call the conflicting method of SnakeYAML. This may be because you only created the ShardingSphere data source through DistSQL of ShardingSphere Proxy or the Java API of ShardingSphere JDBC.

**Comment by daipeizhe** [comment]
> > I found that even with ShardingSphere 5.4.1 and SnakeYaml 2.1, the startup was successful. Why?
> 
> * There are many possible reasons. For example, you did not call the conflicting method of SnakeYAML. This may be because you only created the ShardingSphere data source through DistSQL of ShardingSphere Proxy or the Java API of ShardingSphere JDBC.

If I manually reference SnakeYaml in the pom.xml file and specify a version above 2.x, the startup is fine; However, if you do not manually reference SnakeYaml, the SnakeYaml version of the project, although it is also 2.0, will still start error. In addition, I did configure ShardingSphere JDBC through the Java API.

**Comment by linghengqian** [comment]
> > > I found that even with ShardingSphere 5.4.1 and SnakeYaml 2.1, the startup was successful. Why?
> > 
> > 
> > 
> > * There are many possible reasons. For example, you did not call the conflicting method of SnakeYAML. This may be because you only created the ShardingSphere data source through DistSQL of ShardingSphere Proxy or the Java API of ShardingSphere JDBC.
> 
> If I manually reference SnakeYaml in the pom.xml file and specify a version above 2.x, the startup is fine; However, if you do not manually reference SnakeYaml, the SnakeYaml version of the project, although it is also 2.0, will still start error. In addition, I did configure ShardingSphere JDBC through the Java API.

- This doesn't really mean anything, as ShardingSphere JDBC 5.4.1 explicitly uses methods that were removed from SnakeYAML 2.0.

**Comment by daipeizhe** [comment]
> > > > I found that even with ShardingSphere 5.4.1 and SnakeYaml 2.1, the startup was successful. Why?
> > > 
> > > 
> > > 
> > > * There are many possible reasons. For example, you did not call the conflicting method of SnakeYAML. This may be because you only created the ShardingSphere data source through DistSQL of ShardingSphere Proxy or the Java API of ShardingSphere JDBC.
> > 
> > 
> > If I manually reference SnakeYaml in the pom.xml file and specify a version above 2.x, the startup is fine; However, if you do not manually reference SnakeYaml, the SnakeYaml version of the project, although it is also 2.0, will still start error. In addition, I did configure ShardingSphere JDBC through the Java API.
> 
> * This doesn't really mean anything, as ShardingSphere JDBC 5.4.1 explicitly uses methods that were removed from SnakeYAML 2.0.
You're right, I found out that the framework I was using overwrote the missing parameterless Representer class constructor.

**Comment by daipeizhe** [comment]
> > > > I found that even with ShardingSphere 5.4.1 and SnakeYaml 2.1, the startup was successful. Why?
> > > 
> > > 
> > > 
> > > * There are many possible reasons. For example, you did not call the conflicting method of SnakeYAML. This may be because you only created the ShardingSphere data source through DistSQL of ShardingSphere Proxy or the Java API of ShardingSphere JDBC.
> > 
> > 
> > If I manually reference SnakeYaml in the pom.xml file and specify a version above 2.x, the startup is fine; However, if you do not manually reference SnakeYaml, the SnakeYaml version of the project, although it is also 2.0, will still start error. In addition, I did configure ShardingSphere JDBC through the Java API.
> 
> * This doesn't really mean anything, as ShardingSphere JDBC 5.4.1 explicitly uses methods that were removed from SnakeYAML 2.0.

You're right, I found out that the framework I was using overwrote the missing parameterless Representer class constructor.

**Review by linghengqian — COMMENTED** [review]
- I've opened https://bitbucket.org/snakeyaml/snakeyaml/issues/1093/yaml-constructor-does-not-respect for follow-up effects of this PR.

**Pull request merged**
