### PR TITLE
Add more unit test for ShardingRule

### PR DESCRIPTION
**Pull request by longtai-cn**
Changes proposed in this pull request:
- Add more unit test for ShardingRule.

> https://github.com/apache/shardingsphere/issues/16288 The task was split into two, so fixes was not filled in.

### CODE REVIEW

**Review by strongduanmu — CHANGES_REQUESTED** [review]
@longtai-cn Can you fix ci error first?

**Comment by longtai-cn** [comment]
> @longtai-cn Can you fix ci error first?

@strongduanmu There's nothing I can do because the CI error seems to be caused by another problem.

image

image

These are not within the scope of this submission.

**Comment by zjcnb** [comment]
> > @longtai-cn Can you fix ci error first?
> 
> @strongduanmu There's nothing I can do because the CI error seems to be caused by another problem.
> 
> image
> 
> image
> 
> These are not within the scope of this submission.

You can try to merge latest code in `master`, and push it again.

**Comment by longtai-cn** [comment]
@zjcnb At present, my local is the latest, but there is an error executing the following command.

>  mvn clean install -Dmaven.javadoc.skip=true -B -Drat.skip=true -Djacoco.skip=true  -Prelease

**Comment by longtai-cn** [comment]
@strongduanmu @zjcnb Completed ci.

**Review by strongduanmu — APPROVED** [review]
@longtai-cn Thank you, merged.

**Pull request merged**
