### PR TITLE
Move change history in java api to others

### LINKED ISSUE #10976: [Doc] Optimize change history of ShardingSphere-JDBC Java API (English)
Hi community,

This issue is for [#10887](https://github.com/apache/shardingsphere/issues/10887).

### Background

Refor to #10972 

### Aim

Optimize change history of ShardingSphere-JDBC Java API (English version). 

### How to

1. Migrate `Java API` change history from
   `4.1.2.Configuration Manual`->`Java API`->`Change History` to
   `7.2.API Change History`->`7.2.1.ShardingSphere-JDBC`->`Java API`;
2. Refer to the documents of each version on the official website, check whether the change history is correct, and fill in the missing parts.
3. The content organization of the change history is as follows:

   - ShardingSphere-5.0.0-beta
     - Sharding
     - Readwrite-splitting
     - Encryption
     - Shadow DB
     - Governance
   - ShardingSphere-4.x
     - Sharding
     - Readwrite-splitting
     - Data Masking
     - Orchestration
   - ShardingSphere-3.x
     - Sharding
     - Readwrite-splitting
     - Orchestration
   - ShardingSphere-2.x
     - Sharding
     - Readwrite-splitting
     - Orchestration

### Reference

- [Apache ShardingSphere website](https://shardingsphere.apache.org/)

- [Java API change history](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/configuration/java-api/change-history/)

### PR DESCRIPTION
**Pull request by Swastyy**
Fixes #10976 

Changes proposed in this pull request:
- Created java-api folder in sharding-sphere-jdbc
- Moved `change-history.en.md`
- Changes in `change-history.en.md`

### CODE REVIEW

**Comment by Swastyy** [comment]
@tristaZero Should I add a `_index.en.md` inside java-api folder?
@RaigorJiang Do tell me from where I can find more information to write for 5.0.0.

**Comment by RaigorJiang** [comment]
Hi @Swastyy
For information about version 5.0.0, please refer to the current version of the document. [Link](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/configuration/java-api/sharding/)

**Comment by tristaZero** [comment]
@Swastyy Welcome to come back.

**Comment by Swastyy** [comment]
@tristaZero @RaigorJiang @menghaoranss Pl review this PR. Thanks.

**Comment by RaigorJiang** [comment]
@Swastyy 
Thanks for your update, but I have some questions:
1. Why are there both `Readwrite-splitting` and `Replica Query` in `5.0.0-beta`, they actually have the same meaning, the current name is `Readwrite-splitting`.  So please remove `Replica Query`.

2. The following configuration informations are missing in 5.0.0-beta:
- Sharding Table Configuration, Sharding Automatic Table Configuration, Sharding Strategy Configuration (in [Sharding](https://github.com/apache/shardingsphere/blob/master/docs/document/content/user-manual/shardingsphere-jdbc/configuration/java-api/sharding.en.md) 
- Root Configuration (in [Readwrite-splitting](https://github.com/apache/shardingsphere/blob/master/docs/document/content/user-manual/shardingsphere-jdbc/configuration/java-api/readwrite-splitting.en.md))
- Encrypt Table Rule Configuration, Encrypt Column Rule Configuration and Encrypt Algorithm Configuration (in [Encryption](https://github.com/apache/shardingsphere/blob/master/docs/document/content/user-manual/shardingsphere-jdbc/configuration/java-api/encrypt.en.md))
- Governance [link](https://github.com/apache/shardingsphere/blob/master/docs/document/content/user-manual/shardingsphere-jdbc/configuration/java-api/governance.en.md)

3. The content of 4.x should not only contain `Readwrite-splitting`, more content can be copied from [here](https://shardingsphere.apache.org/document/legacy/4.x/document/en/manual/sharding-jdbc/configuration/config-java/#configuration-item-explanation) 

4. As the same, more content of 3.x is [here](https://shardingsphere.apache.org/document/legacy/3.x/document/en/manual/sharding-jdbc/configuration/config-java/#configuration-reference)

5. Access to archived documents 2.x is not stable, so don't care about it this time.

**Comment by Swastyy** [comment]
@RaigorJiang Done. Review it.

**Comment by RaigorJiang** [comment]
> @RaigorJiang Done. Review it.

@Swastyy  I think it's OK now, thanks a lot.

**Comment by Swastyy** [comment]
> > @RaigorJiang Done. Review it.
> 
> @Swastyy I think the content is OK now, thanks a lot. But the file path may be `others/api-change-history/shardingsphere-jdbc/java-api.en.md` ? Please check [it](https://github.com/apache/shardingsphere/tree/master/docs/document/content/others/api-change-history/shardingsphere-jdbc).

Yeah, I have changed the file path. Thanks for pointing out @RaigorJiang . 
@tristaZero Pl review it.

**Review by RaigorJiang — APPROVED** [review]

**Comment by Swastyy** [comment]
Hi @tristaZero , pl review this PR.

**Review by tristaZero — APPROVED** [review]
Hi @Swastyy Thanks for your efforts. ;-) I am glad to see this PR becomes a part of the community.
@RaigorJiang Nice review.

**Pull request merged**
