### PR TITLE
Refactor MySQL `table` statement

### PR DESCRIPTION
**Pull request by totalo**
For #14110.

Changes proposed in this pull request:
- refactor `table` statement
- update test case

### CODE REVIEW

**Review by strongduanmu — CHANGES_REQUESTED** [review]
Hi @totalo, thank you for your contribution, but can you fix ci error first?

**Comment by totalo** [comment]
> Hi @totalo, thank you for your contribution, but can you fix ci error first?

Ok,just moment.

**Review by strongduanmu — APPROVED** [review]
@totalo Good job, merged.

**Comment by totalo** [comment]
> @totalo Good job, merged.

Thanks.

**Pull request merged**
