### PR TITLE
Changed directory names under the example

### PR DESCRIPTION
**Pull request by iamkyu**
Related to https://github.com/apache/shardingsphere/pull/11082

Changes proposed in this pull request: 
Changed directory names under the example
- `sharding-jdbc` to `shardingsphere-jdbc`
- `sharding-proxy` to `shardingsphere-proxy`

cc @tristaZero  @TeslaCN

### CODE REVIEW

**Review by terrymanu — APPROVED** [review]

**Comment by tristaZero** [comment]
Hey @iamkyu ,
Thanks for your PR. I am just curious what makes you interested in this project?

**Comment by iamkyu** [comment]
@tristaZero My pleasure.
I am interested in contributing to the open source that I am using in production.
Thank you for providing a good open source project 😄

**Comment by tristaZero** [comment]
Thanks @iamkyu .

So you adopted ShardingSphere Proxy for your production?

**Comment by iamkyu** [comment]
@tristaZero 
I adopted ShardingSphere-jdbc

**Comment by tristaZero** [comment]
@iamkyu Aha, good choice, pretty simple, right?

**Pull request merged**
