### PR TITLE
Moved SELECT_SQL_BY_ID_ACROSS_SINGLE_AND_SHARDING_TABLES_ALIAS from FederateStatementTest to shardingsphere-integration-test

### LINKED ISSUE #10915: Refactor SELECT_SQL_BY_ID_ACROSS_SINGLE_AND_SHARDING_TABLES_ALIAS statement with shardingsphere-integration-test
Hi community,

This issue is for #10887.

# Background

Currently `FederateStatementTest` and `FederatePrepareStatementTest` use JUNIT to test SQL statements. In order to improve test coverage and code elegance, we need to migrate the test scenarios of FederateStatementTest and FederatePrepareStatementTest to `shardingsphere-integration-test`. 

# Target

The goal of this issue is to migrate the `SELECT_SQL_BY_ID_ACROSS_SINGLE_AND_SHARDING_TABLES_ALIAS` statement to the `shardingsphere-integration-test` module. 

You can search for the `SELECT_SQL_BY_ID_ACROSS_SINGLE_AND_SHARDING_TABLES_ALIAS` keyword, and then you will find the test cases in `FederateStatementTest` and `FederatePrepareStatementTest`.

FederateStatementTest:

```java
    private static final String SELECT_SQL_BY_ID_ACROSS_SINGLE_AND_SHARDING_TABLES_ALIAS = "select o.*, i.* from"
            + " t_order_federate o, t_order_item_federate_sharding i where o.order_id = i.item_id";
    
    @Test
    public void assertQueryWithFederateInSingleAndShardingTableWithAliasByExecuteQuery() throws SQLException {
        assertQueryWithFederateInSingleAndShardingTableWithAlias(true);
    }
    
    @Test
    public void assertQueryWithFederateInSingleAndShardingTableWithAliasByExecute() throws SQLException {
        assertQueryWithFederateInSingleAndShardingTableWithAlias(false);
    }
    
    private void assertQueryWithFederateInSingleAndShardingTableWithAlias(final boolean executeQuery) throws SQLException {
        ShardingSphereStatement statement = (ShardingSphereStatement) getShardingSphereDataSource().getConnection().createStatement();
        ResultSet resultSet = getResultSet(statement, SELECT_SQL_BY_ID_ACROSS_SINGLE_AND_SHARDING_TABLES_ALIAS, executeQuery);
        assertNotNull(resultSet);
        assertTrue(resultSet.next());
        assertThat(resultSet.getInt(1), is(1000));
        assertThat(resultSet.getInt(2), is(10));
        assertThat(resultSet.getString(3), is("init"));
        assertThat(resultSet.getInt(4), is(1000));
        assertThat(resultSet.getInt(5), is(10000));
        assertTrue(resultSet.next());
        assertThat(resultSet.getInt(1), is(1001));
        assertThat(resultSet.getInt(2), is(11));
        assertThat(resultSet.getString(3), is("init"));
        assertThat(resultSet.getInt(4), is(1001));
        assertThat(resultSet.getInt(5), is(10001));
        assertFalse(resultSet.next());
    }
```

FederatePrepareStatementTest:

```java
    private static final String SELECT_SQL_BY_ID_ACROSS_SINGLE_AND_SHARDING_TABLES_ALIAS =
            "select o.*, i.* from t_order_federate o, t_order_item_federate_sharding i "
                    + "where o.order_id = i.item_id AND i.order_id = ?";

        @Test
    public void assertQueryWithFederateInSingleAndShardingTableWithAliasByExecuteQuery() throws SQLException {
        assertQueryWithFederateInSingleAndShardingTableWithAlias(true);
    }
    
    @Test
    public void assertQueryWithFederateInSingleAndShardingTableWithAliasByExecute() throws SQLException {
        assertQueryWithFederateInSingleAndShardingTableWithAlias(false);
    }
    
    public void assertQueryWithFederateInSingleAndShardingTableWithAlias(final boolean executeQuery) throws SQLException {
        ShardingSpherePreparedStatement preparedStatement = (ShardingSpherePreparedStatement) getShardingSphereDataSource()
                .getConnection().prepareStatement(SELECT_SQL_BY_ID_ACROSS_SINGLE_AND_SHARDING_TABLES_ALIAS);
        preparedStatement.setInt(1, 10001);
        ResultSet resultSet = getResultSet(preparedStatement, executeQuery);
        assertNotNull(resultSet);
        assertTrue(resultSet.next());
        assertThat(resultSet.getInt(1), is(1001));
        assertThat(resultSet.getInt(2), is(11));
        assertThat(resultSet.getString(3), is("init"));
        assertThat(resultSet.getInt(4), is(1001));
        assertThat(resultSet.getInt(5), is(10001));
        assertFalse(resultSet.next());
    }
```

# How to
In order to finish this task, you need to understand the [documentation](https://shardingsphere.apache.org/document/current/en/features/test-engine/integration-test/) of the integration test first, and PR #10913 also provides an example, which you can refer to. BTW, if you have any questions, please leave a comment.

### PR DESCRIPTION
**Pull request by Swastyy**
Fixes #10915 

Changes proposed in this pull request:
-Tried to move federatestatement test to integration test

### CODE REVIEW

**Comment by tristaZero** [comment]
@Swastyy Thanks for your first PR here, I just approved and then all the CI tests will run. @strongduanmu will give it a review later one.

**Comment by strongduanmu** [comment]
@Swastyy Thank you for your efforts. Can you solve the ci error first?

**Comment by Swastyy** [comment]
> @Swastyy Thank you for your efforts. Can you solve the ci error first?

Yes, I am trying to fix it. I think there are more files that are to be changed

**Comment by strongduanmu** [comment]
@Swastyy Any progress?

**Comment by Swastyy** [comment]
@strongduanmu @RaigorJiang Do I have to make any change in `EnvironmentPath.java` ?

**Comment by RaigorJiang** [comment]
> @strongduanmu @RaigorJiang Do I have to make any change in `EnvironmentPath.java` ?

Sorry, I have no idea about this issue, let‘s look forward to @strongduanmu .

**Comment by Swastyy** [comment]
> @strongduanmu @RaigorJiang Do I have to make any change in `EnvironmentPath.java` ?

@strongduanmu Do I have to make any change in `EnvironmentPath.java` ?
Thanks.

**Comment by tristaZero** [comment]
Hi @strongduanmu   or @taojintianxia could you help @Swastyy out?

**Comment by strongduanmu** [comment]
> Hi @strongduanmu or @taojintianxia could you help @Swastyy out?

@Swastyy 

> Hi @strongduanmu or @taojintianxia could you help @Swastyy out?

@tristaZero @Swastyy Sorry for late reply. You doesn't need to change `EnvironmentPath.java`. You only need to add some table initial configuration, and then add some cases. PR #10913 provides a good example, and the [official documentation](https://shardingsphere.apache.org/document/current/en/features/test-engine/integration-test/) can also provide some help.

**Comment by taojintianxia** [comment]
I saw there are some `MySQLSyntaxError` appeared in CI action . @Swastyy , you could execute the test by executing command `./mvnw clean install -Dmaven.javadoc.skip=true -B -Drat.skip=true -Djacoco.skip=true -Dmaven.test.skip=true` in the root of the project on your own machine. that may reproduce the problem

**Comment by strongduanmu** [comment]
Hi @Swastyy, can we modify this PR? BTW, @LeeGuoPing has submitted a lot of similar PRs recently, you can refer to it, such as PR #11950.

**Comment by Swastyy** [comment]
> Hi @Swastyy, can we modify this PR? BTW, @LeeGuoPing has submitted a lot of similar PRs recently, you can refer to it, such as PR #11950.

Yep, I will resolve the failing Integration tests asap.

**Comment by strongduanmu** [comment]
Hi @Swastyy, any progress? If there is no reply for a long time, I will close this PR and you can submit a new ONE.

**Comment by Swastyy** [comment]
> Hi @Swastyy, any progress? If there is no reply for a long time, I will close this PR and you can submit a new ONE.

Hi @strongduanmu I will reopen the PR once I complete the task. I am still learning things which is taking time.

**Comment by strongduanmu** [comment]
@Swastyy If you need any help, please ping me.

**Pull request closed without merging**
