### PR TITLE
add SQL parser test case for ShowScalingStatusStatement (#15728)

### LINKED ISSUE #15728: [OpenForce 2022]  Add SQL parser test case for `ShowScalingStatusStatement`
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Background

`SHOW SCALING STATUS jobId` is a syntax in [DistSQL RAL](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/ral/), when `ShardingSphereSQLParserEngine` receives this SQL text, it parses it as `ShowScalingStatusStatement`. Now we need to add a test case for this parsing process to assert that its parsing is correct.

### Aim

Add SQL parser test case for `ShowScalingStatusStatement`.

- Affected files:

  - `SQLParserTestCases` (modify)

  - `shardingsphere-test/shardingsphere-parser-test/src/main/resources/case/ral/query.xml` (modify)

  - `shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported/ral/query.xml` (modify)

  - `shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/jaxb/cases/domain/statement/distsql/ral/scaling/ShowScalingStatusStatementTestCase.java` (create )

  - `shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/asserts/statement/distsql/ral/impl/scaling/query/ShowScalingStatusStatementAssert.java` (create )

  - `QueryableScalingRALStatementAssert` (modify)

- After all, execute `DistSQLParserParameterizedTest#assertDistSQL()` for validation

### Basic Qualifications

- Java
- Maven

### Example FYI

- `CheckScalingStatement`
- `CheckScalingStatementTestCase`
- `CheckScalingStatementAssert`
- search for "check-scaling"

### PR DESCRIPTION
**Pull request by pparthenhs**
Fixes #15728.

### CODE REVIEW

**Comment by RaigorJiang** [comment]
Hi @pparthenhs 
There are some CI failed, please merge the master branch and push again.

**Comment by pparthenhs** [comment]
> Hi @pparthenhs There are some CI failed, please merge the master branch and push again.

Dear @RaigorJiang,

I update the failing test. When I execute `./mvnw clean install` local, the build and test are successful. I use Linux (Centos 7) and Java 8.
image

Could you please help me with the CI test failing?

Thank you in advance for your time and collaboration.

Best regards, 
Panagiotis Parthenis

**Comment by RaigorJiang** [comment]
Sorry, CI failure is causing trouble for everyone. 
There are community contributors working on the CI right now, let's wait for the results, thank you!

**Review by RaigorJiang — APPROVED** [review]

**Comment by RaigorJiang** [comment]
Merged, thank you! @pparthenhs

**Pull request merged**
