### PR TITLE
update the export-distsql print format

### PR DESCRIPTION
**Pull request by isHuangXin**
Modify the export-distsql print format

- Before modify the print format
image

- After modify the print format
image

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
Could you fix CI?

**Comment by isHuangXin** [comment]
> Could you fix CI?
I think this error may be affecting import distsql when undating export distsql. 
I re-updated the code. plz check it~ thx.

- Before this time update
image

- After this time update
image

**Comment by isHuangXin** [comment]
I'm a beginner of open source projects, this PR is just to verify that I can submit a PR to shardingsphere correctly.

I am developing a new distsql statement `convert distsql`, which can automatically parse yaml files and generate distsql statements.

**Comment by terrymanu** [comment]
> I'm a beginner of open source projects, this PR is just to verify that I can submit a PR to shardingsphere correctly.
> 
> I am developing a new distsql statement `convert distsql`, which can automatically parse yaml files and generate distsql statements.

Great!, Welcome to join the community and develop more and more interesting features.

**Comment by terrymanu** [comment]
The CI still break, please fix it.

**Comment by isHuangXin** [comment]
> The CI still break, please fix it.

Please review again.

**Pull request closed without merging**
