### PR TITLE
Create tablespace relative location

### LINKED ISSUE #27861: Support parsing openGauss  CREATE sql
# Background
Hi community,

ShardingSphere parser engine helps users parse a SQL to get the AST (Abstract Syntax Tree) and visit this tree to get SQLStatement (Java Object). Currently, we are planning to enhance the support for openGauss SQL parsing in ShardingSphere.

More details:
https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/

# Task
This issue is to support more openGauss sql parse, as follows:
```sql
 CREATE TABLESPACE example2 RELATIVE LOCATION 'tablespace2/tablespace_2';

```

```sql
 CREATE TABLESPACE example3 RELATIVE LOCATION 'tablespace3/tablespace_3';

```

```sql
 CREATE TABLESPACE example4 RELATIVE LOCATION 'tablespace4/tablespace_4';
--创建表tpcds.customer_address_p1。

```

```sql
 CREATE TABLE tpcds.customer_address_p1
(
    CA_ADDRESS_SK             INTEGER               NOT NULL,
    CA_ADDRESS_ID             CHAR(16)              NOT NULL,
    CA_STREET_NUMBER          CHAR(10)                      ,
    CA_STREET_NAME            VARCHAR(60)                   ,
    CA_STREET_TYPE            CHAR(15)                      ,
    CA_SUITE_NUMBER           CHAR(10)                      ,
    CA_CITY                   VARCHAR(60)                   ,
    CA_COUNTY                 VARCHAR(30)                   ,
    CA_STATE                  CHAR(2)                       ,
    CA_ZIP                    CHAR(10)                      ,
    CA_COUNTRY                VARCHAR(20)                   ,
    CA_GMT_OFFSET             DECIMAL(5,2)                  ,
    CA_LOCATION_TYPE          CHAR(20)
)
TABLESPACE example1
PARTITION BY RANGE(CA_ADDRESS_SK)
( 
   PARTITION p1 VALUES LESS THAN (3000),
   PARTITION p2 VALUES LESS THAN (5000) TABLESPACE example1,
   PARTITION p3 VALUES LESS THAN (MAXVALUE) TABLESPACE example2
)
ENABLE ROW MOVEMENT;
--创建分区表索引ds_customer_address_p1_index1，不指定索引分区的名称。

```

```sql
 CREATE INDEX ds_customer_address_p1_index1 ON tpcds.customer_address_p1(CA_ADDRESS_SK) LOCAL; 
--创建分区表索引ds_customer_address_p1_index2，并指定索引分区的名称。

```

# Process
1. First confirm that this is a correct openGauss sql syntax, if not please leave a message under the issue and ignore it;
2. Compare SQL definitions in Official SQL Doc and ShardingSphere SQL Doc;
3. If there is any difference in ShardingSphere SQL Doc, please correct them by referring to the Official SQL Doc;
4. Run mvn install the current_file_module;
5. Check whether there are any exceptions. If indeed, please fix them. (Especially xxxVisitor.class);
6. Add new corresponding SQL case in SQL Cases and expected parsed result in Expected Statement XML;
7. Run SQLParserParameterizedTest to make sure no exceptions.

# Relevant Skills
1. Master JAVA language
2. Have a basic understanding of Antlr `g4` file
3. Be familiar with openGauss SQLs

### PR DESCRIPTION
**Pull request by dshunter107**
This first commit adds the keyword "Relative" as an option when creating a tablespace in openGauss

Fixes #27861

I have a few questions. I saw that the create tablespace class does not have any fields. Does that mean that you would prefer that information such as the location of data files should not be stored as Java Objects? Or are you looking for someone to put those pieces of information into a java object? 

Let me know if this is what you are looking for or something else, and I will continue working on the other commands. 

---

Before committing this PR, I'm sure that I have checked the following options:
- [ x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x ] I have self-reviewed the commit code.
- [x ] I have (or in comment I request) added corresponding labels for the pull request.
- [x ] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [x ] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Comment by dshunter107** [comment]
Hello. I am trying to see if I am on the right track so I can continue.

**Comment by strongduanmu** [comment]
Hi @dshunter107, can you solve code conflict?

**Comment by dshunter107** [comment]
Hello @strongduanmu . I wasn't sure what you meant by your message, but I was able to fix the code checks that were not passing, and I was able to update my repository. Is this what you were looking for?

**Comment by strongduanmu** [comment]
> Hello @strongduanmu . I wasn't sure what you meant by your message, but I was able to fix the code checks that were not passing, and I was able to update my repository. Is this what you were looking for?

Now it looks like CI has been fixed.

**Review by strongduanmu — APPROVED** [review]
Thank you for your contribution, merged.

**Comment by strongduanmu** [comment]
Hi @dshunter107, are you willing to participate in more SQL parsing tasks?

**Comment by dshunter107** [comment]
Hello. Yes I am willing to. @strongduanmu

**Comment by strongduanmu** [comment]
> Hello. Yes I am willing to. @strongduanmu

@dshunter107 Welcome. If you have an issue that interests you, please leave a comment.

**Pull request merged**
