### PR TITLE
Add syntax for DROP SHARDING KEY GENERATOR

### LINKED ISSUE #13999: Add syntax for `DROP SHARDING KEY GENERATOR`
For details, please refer to https://github.com/apache/shardingsphere/issues/13994

The ANTLR definition syntax is as follows:

```sql
DROP SHARDING KEY GENERATOR keyGeneratorName (COMMA keyGeneratorName)*;
```

Examples are as follows:

```sql
DROP SHARDING KEY GENERATOR uuid_key_generator;
```

### PR DESCRIPTION
**Pull request by Liangda-w**
Fixes #13999 

Changes proposed in this pull request:
- Add syntax for DROP SHARDING KEY GENERATOR
- Add the corresponding test case

### CODE REVIEW

**Comment by RaigorJiang** [comment]
Hi @Liangda-w 
There is a conflicting file, please resolve it, thanks!

**Comment by Liangda-w** [comment]
> Hi @Liangda-w There is a conflicting file, please resolve it, thanks!

Done:)

**Review by RaigorJiang — APPROVED** [review]

**Comment by tristaZero** [comment]
Hi @Liangda-w Glad to see your persistence here, and the `Insights` page also shows your lots of contributions recently. I assume there is only one step to be the committer of Apache ShardingSphere, please stay tuned!

**Comment by Liangda-w** [comment]
> Hi @Liangda-w Glad to see your persistence here, and the `Insights` page also shows your lots of contributions recently. I assume there is only one step to be the committer of Apache ShardingSphere, please stay tuned!

thank you @tristaZero 😄  I'll keep up the work!

**Pull request merged**
