### PR TITLE
Add the SQL definition ALTER SYNONYM of Oracle database

### PR DESCRIPTION
**Pull request by Liangda-w**
Relates #6480 

Changes proposed in this pull request:
- Add SQL definition of [ALTER SYNONYM](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-SYNONYM.html#GUID-C31B6804-6783-4A8C-B448-DF78E3FE6837)
- Add new test cases

Former discussion #9740

### CODE REVIEW

**Comment by tristaZero** [comment]
Nice @Liangda-w 
Hi @wgy8283335 , Could you give this PR a look?

**Review by wgy8283335 — APPROVED** [review]

**Comment by wgy8283335** [comment]
@tristaZero  I've finished the review， shall we merge this pull request?

**Comment by tristaZero** [comment]
Hi @Liangda-w ,

I saw the approval from @wgy8283335 , but unfortunately, some conflict files appear, could you have a look?
BTW, GSoC 2021 is on the student register stage now, where you can begin to consider your application, I suppose.

**Comment by Liangda-w** [comment]
Hi @tristaZero, I've resolved the conflict:) 
Thank you for the kind reminder! I'm on the way to complete my GSoC proposal and will send you for a review once I finish it😄   

@wgy8283335 Thank you for your review!

**Pull request merged**
