### PR TITLE
WIP: 10916 - added integration tests

### LINKED ISSUE #10916: Refactor SELECT_SQL_BY_ID_ACROSS_SINGLE_AND_SHARDING_TABLES_REWRITE statement with shardingsphere-integration-test
Hi community,

This issue is for #10887.

# Background

Currently `FederateStatementTest` and `FederatePrepareStatementTest` use JUNIT to test SQL statements. In order to improve test coverage and code elegance, we need to migrate the test scenarios of FederateStatementTest and FederatePrepareStatementTest to `shardingsphere-integration-test`. 

# Target

The goal of this issue is to migrate the `SELECT_SQL_BY_ID_ACROSS_SINGLE_AND_SHARDING_TABLES_REWRITE` statement to the `shardingsphere-integration-test` module. 

You can search for the `SELECT_SQL_BY_ID_ACROSS_SINGLE_AND_SHARDING_TABLES_REWRITE` keyword, and then you will find the test cases in `FederateStatementTest` and `FederatePrepareStatementTest`.

FederateStatementTest:

```java
    private static final String SELECT_SQL_BY_ID_ACROSS_SINGLE_AND_SHARDING_TABLES_REWRITE =
            "select t_order_federate.*, t_order_item_federate_sharding.* from "
                    + "t_order_federate, t_order_item_federate_sharding "
                    + "where t_order_federate.order_id = t_order_item_federate_sharding.item_id "
                    + "AND t_order_item_federate_sharding.remarks = 't_order_item_federate_sharding'";

    @Test
    public void assertQueryWithFederateInSingleAndShardingTableRewriteByExecuteQuery() throws SQLException {
        assertQueryWithFederateInSingleAndShardingTableRewrite(true);
    }
    
    @Test
    public void assertQueryWithFederateInSingleAndShardingTableRewriteByExecute() throws SQLException {
        assertQueryWithFederateInSingleAndShardingTableRewrite(false);
    }
    
    private void assertQueryWithFederateInSingleAndShardingTableRewrite(final boolean executeQuery) throws SQLException {
        ShardingSphereStatement statement = (ShardingSphereStatement) getShardingSphereDataSource().getConnection().createStatement();
        ResultSet resultSet = getResultSet(statement, SELECT_SQL_BY_ID_ACROSS_SINGLE_AND_SHARDING_TABLES_REWRITE, executeQuery);
        assertNotNull(resultSet);
        assertTrue(resultSet.next());
        assertThat(resultSet.getInt(1), is(1000));
        assertThat(resultSet.getInt(2), is(10));
        assertThat(resultSet.getString(3), is("init"));
        assertThat(resultSet.getInt(4), is(1000));
        assertThat(resultSet.getInt(5), is(10000));
        assertTrue(resultSet.next());
        assertThat(resultSet.getInt(1), is(1001));
        assertThat(resultSet.getInt(2), is(11));
        assertThat(resultSet.getString(3), is("init"));
        assertThat(resultSet.getInt(4), is(1001));
        assertThat(resultSet.getInt(5), is(10001));
        assertFalse(resultSet.next());
    }
```

FederatePrepareStatementTest:

```java
    private static final String SELECT_SQL_BY_ID_ACROSS_SINGLE_AND_SHARDING_TABLES_REWRITE =
            "select t_order_federate.*, t_order_item_federate_sharding.* "
                    + "from t_order_federate, t_order_item_federate_sharding "
                    + "where t_order_federate.order_id = t_order_item_federate_sharding.item_id "
                    + "AND t_order_item_federate_sharding.remarks = 't_order_item_federate_sharding' "
                    + "AND t_order_item_federate_sharding.user_id = ?";

    @Test
    public void assertQueryWithFederateInSingleAndShardingTableRewriteByExecuteQuery() throws SQLException {
        assertQueryWithFederateInSingleAndShardingTableRewrite(true);
    }
    
    @Test
    public void assertQueryWithFederateInSingleAndShardingTableRewriteByExecute() throws SQLException {
        assertQueryWithFederateInSingleAndShardingTableRewrite(false);
    }
    
    private void assertQueryWithFederateInSingleAndShardingTableRewrite(final boolean executeQuery) throws SQLException {
        ShardingSpherePreparedStatement preparedStatement = (ShardingSpherePreparedStatement) getShardingSphereDataSource()
                .getConnection().prepareStatement(SELECT_SQL_BY_ID_ACROSS_SINGLE_AND_SHARDING_TABLES_REWRITE);
        preparedStatement.setInt(1, 11);
        ResultSet resultSet = getResultSet(preparedStatement, executeQuery);
        assertNotNull(resultSet);
        assertTrue(resultSet.next());
        assertThat(resultSet.getInt(1), is(1001));
        assertThat(resultSet.getInt(2), is(11));
        assertThat(resultSet.getString(3), is("init"));
        assertThat(resultSet.getInt(4), is(1001));
        assertThat(resultSet.getInt(5), is(10001));
        assertFalse(resultSet.next());
        preparedStatement.setInt(1, 10);
        ResultSet resultSet1 = getResultSet(preparedStatement, executeQuery);
        assertNotNull(resultSet1);
        assertTrue(resultSet1.next());
        assertThat(resultSet1.getInt(1), is(1000));
        assertThat(resultSet1.getInt(2), is(10));
        assertThat(resultSet1.getString(3), is("init"));
        assertThat(resultSet1.getInt(4), is(1000));
        assertThat(resultSet1.getInt(5), is(10000));
        assertFalse(resultSet1.next());
    }
```

# How to
In order to finish this task, you need to understand the [documentation](https://shardingsphere.apache.org/document/current/en/features/test-engine/integration-test/) of the integration test first, and PR #10913 also provides an example, which you can refer to. BTW, if you have any questions, please leave a comment.

### PR DESCRIPTION
**Pull request by tup916**
Fixes #10916.

Changes proposed in this pull request:
- Created integration test (2x)
- TODO: remove JUNIT test.

### CODE REVIEW

**Comment by strongduanmu** [comment]
@tup916 Thank you for your efforts, the CI exception needs to be fixed.

**Comment by strongduanmu** [comment]
@tup916 The first problem is the initialization of `t_order_item_federate_sharding`. We need to initialize in the integration test according to the corresponding configuration. You can refer to `jdbc_init_federate_1.sql` for table creation operations. In addition, `t_order_item_federate_sharding` is a sharding table, you need to refer to `config-federate.yaml` to add sharding configuration.

BTW, the case of the integration test needs to be as consistent as possible with JUNIT. I found that you adjusted the fields of the `t_order_item_federate_sharding` table.

**Comment by strongduanmu** [comment]
@tup916 Integration tests need to cover these scenarios, like `db,dbtbl_with_readwrite_splitting,dbtbl_with_readwrite_splitting_and_encrypt`. You can refer to #10913 to improve the scenarios.

**Comment by tristaZero** [comment]
@tup916 Hi, welcome, could you have a look at the failed CI tests?

**Comment by strongduanmu** [comment]
Hi @tup916, any progress? If there is no reply for a long time, I will close this PR and you can submit a new ONE.

**Comment by strongduanmu** [comment]
Long time no response.

**Pull request closed without merging**
