### PR TITLE
docs: docker build error

### PR DESCRIPTION
**Pull request by totalo**
Changes proposed in this pull request:
- There are some errors in the docker help document, and I tried to fix it

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
The correct project name is `shardingsphere-proxy`.
It is unnecessary to change here.

**Comment by totalo** [comment]
> The correct project name is `shardingsphere-proxy`.
> It is unnecessary to change here.

But what the program reads is the configuration in sharding-proxy, mounted to the shardingsphere-proxy directory, the project cannot be started, please check

**Comment by terrymanu** [comment]
> > The correct project name is `shardingsphere-proxy`.
> > It is unnecessary to change here.
> 
> But what the program reads is the configuration in sharding-proxy, mounted to the shardingsphere-proxy directory, the project cannot be started, please check

It seems we need to update the docker file, is it?

**Comment by totalo** [comment]
> > > The correct project name is `shardingsphere-proxy`.
> > > It is unnecessary to change here.
> > 
> > 
> > But what the program reads is the configuration in sharding-proxy, mounted to the shardingsphere-proxy directory, the project cannot be started, please check
> 
> It seems we need to update the docker file, is it?

Yes, let me to fix it.

**Pull request closed without merging**
