### PR TITLE
Remove blank lines.

### PR DESCRIPTION
**Pull request by yx9o**
Remove blank lines.

### CODE REVIEW

**Review by menghaoranss — APPROVED** [review]

**Comment by tristaZero** [comment]
Hi @yx9o Thanks for your continuous contribution to ShardingSphere, I wonder whether you'd like to be part of this community and become our committer of Apache ShardingSphere?  ;-) [Apache commuter](https://community.apache.org/contributors/) will help you learn more.

**Comment by yx9o** [comment]
> Hi @yx9o Thanks for your continuous contribution to ShardingSphere, I wonder whether you'd like to be part of this community and become our committer of Apache ShardingSphere? ;-) [Apache committer](https://community.apache.org/contributors/) will help you learn more.

@tristaZero Thank you, I am very willing, and I will continue to make more contributions to Apache ShardingSphere.

**Comment by tristaZero** [comment]
Cool, I will initialize the voting in the community. @yx9o

**Comment by yx9o** [comment]
> Cool, I will initialize the voting in the community. @yx9o

Ok, thanks.

**Pull request merged**
