### PR TITLE
[ISSUE  #11097] remove MetaDataAwareEventSubscriber

### PR DESCRIPTION
**Pull request by lwclover**
remove MetaDataAwareEventSubscriber

### CODE REVIEW

**Comment by tristaZero** [comment]
You'd better create a new branch for this PR, since I can see many duplicate coding.

**Review by tristaZero — CHANGES_REQUESTED** [review]
You'd better create a new branch for this PR, since I can see many duplicate coding.

**Comment by lwclover** [comment]
> You'd better create a new branch for this PR, since I can see many duplicate coding.

after merging shardingsphere/matster to my master branch, File changes is displayed correctly.

**Review by tristaZero — APPROVED** [review]
@lwclover Thanks for this enhanced PR, prompt work.

**Pull request merged**
