### PR TITLE
fix for test of subquerytable

### PR DESCRIPTION
**Pull request by jingshanglu**
Ref #4887.

Changes proposed in this pull request:
- fix for test of subquerytable

### CODE REVIEW

**Comment by jingshanglu** [comment]
> /run ci

@tuohai666 CI not run.

**Comment by tuohai666** [comment]
Travis doesn't work. Can you re-create this pr?

**Comment by jingshanglu** [comment]
> Travis doesn't work. Can you re-create this pr?
ok

**Pull request closed without merging**
