### PR TITLE
Support compiling and using ShardingSphere under OpenJDK 23

### PR DESCRIPTION
**Pull request by linghengqian**
For #32927.

Changes proposed in this pull request:
  - Support compiling and using ShardingSphere under OpenJDK 23.
  - According to https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#proc , switch the value of `maven.compiler.proc`.
  - Update Maven Wrapper version. Multi-threaded deadlock problems in the Maven lifecycle often plague CI.

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [x] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [x] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Review by linghengqian — COMMENTED** [review]
- More errors surfaced.

```shell
Caused by: java.lang.ClassNotFoundException: javax.management.loading.PrivateMLet
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528)
        ... 44 more
```

**Review by linghengqian — COMMENTED** [review]
- @kanha-gupta I observed https://github.com/apache/shardingsphere/pull/24007. Why does the relevant unit test have to use the deprecated `javax.management.loading.PrivateMLet` starting from JDK20? This class was removed in JDK23.

**Review by iamhucong — APPROVED** [review]

**Comment by RaigorJiang** [comment]
Hi @linghengqian 

When I use JDK 17 to compile the master branch, this error occurs:

img_v3_02fj_c7f41f6f-ef78-4277-bd3b-8bc654ad5f0g

--- 
If I switch to JDK 21, the compilation is successful. Since the `-proc` option is specified, does it mean that JDK 21 or above must be used to compile ShardingSphere?

**Comment by linghengqian** [comment]
> If I switch to JDK 21, the compilation is successful. Since the `-proc` option is specified, does it mean that JDK 21 or above must be used to compile ShardingSphere?
> 

- I rechecked the OpenJDK Committer's blog https://inside.java/2024/06/18/quality-heads-up/ , and `-proc:full` has been backported to jdk 17.0.11, 11.0.23, 8u411. Can you print the output of `java -version`?

**Comment by RaigorJiang** [comment]
@linghengqian I used the following command to compile and compare the result of different JDKs
```shell
./mvnw clean install -B -DskipTests
```

### 1. Oracle JDK 17
image

- Compile failed
image


### 2. Zulu JDK 17
image

- Compile failed
image


### 3. Oracle JDK 21 (In Zulu JDK 21 is also successful, omitted here)
image

- Compile successful
image

**Comment by RaigorJiang** [comment]
> * I rechecked the OpenJDK Committer's blog https://inside.java/2024/06/18/quality-heads-up/ , and `-proc:full` has been backported to jdk 17.0.11, 11.0.23, 8u411. Can you print the output of `java -version`?

Maybe I need to upgrade JDK 17.0.9 to 17.0.11, I will test again.

**Comment by linghengqian** [comment]
> > * I rechecked the OpenJDK Committer's blog https://inside.java/2024/06/18/quality-heads-up/ , and `-proc:full` has been backported to jdk 17.0.11, 11.0.23, 8u411. Can you print the output of `java -version`?
> 
> After upgrading JDK from 17.0.9 to 17.0.11, there is indeed no problem anymore, thank you @linghengqian

- Maybe some contributors are using non-LTS versions lower than JDK21. Currently, the master branch can only be built with jdk8, jdk11, jdk17, and jdk21-23. I set this JVM parameter in https://github.com/apache/shardingsphere/pull/33224 to take effect only on JDK23. This will allow contributors to build shardingsphere with jdk15, jdk20, etc.

**Comment by RaigorJiang** [comment]
> > After upgrading JDK from 17.0.9 to 17.0.11, there is indeed no problem anymore, thank you @linghengqian
> 
> * Maybe some contributors are using non-LTS versions lower than JDK21. Currently, the master branch can only be built with jdk8, jdk11, jdk17, and jdk21-23. I set this JVM parameter in [Support building Example module with OpenJDK 23 #33224](https://github.com/apache/shardingsphere/pull/33224) to take effect only on JDK23. This will allow contributors to build shardingsphere with jdk15, jdk20, etc.

Great, thanks! 👍

**Pull request merged**
