### PR TITLE
Add syntax for `DROP SHARDING KEY GENERATOR`

### LINKED ISSUE #13999: Add syntax for `DROP SHARDING KEY GENERATOR`
For details, please refer to https://github.com/apache/shardingsphere/issues/13994

The ANTLR definition syntax is as follows:

```sql
DROP SHARDING KEY GENERATOR keyGeneratorName (COMMA keyGeneratorName)*;
```

Examples are as follows:

```sql
DROP SHARDING KEY GENERATOR uuid_key_generator;
```

### PR DESCRIPTION
**Pull request by Liangda-w**
Fixes #13999.

Changes proposed in this pull request:
- Add syntax for `DROP SHARDING KEY GENERATOR`
- Add corresponding test

### CODE REVIEW

**Comment by RaigorJiang** [comment]
Hi @Liangda-w 
Thanks for your PR, but there is some problems that need improvement:

1. This feature belongs to feature sharding, please put the syntax definition in the g4 file of the [shardingsphere-sharding-distsql](https://github.com/apache/shardingsphere/tree/master/shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-parser/src/main/antlr4) module
2. Please refer to [visitDropShardingAlgorithm](https://github.com/apache/shardingsphere/blob/master/shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-parser/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/core/ShardingDistSQLStatementVisitor.java) method to get `DropShardingKeyGeneratorStatement`, not simply new
3. KeyGeneratorDefinitionStatement is not applicable for DROP, please refer to [DropShardingAlgorithmStatement](https://github.com/apache/shardingsphere/blob/master/shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-statement/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/statement/DropShardingAlgorithmStatement.java)

**Comment by Liangda-w** [comment]
> Hi @Liangda-w Thanks for your PR, but there are some problems that need improvement:
> 
> 1. This feature belongs to feature sharding, please put the syntax definition in the g4 file of the [shardingsphere-sharding-distsql](https://github.com/apache/shardingsphere/tree/master/shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-parser/src/main/antlr4) module
> 2. Please refer to [visitDropShardingAlgorithm](https://github.com/apache/shardingsphere/blob/master/shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-parser/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/core/ShardingDistSQLStatementVisitor.java) method to get `DropShardingKeyGeneratorStatement`, not simply new
> 3. KeyGeneratorDefinitionStatement is not applicable for DROP, please refer to [DropShardingAlgorithmStatement](https://github.com/apache/shardingsphere/blob/master/shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql/shardingsphere-sharding-distsql-statement/src/main/java/org/apache/shardingsphere/sharding/distsql/parser/statement/DropShardingAlgorithmStatement.java)

thank you! I'll improve this PR soon:)

**Comment by RaigorJiang** [comment]
Hi @Liangda-w 
Is there any trouble, can we help?

**Comment by Liangda-w** [comment]
> Hi @Liangda-w Is there any trouble, can we help?

Hey sry for my late response, will submit a new PR:)

**Pull request closed without merging**
