### PR TITLE
#7471 resolved 

### LINKED ISSUE #7471: Simplify configuration file
Currently, shardingsphere configuration file need to repeat all tables' config, event they are using same sharding rule.
e.g.
```properties
spring.shardingsphere.sharding.tables.table1.actual-data-nodes=ds$->{0..1}.tab_user$->{0..1}
spring.shardingsphere.sharding.tables.table1.table-strategy.inline.sharding-column=id
spring.shardingsphere.sharding.tables.table1.table-strategy.inline.algorithm-expression=tab_user$->{id % 2}

spring.shardingsphere.sharding.tables.table2.actual-data-nodes=ds$->{0..1}.tab_user$->{0..1}
spring.shardingsphere.sharding.tables.table2.table-strategy.inline.sharding-column=id
spring.shardingsphere.sharding.tables.table2.table-strategy.inline.algorithm-expression=tab_user$->{id % 2}
```
in the example, table1 and table2 have exactly same sharding rule, I suggest to combine them into one group, like:
```properties
spring.shardingsphere.sharding.groups.group1.tables=table1,table2
spring.shardingsphere.sharding.groups.group1.actual-data-nodes=ds$->{0..1}.${tablename}$->{0..1}
spring.shardingsphere.sharding.groups.group1.table-strategy.inline.sharding-column=id
spring.shardingsphere.sharding.groups.group1.table-strategy.inline.algorithm-expression=${tablename}$->{id % 2}
```

### PR DESCRIPTION
**Pull request by johnny2002**
Fixes #7471 

Changes proposed in this pull request:
datasources yaml changed to:
```yaml
dataSources:
  template1:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.h2.Driver
    username: root
    password:
    maximumPoolSize: 2
    isTemplate: true #indicate this is a template, not a concrete datasource
  ds_0: 
    template: template1 #inherit properties from datasource "template1"
    jdbc-url: jdbc:h2:mem:core
    maximumPoolSize: 5 #override the value "2" from "template1"
  ds_1: 
    template: template1
    jdbc-Url: jdbc:h2:mem:core
```
-
-
-

### CODE REVIEW

**Comment by tristaZero** [comment]
Thanks for hard working, @johnny2002 It looks like a big change, please leave @kimmking some time to review. :)

**Comment by johnny2002** [comment]
@tristaZero 
Another thing is, suggestion we don't use expression like "ds_${0..1}", instead, we can use "ds_$->{0..1}", so that to avoid spring placeholder.

**Comment by tristaZero** [comment]
@johnny2002 I guess `ds_$->{0..1}` can work as well. Have you ever tried it?

**Comment by kimmking** [comment]
It seems a big issue. I will check it soon.

**Comment by kimmking** [comment]
@johnny2002 Can you change the title friendly for users?

**Comment by kimmking** [comment]
Hello, @johnny2002  thanks a lot for contribution.
As a team discussion for configuration design,  common configured parameters will be removed from current version.
So, we need close this pr instead of merging it. Maybe someday we relaunch the common configration and template functionalities in our ecosystem projects.
But now let's move on.

**Comment by johnny2002** [comment]
> @johnny2002 I guess `ds_$->{0..1}` can work as well. Have you ever tried it?

@tristaZero  YES, ds_$->{0..1} does work. 
While I think we shall NOT support ds_${0..1}, I found in our source code, in order to support "ds_${0..1}", we have to change StandardEnvironment.ignoreUnresolvableNestedPlaceholders to true. This is not a good practice, since it will affect the whole application.

**Comment by johnny2002** [comment]
> Hello, @johnny2002 thanks a lot for contribution.
> As a team discussion for configuration design, common configured parameters will be removed from current version.
> So, we need close this pr instead of merging it. Maybe someday we relaunch the common configration and template functionalities in our ecosystem projects.
> But now let's move on.

Understand, hope to contribute for the project in the future.

**Comment by johnny2002** [comment]
> Hello, @johnny2002 thanks a lot for contribution.
> As a team discussion for configuration design, common configured parameters will be removed from current version.
> So, we need close this pr instead of merging it. Maybe someday we relaunch the common configration and template functionalities in our ecosystem projects.
> But now let's move on.
@kimmking One more thing I wanna remind you is that, the new template style datasource configuration also compatible with no template style. e.g.  both the following styles are compatible.
``` yaml
dataSources:
  template1:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.h2.Driver
    username: root
    password:
    maximumPoolSize: 2
    isTemplate: true #indicate this is a template, not a concrete datasource
  ds_0: 
    template: template1 #inherit properties from datasource "template1"
    jdbc-url: jdbc:h2:mem:core
    maximumPoolSize: 5 #override the value "2" from "template1"
  ds_1: 
    template: template1
    jdbc-Url: jdbc:h2:mem:core
```
or 
```yaml
dataSources:
   ds_0:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.h2.Driver
    username: root
    password:
    maximumPoolSize: 2
    jdbc-url: jdbc:h2:mem:core
    maximumPoolSize: 5 #override the value "2" from "template1"
  ds_1: 
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.h2.Driver
    username: root
    password:
    maximumPoolSize: 2
    jdbc-Url: jdbc:h2:mem:core
```

**Comment by kimmking** [comment]
Thanks for reminding me.

**Pull request closed without merging**
