### PR TITLE
Optimized aes encryption implementation

### PR DESCRIPTION
**Pull request by klboke**
Changes proposed in this pull request:
1、Modified the implementation of AESEncryptor, moved the instantiation and initialization of AES encryption and decryption to init, without having to initialize it every time

### CODE REVIEW

**Comment by yu199195** [comment]
@klboke hi，you pr changed a few lines that you did not change ，you can not format  this code，blank line may be 4 characters

**Comment by tristaZero** [comment]
Hi @klbokkl, thanks for your first contribution to ShardingSphere community, welcome! :)
I reviewed your PR, and it looks great to avoid initializing encryptor repeatedly. However, like @yu199195 said, checking style is required, since your code is public to anyone all over the world.

**Comment by kezhenxu94** [comment]
The code style "keep indentation in blank lines" is a little bit unfriendly for new-comers (like me, at https://github.com/apache/shardingsphere/pull/5634#discussion_r426106879) because the IDE always remove them by default, but if you could export the code style configuration that respects to the project's standard, it should avoid many code style violations in PRs 😅

**Comment by klboke** [comment]
I have noticed the problem of formatting IDEA code, I will resubmit it after modification

**Comment by klboke** [comment]
I found that I have to mention pr again to solve the problem of code formatting, right? The code format verification problem has actually been fixed

**Pull request closed without merging**
