### PR TITLE
Add unit test for GlobalLockNode.generateSchemaLockName in GlobalLock…

### LINKED ISSUE #16391: GlobalLockNode.generateSchemaLockName(final String schema, final String instanceId) add unit test
Please add unit test in class `GlobalLockNodeTest`

### PR DESCRIPTION
**Pull request by ntsompa**
…NodeTest class

Fixes #16391.

### CODE REVIEW

**Comment by ntsompa** [comment]
Hello, what do i need to do now, in order for my commit to be merged? Thank you.

**Comment by totalo** [comment]
> Hello, what do i need to do now, in order for my commit to be merged? Thank you.

hi @ntsompa , Thanks for your nice work, we need to wait for ci to pass and we can merge.

**Review by zjcnb — APPROVED** [review]

**Comment by zjcnb** [comment]
> Hello, what do i need to do now, in order for my commit to be merged? Thank you.

It has conflicts, Resolve it please.

**Comment by ntsompa** [comment]
@zjcnb I think i resolved the conflict. Thank you.

**Review by zjcnb — APPROVED** [review]

**Pull request merged**
