### PR TITLE
add ut sharding-sphere-agent-core

### LINKED ISSUE #11156: Add unit test for shardingsphere-agent-core
Hi community,

This issue is for #10887.

## Aim
Add unit test for shardingsphere-agent-core project to test its public functions.

## Basic Qualifications
- Java  
- Maven  
- Junit.Test

## Classes
Add unit test for classes to test its public functions.

- [x] ComposeClassStaticMethodAroundAdvice
- [x] ComposeConstructorAdvice

## Examples FYI
- ShardingSphereTransformerTest

### PR DESCRIPTION
**Pull request by Swastyy**
Fixes #11156 

Changes proposed in this pull request:
Added test functions for:
-ComposeClassStaticMethodAroundAdvice
-ComposeConstructorAdvice
-AgentServiceProviderNotFoundException

### CODE REVIEW

**Comment by Swastyy** [comment]
@tristaZero @strongduanmu Its taking time for me to fix these(more than 3 hours in this issue 😕 ). Will we be able to contribute after OSD?

**Comment by strongduanmu** [comment]
> @tristaZero @strongduanmu Its taking time for me to fix these(more than 3 hours in this issue 😕 ). Will we be able to contribute after OSD?

@Swastyy Of course. In addition, CI has an exception, you can execute `mvn clean install` locally to verify that CI is passed.

**Comment by strongduanmu** [comment]
@Swastyy You can refer [code-conduct](https://shardingsphere.apache.org/community/en/contribute/code-conduct/) to fix the checkstyle.

**Comment by strongduanmu** [comment]
@Swastyy Any progress?

**Comment by Swastyy** [comment]
@strongduanmu The Travis CI logs were showing the unused plugins as redundant so I removed them and build is still failing. See the error log I cannot debug it.
image

**Comment by tristaZero** [comment]
@Swastyy Hi, the log shows me it is about check-style. [Contributor Covenant Submitting of Conduct](https://shardingsphere.apache.org/community/en/contribute/code-conduct/) will give you some hints.

**Comment by tristaZero** [comment]
Hi @Swastyy Do you need any help?

**Comment by strongduanmu** [comment]
Hi @Swastyy, any progress?

**Comment by Swastyy** [comment]
> Hi @Swastyy, any progress?

@strongduanmu I will reopen this PR again after completing.

**Comment by strongduanmu** [comment]
@Swastyy Looking forward to your PR.

**Pull request closed without merging**
