### PR TITLE
support load partitioned table

### PR DESCRIPTION
**Pull request by shijie-328931589**
Fixes #ISSUSE_ID.

Changes proposed in this pull request:
  -

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Review by 328931589 — COMMENTED** [review]
LGTM

**Comment by strongduanmu** [comment]
@shijie-328931589 Can you submit an issue to describe the feature request?

**Comment by shijie-328931589** [comment]
> @shijie-328931589 Can you submit an issue to describe the feature request?

In using postgresql partitioned table , if  i use partitioned table as single table, will appear table or view not exist; if  use partitioned table as sharding table, and the line expression is same with partitioned table name, it can normal work. Is this expected？

**Comment by strongduanmu** [comment]
Since this issue is not clearly described, I will close this PR. You are welcome to submit a more detailed issue description first, and then contribute to the PR.

**Pull request closed without merging**
