### PR TITLE
Fix maven version number display

### PR DESCRIPTION
**Pull request by acmenlt**
Changes proposed in this pull request:
- Fix maven version number display.

original:
image

now:
image

remark: The readme file only changed one line. I don't know why the whole file changed.

### CODE REVIEW

**Comment by TeslaCN** [comment]
Maybe the CRLF changed?

**Comment by acmenlt** [comment]
> Maybe the CRLF changed?

@TeslaCN Do you mean the reason why the icon is invalid, Or has readme been completely changed

**Comment by TeslaCN** [comment]
> > Maybe the CRLF changed?
> 
> @TeslaCN Do you mean the reason why the icon is invalid, Or has readme been completely changed

Readme changed.

**Comment by acmenlt** [comment]
@TeslaCN Sorry, I don't know why. If there is a solution, I can resubmit it

**Comment by acmenlt** [comment]
@TeslaCN I tried to restore to the original version and modify only one line of data, but I still couldn't

**Comment by terrymanu** [comment]
Could you submit a new PR to handle CRLF issue?

**Pull request closed without merging**
