### PR TITLE
Support parsing SQL Server SELECT TRIM

### LINKED ISSUE #29162: Support parsing SQL Server SELECT TRIM( sql
# Background
Hi community.
This issue is for #29149.

The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for `SQL Server` SQL parsing in ShardingSphere.

More details:
https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/

# Task
This issue is to support more `SQL Server` sql parsing, as follows:
```sql
SELECT TRIM( '.,! ' FROM '     #     test    .') AS Result
```
[link](https://learn.microsoft.com/zh-cn/sql/t-sql/functions/trim-transact-sql?view=sql-server-ver16)

```sql
SELECT TRIM(LEADING '.,! ' FROM  '     .#     test    .') AS Result
```
[link](https://learn.microsoft.com/zh-cn/sql/t-sql/functions/trim-transact-sql?view=sql-server-ver16)

```sql
SELECT TRIM(TRAILING '.,! ' FROM '     .#     test    .') AS Result
```
[link](https://learn.microsoft.com/zh-cn/sql/t-sql/functions/trim-transact-sql?view=sql-server-ver16)

```sql
SELECT TRIM(BOTH '123' FROM '123abc123') AS Result
```
[link](https://learn.microsoft.com/zh-cn/sql/t-sql/functions/trim-transact-sql?view=sql-server-ver16)

```sql
INSERT INTO [HR].[Employees]
        ([SSN]
        ,[FirstName]
        ,[LastName]
        ,[Salary])
    VALUES
        ('795-73-9838'
        , N'Catherine'
        , N'Abel'
        , $31692)
```
[link](https://learn.microsoft.com/zh-cn/azure/azure-sql/database/always-encrypted-enclaves-getting-started-vbs?view=azuresql)

# Process
1. First confirm that this is a correct `SQL Server` sql syntax, if not please leave a message under the issue and ignore it;
2. Compare SQL definitions in Official SQL Doc and ShardingSphere SQL Doc;
3. If there is any difference in ShardingSphere SQL Doc, please correct them by referring to the Official SQL Doc;
4. Run mvn install the current_file_module;
5. Check whether there are any exceptions. If indeed, please fix them. (Especially xxxVisitor.class);
6. Add new corresponding SQL case in SQL Cases and expected parsed result in Expected Statement XML;
7. Run SQLParserParameterizedTest to make sure no exceptions.

# Relevant Skills
1. Master JAVA language
2. Have a basic understanding of Antlr `g4` file
3. Be familiar with `SQL Server` SQLs

### PR DESCRIPTION
**Pull request by zzzk1**
Fixes #29162.

Changes proposed in this pull request:
  -
Task
---
This issue is to support more SQL Server sql parsing, as follows:
``` sql
SELECT TRIM( '.,! ' FROM '     #     test    .') AS Result
```
``` sql
SELECT TRIM(LEADING '.,! ' FROM  '     .#     test    .') AS Result
```
``` sql
SELECT TRIM(TRAILING '.,! ' FROM '     .#     test    .') AS Result
```
``` sql
SELECT TRIM(BOTH '123' FROM '123abc123') AS Result
```

Before committing this PR, I'm sure that I have checked the following options:
- [ ] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [ ] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [ ] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Comment by strongduanmu** [comment]
Hi @zzzk1, thank you for your contribution. Please solve ci exception on your local machine.

**Comment by zzzk1** [comment]
@strongduanmu pls take a look

**Comment by strongduanmu** [comment]
Hi @zzzk1, thank you for your contribution. I leave some comment, please take a look.

**Review by strongduanmu — APPROVED** [review]
Thank you for your contribution, merged.

**Comment by strongduanmu** [comment]
Hi @zzzk1, can you take a look at https://github.com/apache/shardingsphere/pull/30270, I made some minor optimizations.
You can get this code conduct from doc - https://shardingsphere.apache.org/community/cn/involved/conduct/code/#g4-%E8%A7%84%E8%8C%83.

**Comment by zzzk1** [comment]
> Hi @zzzk1, can you take a look at #30270, I made some minor optimizations. You can get this code conduct from doc - [shardingsphere.apache.org/community/cn/involved/conduct/code/#g4-%E8%A7%84%E8%8C%83](https://shardingsphere.apache.org/community/cn/involved/conduct/code/#g4-%E8%A7%84%E8%8C%83).

sorry about that i will be prudently next

**Pull request merged**
