### PR TITLE
Update sql-error-code.cn.md

### PR DESCRIPTION
**Pull request by lhyundeadsoul**
Fixes https://github.com/apache/shardingsphere/pull/20677#discussion_r959520117

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
The document is already existed in `11000`

**Comment by lhyundeadsoul** [comment]
> The document already existed in `11000`

Yes, it already existed. But according to [this comment](https://github.com/apache/shardingsphere/pull/20677#discussion_r959520117) there is a new little clip `error message: %s` which contains the more detailed error message. 

So, please let me know which one fits the code of conduct better.

1. 
| 42000 | 11000 | You have an error in your SQL syntax: \`%s\ |
| 42000 | 11004 | You have an error in your SQL syntax: \`%s\`, error message: \`%s\` |

2. 
| 42000 | 11000 | You have an error in your SQL syntax: \`%s\ |
| 42000 | 11000 | You have an error in your SQL syntax: \`%s\`, error message: \`%s\` |

3.
change 
| 42000 | 11000 | You have an error in your SQL syntax: \`%s\ |
to
| 42000 | 11000 | You have an error in your SQL syntax: \`%s\`, error message: \`%s\` |

**Comment by terrymanu** [comment]
One exception should only have one vender code

**Comment by lhyundeadsoul** [comment]
> One exception should only have one vender code
Copy.
So `org.apache.shardingsphere.sql.parser.exception.SQLParsingException` 's vendor code is always 11000.

Doc update:
change
| 42000 | 11000 | You have an error in your SQL syntax: `%s\ |
to
| 42000 | 11000 | You have an error in your SQL syntax: `%s`, error message: `%s` |

**Comment by terrymanu** [comment]
> > One exception should only have one vender code
> 
> Copy. So `org.apache.shardingsphere.sql.parser.exception.SQLParsingException` 's vendor code is always 11000.
> 
> Doc update: change | 42000 | 11000 | You have an error in your SQL syntax: `%s` | to | 42000 | 11000 | You have an error in your SQL syntax: `%s`, error message: `%s` |
> 
> Am I right?

Unfortunately no, one exception only has one error message, please split different message into two exceptions

**Comment by terrymanu** [comment]
> > One exception should only have one vender code
> 
> Copy. So `org.apache.shardingsphere.sql.parser.exception.SQLParsingException` 's vendor code is always 11000.
> 
> Doc update: change | 42000 | 11000 | You have an error in your SQL syntax: `%s` | to | 42000 | 11000 | You have an error in your SQL syntax: `%s`, error message: `%s` |
> 
> Am I right?

Unfortunately no, one exception only has one error message, please split different message into two exceptions

**Comment by terrymanu** [comment]
If no update, I just close this issue

**Pull request closed without merging**
