### PR TITLE
#11397 fix bug of wrong route result

### LINKED ISSUE #11397: route result is wrong
I execute a SQL like this : "select * from demo_db where num=1 or num=2 and count=3"，
I config 2 dataSources : ds_0 and ds_1
table strategy : tb_${num % 2}，
database strategy : ds_${count % 2}
but route result only contains ds_1，following is actual SQL:
Actual SQL: ds_1 ::: select * from tb_1 where num = 1 or num=2 and count =3
Actual SQL: ds_1 ::: select * from tb_0 where num = 1 or num=2 and count =3
Version : 4.1.0

### PR DESCRIPTION
**Pull request by vince7839**
Fixes #11397.

Changes proposed in this pull request:
-Fix bug of wrong route result when OR condition before AND condition.
-Add route test case.
-Add rewrite test case.

### CODE REVIEW

**Comment by vince7839** [comment]
@strongduanmu Hi,I've add rewrite test case,have a look please.

**Comment by strongduanmu** [comment]
> @strongduanmu Hi,I've add rewrite test case,have a look please.

@vince7839 Good job, i will review this pr.

**Comment by strongduanmu** [comment]
Hi @vince7839 , ci is fail, can you fix it first?

**Comment by vince7839** [comment]
> Hi @vince7839 , ci is fail, can you fix it first?
@strongduanmu Hi, It doesn't seem to be caused by this PR

**Comment by tristaZero** [comment]
@vince7839 Hi, thanks. I just approve the CI to run your PR. Let's wait for the result. Have a good day.

**Comment by vince7839** [comment]
> @vince7839 Hi, thanks. I just approve the CI to run your PR. Let's wait for the result. Have a good day.

Ok,thanks

**Comment by vince7839** [comment]
@tristaZero  Hi,CI always failed for "Unable to resolve address: zk:2181",can you give me some advice to solve it?thanks!

**Comment by vince7839** [comment]
@tristaZero Hi,please approve CI runs,thanks : )

**Comment by vince7839** [comment]
@strongduanmu Hi,please approve CI run,thanks

**Comment by strongduanmu** [comment]
> @strongduanmu Hi,please approve CI run,thanks

@vince7839 Thank you for your effort. Let us wait for the result of ci execution.

**Review by strongduanmu — APPROVED** [review]

**Pull request merged**
