### PR TITLE
fix mysql blob type field can be empty (#20243)

### LINKED ISSUE #20243: [SQL Parser] Support blob type with content of x''
### Which version of ShardingSphere did you use?
master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Support blob type with content of x''

### PR DESCRIPTION
**Pull request by mingyifei**
Fixes #20243.

Changes proposed in this pull request:
- Modify syntax parsing of MySQL BLOB field.
-
-

### CODE REVIEW

**Comment by TeslaCN** [comment]
Hi @mingyifei Please merge master into your branch.

**Comment by mingyifei** [comment]
> Hi @mingyifei Please merge master into your branch.

ok.

**Review by strongduanmu — CHANGES_REQUESTED** [review]
Can you add sql parse test case to cover this new logic?

**Comment by mingyifei** [comment]
> Can you add sql parse test case to cover this new logic?

ok.

**Review by strongduanmu — APPROVED** [review]

**Pull request merged**
