### PR TITLE
Issue#9758

### PR DESCRIPTION
**Pull request by huanghao495430759**
Fixes Issue#9758.
- doc error of read-write-splitting configurations.

### CODE REVIEW

**Comment by tristaZero** [comment]
Hi @huanghao495430759 
Thanks for your issue and PR

@yu199195  @strongduanmu Hi could you give it a review?

**Comment by yu199195** [comment]
can merged

**Comment by yu199195** [comment]
@tristaZero Trouble you merged

**Review by tristaZero — APPROVED** [review]
Thanks @huanghao495430759 , nice.
Thanks for your review. @yu199195

**Pull request merged**
