### PR TITLE
Support Nacos authentication

### LINKED ISSUE #26437: The cluster mode is Nacos, can it support authentication?
## Feature Request

**For English only**, other languages will not be accepted.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Describe the feature you would like.

In module shardingsphere-cluster-mode-repository-nacos, the method org.apache.shardingsphere.mode.repository.cluster.nacos.NacosRepository.createClient(final ClusterPersistRepositoryConfiguration config) create NamingService instance，but no parameters for username and password, If Nacos needs to log in, an error will be reported.

### PR DESCRIPTION
**Pull request by zihaoAK47**
Fixes #26437.

Changes proposed in this pull request:
  - Support Nacos authentication
  - Add test

---

Before committing this PR, I'm sure that I have checked the following options:
- [ ✓] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [ ✓] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [ ✓] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ✓] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Comment by zihaoAK47** [comment]
@zhaojinchao95 Hi mentor, can you take a look at this PR? If there are any issues, I will modify it. Thank you very much

**Comment by zhaojinchao95** [comment]
> @zhaojinchao95 Hi mentor, can you take a look at this PR? If there are any issues, I will modify it. Thank you very much

Thx, i will review it

**Comment by zhaojinchao95** [comment]
@zihaoAK47 Hi, can you pull master to rerun this pull request?

**Comment by zihaoAK47** [comment]
> @zihaoAK47 Hi, can you pull master to rerun this pull request?

Done

**Review by zhaojinchao95 — APPROVED** [review]

**Pull request merged**
