### PR TITLE
Update the sub class ShardingCTLShowBackendHandler of TextProtocolBackendHandler 

### LINKED ISSUE #8241: Update the sub classes of TextProtocolBackendHandler
As method getRowData in TextProtocolBackendHandler has been modified, return type from list to collection.
Before:
```
public List<Object> getRowData();
```
After:
```
public Collection<Object> getRowData();
```

But all sub classes have not updated to Collection type as follow:

- [x] 1.BroadcastBackendHandler
- [x] 2.QueryBackendHandler
- [x] 3.RDLBackendHandler
- [x] 4.ShardingCTLExplainBackendHandler
- [x] 5.ShardingCTLHintBackendHandler
- [x] 6.ShardingCTLSetBackendHandler
- [x] 7.ShardingCTLShowBackendHandler
- [x] 8.ShowDatabasesBackendHandler
- [x] 9.ShowTablesBackendHandler
- [x] 10.SkipBackendHandler
- [x] 11.TransactionBackendHandler
- [x] 12.UnicastBackendHandler
- [x] 13.UseDatabaseBackendHandler

You should pick up one and 
1. modify getRowData return type to Collection<Object>
2. remove useless imports
3. mvn clean package to ensure all test work well
4. submit a pr to this repo with a certain title: Update the sub class[your update class name here] of TextProtocolBackendHandler

buddies, good luck and move on.

It's the result:
```

1. @sydgeek           1
2. @Duelist-Fiora   2
3. @zenglinhui       3
4. @abysscat-yj     4
5. @guojia1698      5
6. @Jlif                     6
7. @sharpzhango   7
8. @plutokaito        8
9. @zhangwei1989 9
10. @lxl910128       10
11. @cutieagain       11
12. @sciatta              12
13. @Wincher           13

```

### PR DESCRIPTION
**Pull request by sharpzhango**
For #8241 .

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
Can you fix the compile error?

**Comment by sharpzhango** [comment]
> Can you fix the compile error?

I didn't modify pom.xml, why did it go wrong?

**Comment by terrymanu** [comment]
Compile error, can you execute `mvn install` in your local env and debug it first?

**Comment by sharpzhango** [comment]
ok，I will try

**Review by terrymanu — APPROVED** [review]

**Pull request merged**
