### PR TITLE
center the images on the overview page.

### LINKED ISSUE #12572: Center the images on the overview page of the official document
image

### PR DESCRIPTION
**Pull request by ThanoshanMV**
Fixes #12572

Hi @menghaoranss, I've aligned images to the center. Please check it.

Changes proposed in this pull request:
- Center the images on the overview page.

These are the screenshots I've taken after aligned the the below five images:

Roadmap
ShardingSphere Hybrid Architecture
ShardingSphere-JDBC Architecture
ShardingSphere-Proxy Archit
![Overview
ecture](https://user-images.githubusercontent.com/48581379/133890551-30713b7d-1149-433b-ab82-ade2df284a11.png)

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
HTML is hard to understand, it is better to just use md.
The reason of the picture not in center because of the picture is too "narrow".
Can we consider about put the registry center from top of the picture to right of it?
Please feel free to modify the picture with `draw.io`

**Comment by ThanoshanMV** [comment]
I moved the RegisterCenter to the right of the image:

shardingsphere-jdbc_v2

Please let me know what do you think.

**Comment by tristaZero** [comment]
Hey @ThanoshanMV , how are you doing? 👋 
I am curious whether you are interested in proofreading [SQLServer](#6478)?
Since you have been familiar with ANTLR, I presume you're the best one for that issue. But if you want to try others, I can find something new for you.

**Comment by ThanoshanMV** [comment]
Hi @tristaZero 😃 I'll start participating in #6478.

**Comment by terrymanu** [comment]
I can merge it, and let UED partner  to adjust it.

**Review by terrymanu — APPROVED** [review]

**Comment by ThanoshanMV** [comment]
Sure, thank you.

**Pull request merged**
