### PR TITLE
support MySQLComQuery Blob

### LINKED ISSUE #21627: sharding-proxy insert blob size is not correct
### Which version of ShardingSphere did you use?

1. apache-shardingsphere-5.0.0-shardingsphere-proxy-bin
2. apache-shardingsphere-5.2.0-shardingsphere-proxy-bin

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Behavior

image

above it, `id==1` insert by proxy  and `id==2` insert by direct，maybe you think this tool(dbeaver) not support fine, i read this record and write to file，record（`id==1` ）open fail

### Reason analyze (If you can)

config(seriver.yml) show sql, can see `insert into blob_clob(id,b_blob,c_clob) values(1,_binary'......','........')`，maybe get sql from packet ？

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

* **config-shadow.yml**
```yml
#....
######################################################################################################
#
# If you want to connect to MySQL, you should manually copy MySQL driver to lib directory.
#
######################################################################################################
#
databaseName: shadow_db
#
dataSources:
  ds:
    url: jdbc:mysql://192.168.1.253:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: test
    password: test
#    connectionTimeoutMilliseconds: 30000
#    idleTimeoutMilliseconds: 60000
#    maxLifetimeMilliseconds: 1800000
#    maxPoolSize: 50
#    minPoolSize: 1
#...
```
* **server.yml**
```yml
#...
#mode:
#  type: Cluster
#  repository:
#    type: ZooKeeper
#    props:
#      namespace: governance_ds
#      server-lists: localhost:2181
#      retryIntervalMilliseconds: 500
#      timeToLiveSeconds: 60
#      maxRetries: 3
#      operationTimeoutMilliseconds: 500
#  overwrite: false
#
rules:
  - !AUTHORITY
    users:
      - root@%:root
      - sharding@:sharding
    provider:
      type: ALL_PERMITTED
  - !TRANSACTION
    defaultType: XA
    providerType: Atomikos
  - !SQL_PARSER
    sqlCommentParseEnabled: true
    sqlStatementCache:
      initialCapacity: 2000
      maximumSize: 65535
    parseTreeCache:
      initialCapacity: 128
      maximumSize: 1024

props:
#  max-connections-size-per-query: 1
#  kernel-executor-size: 16  # Infinite by default.
#  proxy-frontend-flush-threshold: 128  # The default value is 128.
#  proxy-hint-enabled: false
  sql-show: true
#  check-table-metadata-enabled: false
#...
```
* **${shardingsphere-proxy}/bin/start.sh**
### Example codes for reproduce this issue (such as a github link).
```java
public class BlobClobTest {

    private String url;
    private Properties properties;

    public static void main(String[] args) throws Exception {
        BlobClobTest test = new BlobClobTest();
        test.setUp();
//        test.createTable();
        test.writeStream();
    }

    public void setUp() throws ClassNotFoundException {
        Class.forName("com.mysql.cj.jdbc.Driver");
        url = "jdbc:mysql://localhost:3307/shadow_db?useUnicode=true&characterEncoding=UTF-8";
        properties = new Properties();
        properties.put("user", "root");
        properties.put("password", "root");
    }

    public void createTable() {
        String sql = "CREATE TABLE `blob_clob` (\n" +
                "  `id` int(11) DEFAULT NULL,\n" +
                "  `b_blob` mediumblob,\n" +
                "  `c_clob` mediumtext\n" +
                ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;"; //mysql
        try (Connection conn = DriverManager.getConnection(url, properties);
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            System.out.println(stmt.executeUpdate());
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void writeStream() {
        String sql = "insert into blob_clob(id,b_blob,c_clob) values(?,?,?)";
        try (Connection conn = DriverManager.getConnection(url, properties);
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setInt(1, 1);
            stmt.setBlob(2,
                    Files.newInputStream(Paths.get(System.getProperty("user.home"), "test", "test.png")));
            stmt.setClob(3,
                    Files.newBufferedReader(Paths.get(System.getProperty("user.home"), "test", "test.txt")));
            System.out.println(stmt.executeUpdate());
        } catch (SQLException | IOException e) {
            e.printStackTrace();
        }
    }

}
```

### PR DESCRIPTION
**Pull request by yoloz**
Fixes #21627 #3024 #21518.

Changes proposed in this pull request:
  - revert stream bytes;
  - position of blob are replaced by parameter;

---

Before committing this PR, I'm sure that I have checked the following options:
- [ x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [ x] I have self-reviewed the commit code.
- [ x] I have (or in comment I request) added corresponding labels for the pull request.
- [ x] I have passed maven check locally : `mvn clean install -B -T2C -DskipTests -Dmaven.javadoc.skip=true -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Review by TeslaCN — CHANGES_REQUESTED** [review]
Hi @yoloz 
ShardingSphere-Proxy didn't set `CLIENT_QUERY_ATTRIBUTES`, so there is only a SQL in COM_QUERY packet. Could you describe your logic?

image

https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_com_query.html

**Comment by yoloz** [comment]
Hi @TeslaCN 
java-connector will append blob(stream) and bytes  in sql to send, which you can see [https://github.com/mysql/mysql-connector-j/blob/release/8.0/src/main/user-impl/java/com/mysql/cj/jdbc/ClientPreparedStatement.java](https://github.com/mysql/mysql-connector-j/blob/release/8.0/src/main/user-impl/java/com/mysql/cj/jdbc/ClientPreparedStatement.java) 1047行：
` Message sendPacket = ((PreparedQuery<?>) this.query).fillSendPacket(bindings);`
```java
 for (int i = 0; i < bindValues.length; i++) {
                bindings.checkParameterSet(i);

                sendPacket.writeBytes(StringLengthDataType.STRING_FIXED, staticSqlStrings[i]);

                if (bindValues[i].isStream()) {
                    streamToBytes(sendPacket, bindValues[i].getStreamValue(), true, bindValues[i].getStreamLength(), useStreamLengths);
                } else {
                    sendPacket.writeBytes(StringLengthDataType.STRING_FIXED, bindValues[i].getByteValue());
                }
            }
```
if use hex, begin with `x`, default `type bytes` use this, while no other set , `type blob` default use escape ,begin with `_binary` and:
* `0` to `\0` , can see ascii ;
* `\` and "`"  to double;

**Comment by TeslaCN** [comment]
If this is a SQL, we should send it directly instead of extracting values from it. Maybe what we need to figure out is why the SQL cannot be sent to database directly.

**Comment by yoloz** [comment]
> If this is a SQL, we should send it directly instead of extracting values from it. Maybe we need to figure out why the SQL cannot be sent to database directly.

yeah, i think direct read by packet.charset to string will lost some thing

**Comment by TeslaCN** [comment]
> > If this is a SQL, we should send it directly instead of extracting values from it. Maybe we need to figure out why the SQL cannot be sent to database directly.
> 
> yeah, i think direct read by packet.charset to string will lost some thing, also i found from `mysql server`, limit by my poor `c` and time ,no more thing get

You may try enabling `sql-show` and check whether the SQL is rewrote correctly. We have met some issues about blob before. Such as https://github.com/apache/shardingsphere/issues/17892

**Comment by yoloz** [comment]
> > > If this is a SQL, we should send it directly instead of extracting values from it. Maybe we need to figure out why the SQL cannot be sent to database directly.
> > 
> > 
> > yeah, i think direct read by packet.charset to string will lost some thing, also i found from `mysql server`, limit by my poor `c` and time ,no more thing get
> 
> You may try enabling `sql-show` and check whether the SQL is rewrote correctly. We have met some issues about blob before. Such as #17892

ok, i try it again, at #21922  i have checked sql

**Comment by TeslaCN** [comment]
We need to figure out the root cause of blob problem. I'm closing this for now.

**Comment by yoloz** [comment]
> We need to figure out the root cause of blob problem. I'm closing this for now.

👌

**Pull request closed without merging**
