### PR TITLE
Update ConnectionTransactionTest.java

### LINKED ISSUE #12889: Add test cases for ConnectionTransaction

### PR DESCRIPTION
**Pull request by zzs52**
Add test cases for ConnectionTransaction
Fixes #12889

Changes proposed in this pull request:

- Test cases added for ConnectionTransaction

### CODE REVIEW

**Comment by tristaZero** [comment]
Welcome here @zzs52 , could you look at conflicting files?

**Comment by terrymanu** [comment]
Please fix CI

**Comment by zzs52** [comment]
> Please fix CI

**Comment by terrymanu** [comment]
Hi, the CI still failed

**Comment by menghaoranss** [comment]
@zzs52 please fix the requested changes and ci errors ASAP to ensure that your commits will be merged into the upcoming release

**Comment by zzs52** [comment]
> @zzs52 please fix the requested changes and ci errors ASAP to ensure that your commits will be merged into the upcoming release

Ok,I will do it as soon as possible.

**Comment by menghaoranss** [comment]
@zzs52 there's no files changed

**Comment by zzs52** [comment]
> @zzs52 there's no files changed

Okay, I know

**Review by terrymanu — APPROVED** [review]

**Pull request merged**
