### PR TITLE
Add config change history of ShardingSphere-Proxy

### LINKED ISSUE #10990: [Doc] add configuration change history of ShardingSphere-Proxy. (English)
Hi community,

This issue is for [#10887](https://github.com/apache/shardingsphere/issues/10887).

### Background

Refor to #10972

### Aim

add  configuration change history of ShardingSphere-Proxy (English version). 

### How to

1. Add  `7.2.2.ShardingSphere-Proxy` in the `7.2.API Change History` directory;
2. create file `_index.en.md` and write the configuration change history of proxy's `server.yaml`.

### Reference

- [Apache ShardingSphere website](https://shardingsphere.apache.org/)

- [ShardingSphere-Proxy Configuration Manual](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/configuration/)

### PR DESCRIPTION
**Pull request by Swastyy**
Fixes #10990 

Changes proposed in this pull request:
- Created ShardingSphere-Proxy folder inside API-change-history
- Updated the `_index.en.md` file

### CODE REVIEW

**Comment by Swastyy** [comment]
@tristaZero @strongduanmu @RaigorJiang Pl review this PR.

**Comment by RaigorJiang** [comment]
Hi @Swastyy 
Thanks for your hard work!
I think there may be some misunderstandings. ShargingSphere-Proxy has a configuration file `server.yaml`, which is not exist in `ShardingSphere-JDBC`.
The configuration in `server.yaml` changes in different versions, so this record of change history is needed.
For example: 
the structure of authority configuratio has changed by #10297, you can refer to the git history of the file [server.yaml](https://github.com/apache/shardingsphere/blob/master/shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/resources/conf/server.yaml) .

**Comment by Swastyy** [comment]
> Hi @Swastyy
> Thanks for your hard work!
> I think there may be some misunderstandings. ShargingSphere-Proxy has a configuration file `server.yaml`, which is not exist in `ShardingSphere-JDBC`.
> The configuration in `server.yaml` changes in different versions, so this record of change history is needed.
> For example:
> the structure of authority configuratio has changed by #10297, you can refer to the git history of the file [server.yaml](https://github.com/apache/shardingsphere/blob/master/shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/resources/conf/server.yaml) .

Hey, I have a doubt like changement of authority configuration is not what we want right? We want to store the changes of `server.yaml` so putting the users sections inside the authority in `server.yaml` file is not we will do. I mean we won't make any change in the above file right?

**Comment by RaigorJiang** [comment]
> > Hi @Swastyy
> > Thanks for your hard work!
> > I think there may be some misunderstandings. ShargingSphere-Proxy has a configuration file `server.yaml`, which is not exist in `ShardingSphere-JDBC`.
> > The configuration in `server.yaml` changes in different versions, so this record of change history is needed.
> > For example:
> > the structure of authority configuratio has changed by #10297, you can refer to the git history of the file [server.yaml](https://github.com/apache/shardingsphere/blob/master/shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/resources/conf/server.yaml) .
> 
> Hey, I have a doubt like changement of authority configuration is not what we want right? We want to store the changes of `server.yaml` so putting the users sections inside the authority in `server.yaml` file is not we will do. I mean we won't make any change in the above file right?

I'm sorry I didn't understand what you mean. What we need to do now is to add a change history, so have you read the git history? This file has indeed been updated many times, with new and changed parameters.

**Comment by RaigorJiang** [comment]
`authority` is just a change in server.yaml, we need to record this update so that users know how to modify the configuration when upgrading the version.

**Comment by Swastyy** [comment]
> `authority` is just a change in server.yaml, we need to record this update so that users know how to modify the configuration when upgrading the version.

How to do that? I mean if there is any example

**Comment by Swastyy** [comment]
> > > Hi @Swastyy
> > > Thanks for your hard work!
> > > I think there may be some misunderstandings. ShargingSphere-Proxy has a configuration file `server.yaml`, which is not exist in `ShardingSphere-JDBC`.
> > > The configuration in `server.yaml` changes in different versions, so this record of change history is needed.
> > > For example:
> > > the structure of authority configuratio has changed by #10297, you can refer to the git history of the file [server.yaml](https://github.com/apache/shardingsphere/blob/master/shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/resources/conf/server.yaml) .
> > 
> > 
> > Hey, I have a doubt like changement of authority configuration is not what we want right? We want to store the changes of `server.yaml` so putting the users sections inside the authority in `server.yaml` file is not we will do. I mean we won't make any change in the above file right?
> 
> I'm sorry I didn't understand what you mean. What we need to do now is to add a change history, so have you read the git history? This file has indeed been updated many times, with new and changed parameters.

Git history is in file itself?

**Comment by RaigorJiang** [comment]
[Here](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/configuration/yaml/change-history/) is an example of ShardingSphere-JDBC.

For `server.yaml`,  we only need to list the differences between several major versions of `server.yaml`. 
Like 5.0.0, 4.x, 3.x, 2.x.

**Comment by Swastyy** [comment]
> > > > Hi @Swastyy
> > > > Thanks for your hard work!
> > > > I think there may be some misunderstandings. ShargingSphere-Proxy has a configuration file `server.yaml`, which is not exist in `ShardingSphere-JDBC`.
> > > > The configuration in `server.yaml` changes in different versions, so this record of change history is needed.
> > > > For example:
> > > > the structure of authority configuratio has changed by #10297, you can refer to the git history of the file [server.yaml](https://github.com/apache/shardingsphere/blob/master/shardingsphere-proxy/shardingsphere-proxy-bootstrap/src/main/resources/conf/server.yaml) .
> > > 
> > > 
> > > Hey, I have a doubt like changement of authority configuration is not what we want right? We want to store the changes of `server.yaml` so putting the users sections inside the authority in `server.yaml` file is not we will do. I mean we won't make any change in the above file right?
> > 
> > 
> > I'm sorry I didn't understand what you mean. What we need to do now is to add a change history, so have you read the git history? This file has indeed been updated many times, with new and changed parameters.
> 
> Git history is in file itself?



> [Here](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/configuration/yaml/change-history/) is an example of ShardingSphere-JDBC.
> 
> For `server.yaml`, we only need to list the differences between several major versions of `server.yaml`.
> Like 5.0.0, 4.x, 3.x, 2.x.

Ohhk I get it. Thank you so much.

**Comment by Swastyy** [comment]
@RaigorJiang I could only find about the versions 5.0.0-beta and 4.1.1 in the git history of `server.yaml` file. Please review it again.

**Comment by RaigorJiang** [comment]
@Swastyy 
Thanks for your efforts.  I think it's OK.
The earlier version information is more scattered, I can supplement it through subsequent PRs.

**Comment by Swastyy** [comment]
@tristaZero Please review it once.

**Comment by Swastyy** [comment]
Hey @tristaZero, @strongduanmu Pl check this PR once.

**Review by tristaZero — APPROVED** [review]
Hi @Swastyy thanks for your update. ;-)

**Comment by Swastyy** [comment]
> Hi @Swastyy thanks for your update, nice job. ;-)

Thank you so much for the instant reply @tristaZero 🎉

**Pull request merged**
