### PR TITLE
Add DBCOMPATIBILITY 'B' parameter to opengauss database

### LINKED ISSUE #33992: Support GroupConcat sql for aggregating multiple shards in opengauss and doris database
link #33797. Enhancement GroupConcat function in opengauss and doris database

### PR DESCRIPTION
**Pull request by YaoFly**
Fixes #33992.

Changes proposed in this pull request:
  - Add DBCOMPATIBILITY 'B' parameter to opengauss database

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [x] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [x] I have made corresponding changes to the documentation.
- [x] I have added corresponding unit tests for my changes.
- [x] I have updated the Release Notes of the current development version. For more details, see [Update Release Note](https://shardingsphere.apache.org/community/en/involved/contribute/contributor/)

### CODE REVIEW

**Comment by YaoFly** [comment]
@strongduanmu PTAL. I have successfully run all e2e cases of opengauss locally.

**Comment by strongduanmu** [comment]
Hi @YaoFly, can you add openGauss test case for group_concat? I removed it yesterday

**Comment by YaoFly** [comment]
> Hi @YaoFly, can you add openGauss test case for group_concat? I removed it yesterday

Added.

**Review by strongduanmu — APPROVED** [review]
Looks great, mergd.

**Pull request merged**
