### PR TITLE
Added EXTRACT_URL_PARAMETER to Doris parsing support (#31508)

### PR DESCRIPTION
**Pull request by danigiri**
Continuing with Doris parsing support.
In this case adding support for  `EXTRACT_URL_PARAMETER`
see https://doris.apache.org/docs/sql-manual/sql-functions/string-functions/extract-url-parameter
No equivalent mysql function i could find.

Continues to address #31508

### Changes proposed in this pull request:
- added test
- Marked // DORIS ADDED BEGIN|END
- added parser g4 stuff, within `extractUrlParameterFunction`
- added visitor logic as needed
- updated release notes
- ran spotless
- ran full test maven command
- also ran
```
cd test/it/parser/
mvn -DskipTests=true generate-sources compile install -q
cd parser/sql/dialect/doris/
mvn test -Dit.test=InternalDorisParserIT
```

### Question
- do we collapse two consecutive changes? So
```
// DORIS ADDED END
// DORIS ADDED BEGIN
```

would be
```
```
and have a final terminating
`// DORIS ADDED END`
at the end

---

Before committing this PR, I'm sure that I have checked the following options:
- [✅] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [✅] I have self-reviewed the commit code.
- [✅] I have (or in comment I request) added corresponding labels for the pull request.
- [✅] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [✅] I have made corresponding changes to the documentation (release notes)
- [✅] I have added corresponding unit tests for my changes.
- [✅] `mvn spotless:apply -Pcheck`
- [✅] `mvn test -Dit.test=InternalDorisParserIT` in `shardingsphere/parser/sql/dialect/doris` (need to specify it.test)
- [✅] Executed test case in Doris v2.1.6 – `SELECT EXTRACT_URL_PARAMETER('http://foo.com/?bar=baz','bar')`

```
+---------------------------------------------------------+
| extract_url_parameter('http://foo.com/?bar=baz', 'bar') |
+---------------------------------------------------------+
| baz                                                     |
+---------------------------------------------------------+
1 row in set (0.31 sec)
```

### CODE REVIEW

**Comment by danigiri** [comment]
Will check the test failures. Looks like the combo:
```
cd test/it/parser/
mvn -DskipTests=true generate-sources compile install -q
cd parser/sql/dialect/doris/
mvn test -Dit.test=InternalDorisParserIT
```
doesn't fully test as expected. Currently fully testing on my test server.

**Comment by danigiri** [comment]
found the correct test indexes, will commit tomorrow

**Comment by danigiri** [comment]
Could complete full test cycle on test machine, next is to incorporate latest upstream changes and should be OK for final review

**Comment by danigiri** [comment]
Ready for review

**Comment by strongduanmu** [comment]
Hi @danigiri, can you solve code conflict?

**Comment by danigiri** [comment]
Sure, it is probably the release notes have drifted

**Comment by danigiri** [comment]
@strongduanmu can you check? release notes should be OK now

**Comment by danigiri** [comment]
XML test files have drifted since the PR was created, will resolve conflicts tomorrow morning

**Review by strongduanmu — APPROVED** [review]
Looks so great, merged. Thank you for your contribution @danigiri

**Comment by danigiri** [comment]
awesome, thanks @strongduanmu

**Pull request merged**
