### PR TITLE
Add PluginJarLoaderTest (#23423)

### LINKED ISSUE #23423: Add test case for PluginJarLoader

### PR DESCRIPTION
**Pull request by iamhucong**
Fixes #23423.

Changes proposed in this pull request:
  - test cases for PluginJarLoaderTest class

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Comment by iamhucong** [comment]
@tuichenchuxin Could you help review the code? Please advise me if I have any problems.

**Comment by tuichenchuxin** [comment]
@jiangML Hello, Can you help check this pr?

**Comment by jiangML** [comment]
@iamhucong HI, can `plugin0.jar` be an empty jar file?

**Comment by iamhucong** [comment]
> @iamhucong HI, can `plugin0.jar` be an empty jar file? And can it be named `test-plugin.jar`?

has been modified, please help check again

**Comment by jiangML** [comment]
@iamhucong Hi, already no problem.

**Review by RaigorJiang — APPROVED** [review]

**Pull request merged**
