### PR TITLE
Update data sharding user-manual document

### PR DESCRIPTION
**Pull request by strongduanmu**
Changes proposed in this pull request:
- update data sharding java api document
- update data sharding yaml api document
- update data sharding spring boot starter document
- update data sharding spring namespace document

### CODE REVIEW

**Comment by strongduanmu** [comment]
Following is the updated document of data sharding java api:

image

**Comment by strongduanmu** [comment]
Following is the updated document of data sharding yaml api:

image

**Comment by strongduanmu** [comment]
Following is the updated document of data sharding spring boot starter api:

image

**Comment by strongduanmu** [comment]
Following is the updated document of data sharding spring namespace api:

image

**Review by tristaZero — APPROVED** [review]

**Pull request merged**
