### PR TITLE
Optimized java doc in ShardingRule class

### LINKED ISSUE #10416: Optimize java doc in ShardingRule class
As described in PR #10414, some java doc description in the `ShardingRule` class is inaccurate and needs to be optimized. You need to optimize the java doc according to the comment in PR #10414, and check whether other java doc has the same problem.

For example, the following javadoc description is inaccurate.

```java
    /**
     * Judge logic table is belong to sharding tables.
     *
     * @param logicTableName logic table name
     * @return logic table is belong to sharding tables or not
     */
    public boolean isShardingTable(final String logicTableName) {
        return tableRules.containsKey(logicTableName.toLowerCase());
    }
```

We can modify it to `Judge whether logic table is sharding table or not.` Then modify the comment of return to `whether logic table is sharding table or not`. The public method in ShardingRule has some similar problems, please find and optimize together.

If you are interested, please leave a comment below. BTW, If you need any help, please ping me.

### PR DESCRIPTION
**Pull request by Swastyy**
Fixes #10416 

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Review by strongduanmu — CHANGES_REQUESTED** [review]
@Swastyy Thank you very much for your PR, but the purpose of this issue is to check the javadoc of which public methods and check whether their descriptions are accurate.

**Comment by Swastyy** [comment]
Yes @strongduanmu , two of the public methods didn't had descriptions, so edited it 😕

**Comment by strongduanmu** [comment]
> Yes @strongduanmu , two of the public methods didn't had descriptions, so edited it 😕

@Swastyy According to the requirements of shardingsphere, the construction method does not require javadoc, which is why your pr has a checkstyle error.

**Comment by Swastyy** [comment]
> > Yes @strongduanmu , two of the public methods didn't had descriptions, so edited it 😕
> 
> @Swastyy According to the requirements of shardingsphere, the construction method does not require javadoc, which is why your pr has a checkstyle error.

Ok, then is there anything else that I can do for this issue?

**Comment by strongduanmu** [comment]
@Swastyy You can refer to the comments in PR #10414 to optimize similar java doc issues.

**Comment by strongduanmu** [comment]
@Swastyy Because this PR did not achieve the target task, I will close this PR first, and then modify the problem description in the issue. Looking forward to your new PR.

**Pull request closed without merging**
