### PR TITLE
Add test case for ProxyContext

### LINKED ISSUE #7331: Add more test cases for ProxyContext
Please add test cases for:

- [ ] ProxyContext.init()
- [ ] ProxyContext.schemaExists()
- [ ] ProxyContext.getSchema()
- [ ] ProxyContext.getAllSchemaNames()

### PR DESCRIPTION
**Pull request by xiangtao**
Fixes #7331 .

Changes proposed in this pull request:
- Add test case for ProxyContext
-
-

### CODE REVIEW

**Review by tristaZero — CHANGES_REQUESTED** [review]
Hi @xiangtao Thanks for your PR. This is my first time to see you, welcome!
BTW, Solving the CI failure issue is the first step for us to review this PR.
Thanks.

**Comment by xiangtao** [comment]
i solve test failure

**Comment by xiangtao** [comment]
already Fixed due to code format verification failure @tristaZero

**Comment by terrymanu** [comment]
Duplicated with #7491

**Pull request closed without merging**
