### PR TITLE
setNextException with chain in classes JDBCBackendTransactionManager and LocalTransactionManager

### LINKED ISSUE #20810: use recursion to setNextException with chain in classes JDBCBackendTransactionManager and LocalTransactionManager
Please use recursion to setNextException with chain, not overlap in classes JDBCBackendTransactionManager and LocalTransactionManager.

Just search `// TODO` to find the codes.

### PR DESCRIPTION
**Pull request by null-sys**
Fixes #20810.

Changes proposed in this pull request:
  - setNextException with chain in JDBCBackendTransactionManager.class
  - setNextException with chain in LocalTransactionManager.class  -

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [x] I have triggered maven check: `mvn clean install -B -T2C -DskipTests -Dmaven.javadoc.skip=true -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Review by terrymanu — APPROVED** [review]

**Comment by terrymanu** [comment]
Please resolve conflicts

**Review by terrymanu — APPROVED** [review]

**Comment by terrymanu** [comment]
Please resolve conflicts

**Comment by null-sys** [comment]
@terrymanu resolved conflicts. Please review

**Comment by null-sys** [comment]
> Please check the code @null-sys .In the original logic, the input parameter `[ex1, ex2]`,then the method will return `ex1 and ex1.next = ex2`;After your change,the input parameter `[ex1, ex2]`,then the method will return `ex2 and ex2.next = ex1`;It's not same.

@FlyingZC , As I understood, that was the indented change to recursively add these errors

**Comment by terrymanu** [comment]
Fixed at #23668

**Pull request closed without merging**
