### PR TITLE
Support Parsing `DROP STATISTICS` for PostgreSQL

### PR DESCRIPTION
**Pull request by everly-gif**
Refers #14015 

Changes proposed in this pull request:
- Optimized Grammar for `DROP STATISTICS` to support `CASCADE` and `RESTRICT`
- Adds Support for parsing `DROP STATISTICS` in `PostgreSQL`
- Adds Tests
- Successfully Builds locally

### CODE REVIEW

**Review by strongduanmu — CHANGES_REQUESTED** [review]
Hi @everly-gif, can you fix ci error first?

**Comment by everly-gif** [comment]
Hi @strongduanmu , does the failing CI have to do with my PR? I doubt so, as it fails with a `Download error` in the initial setup. Plus I have tested my code locally and it builds successfully with the entire project. Please correct me if I'm wrong

**Comment by everly-gif** [comment]
Hi @strongduanmu , does the failing CI have to do with my PR? I doubt so, as it fails with a `Download error` in the initial setup. Plus I have tested my code locally and it builds successfully with the entire project. Please correct me if I'm wrong

**Comment by everly-gif** [comment]
Retriggering the CI , seems to have done it 😊 @strongduanmu . There was no issue with the code. Maybe the CI was temporarily unavailable at the time I made the PR. Not sure what might have caused it.

**Review by strongduanmu — APPROVED** [review]
@everly-gif It looks good to me, merged.

**Pull request merged**
