### PR TITLE
Update Readme of docker-compose

### PR DESCRIPTION
**Pull request by iamkyu**
Changes proposed in this pull request:
- Update to current directory

### CODE REVIEW

**Review by TeslaCN — COMMENTED** [review]
Could we rename the directory to `shardingsphere`?

**Review by tristaZero — APPROVED** [review]

**Comment by tristaZero** [comment]
Hi @iamkyu ,

Thanks for your PR. which version do you use? @TeslaCN feedbacked that the doc is correct.

**Comment by iamkyu** [comment]
@tristaZero 
current version on master branch. (maybe 5.0.0-beta)

I guess @TeslaCN means, 
- change directory name `/examples/docker/sharding-jdbc/` to `/examples/docker/shardingsphere-jdbc/` that same as readme
- Instead of change directory name in `docker-compose.md` and `docker-compose-zh.md`

is it right? I will pull request ASAP.

**Comment by TeslaCN** [comment]
> @tristaZero
> current version on master branch. (maybe 5.0.0-beta)
> 
> I guess @TeslaCN means,
> 
> * change directory name `/examples/docker/sharding-jdbc/` to `/examples/docker/shardingsphere-jdbc/` that same as readme
> * Instead of change directory name in `docker-compose.md` and `docker-compose-zh.md`
> 
> is it right? I will pull request ASAP.

Yes. `sharding-jdbc` or `sharding-proxy` was named after the legacy version. The current version is `shardingsphere-jdbc` and `shardingsphere-proxy`.

**Comment by tristaZero** [comment]
@iamkyu Looks like we need another PR to revert it, could you give a hand?
But I am curious why your raise this PR? Do you have some problems with our examples?

**Pull request merged**
