### PR TITLE
Add `MERGE` statement test case

### PR DESCRIPTION
**Pull request by ThanoshanMV**
#9129 

Changes proposed in this pull request:
- added a test case for `MERGE` statement

### CODE REVIEW

**Comment by ThanoshanMV** [comment]
Hi @tristaZero, I've added a test case for `MERGE` statement. Can you please check whether I'm doing it in the correct way? (the segments I chose and visiting actual values from AST in `OracleDMLStatementSQLVisitor`) I'll change according to your feedback.

**Comment by tristaZero** [comment]
Hi @ThanoshanMV ,

The PR looks almost correct. Nice!
Actually, it is challenging to visit out the corresponding `SQLStatement`. Anyway, we can firstly fill some necessary `Segment`s into the target `SQLStatement`.

Here is another issue needing your attention.

Could you figure out whether there are similar `MERGE` SQL definitions in other databases, like `SQLServer`, `SQL92`?

The reason is that I found you created an abstract class, `MergeStatement`. Generally, an abstract class `MergeStatement` is designed to imply that there will be many final child classes from various databases, like the `OracleMergeStatement` class from you.

So if `MERGE` SQL is specific to `Oracle`, it is suggested to remove abstract `MergeStatement`.

**Comment by ThanoshanMV** [comment]
Hi @tristaZero, 

I tried to search and figured out that `SQL Server` has a similar `MERGE` [statement](https://docs.microsoft.com/en-us/sql/t-sql/statements/merge-transact-sql?view=sql-server-ver15). 

In the `OracleDMLStatementSQLVisitor`, why we're visiting each subrule? For example, `visitWhereClause`, `visitGroupByClause`. If we consider asserting `MERGE` test cases, we actually get values from `visitMerge` right? If it is, then why we need to visit each subrule? I'm sorry this could be a silly question.

As you said, I'll fill some necessary segments into the target `SQLStatement` to work wholly and finish up remaining all other test cases.

**Comment by jingshanglu** [comment]
@ThanoshanMV May be it is better to use 'into' and 'using' than use 'tables' in `mergeStatement`. we visit each subrule in order to construct a convenient data structure.

**Comment by ThanoshanMV** [comment]
@jingshanglu, do you mean like this for `MergeStatement`:
MergeStatement
and `MergeStatementTestCase`:

MergeStatementTestCase

**Comment by jingshanglu** [comment]
@ThanoshanMV  Yes, it may be better to determine the meaning of a property by its name.

**Comment by ThanoshanMV** [comment]
In [`MERGE` statement](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/MERGE.html#GUID-5692CCB7-24D9-4C0E-81A7-A22436DC968F), Into clause specifies the target table or view and using clause specifies source table or view. 

So, changing the property names and XML element names as `source` and `target` like below would be okay? : 
MergeStatement
and `MergeStatementTestCase`:
MergeStatementTestCase

**Comment by jingshanglu** [comment]
@ThanoshanMV I think that's ok.

**Comment by ThanoshanMV** [comment]
@jingshanglu I tried to visit subrules `intoClause` and `usingClause` in the `OracleDMLStatementSQLVisitor`. I also visited `viewName` in `OracleStatementSQLVisitor` similar to `MySQLStatementSQLVisitor`. I added single parameter asserts in `MergeStatementAssert`. Can you please check it

**Review by jingshanglu — APPROVED** [review]

**Comment by tristaZero** [comment]
Hi @ThanoshanMV @jingshanglu 
It is the right time to merge? I guess @ThanoshanMV needs to change the pattern of this PR as a regular one rather than a draft?

**Comment by ThanoshanMV** [comment]
Sorry @tristaZero, I changed the pattern of this PR

**Comment by tristaZero** [comment]
Nice work, do you have any plan next? @ThanoshanMV  :)

**Comment by ThanoshanMV** [comment]
@tristaZero in the merge statement, `merge update clause`, `merge insert clause` and `error logging clause` needs test cases. I'll add try to add them and I'll prepare my application.

**Comment by tristaZero** [comment]
@ThanoshanMV Got it. go ahead, good luck.

**Pull request merged**
