### PR TITLE
Unified debug level log adding judgment

### PR DESCRIPTION
**Pull request by longtai-cn**
Changes proposed in this pull request:
- Unified debug level log adding judgment.

> Referring to the writing method of other debug level logs in the project, standardize the printing method of debug logs.

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
Is it effect the performance? maybe we need a performance test report

**Comment by longtai-cn** [comment]
> Is it effect the performance? maybe we need a performance test report

@terrymanu This PR is mainly to unify the printing method of debug level logs, which may not greatly improve the performance

**Comment by terrymanu** [comment]
> > Is it effect the performance? maybe we need a performance test report
> 
> @terrymanu This PR is mainly to unify the printing method of debug level logs, which may not greatly improve the performance

@longtai-cn The original codes look like more clear, is it necessary to add more judgment here?

**Comment by longtai-cn** [comment]
@terrymanu You're right. I should focus on performance. This PR is coming to an end.

**Comment by terrymanu** [comment]
Thank you very much

**Pull request closed without merging**
