### PR TITLE
Upgrade antlr4 to 4.9.2

### PR DESCRIPTION
**Pull request by zhfeng**

### CODE REVIEW

**Comment by zhfeng** [comment]
@RaigorJiang I'm working on [quarkus-shardingsphere-jdbc](https://github.com/quarkiverse/quarkus-shardingsphere-jdbc) and Quarkus also has the depdency on ```org.antlr4:antlr4-runtime``` with ```4.9.2```. So I get the following message

```
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.9.2
ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.9.2
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.9.2
ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.9.2
```

Anyway, I could align the antlr4 version in ```quarkus-shardingsphere-jdbc``` with ```shardingshpere-jdbc-core```. But I just still want to see if upgrading antlr4 is acceptable by shardingsphere.

**Comment by zhfeng** [comment]
Thanks, that fix looks good to me.

**Comment by strongduanmu** [comment]
> @zhfeng Thanks for your PR, could you give a look at these failed CI tests? I am unsure whether they are due to this change.
> 
> @strongduanmu Could you double-check this version is fine with our project？

@tristaZero I will check this upgrade.

**Comment by RaigorJiang** [comment]
CI has been fixed in #13027.

**Comment by strongduanmu** [comment]
> CI has been fixed in #13027.

@zhfeng Can you sync latest master branch code?

**Comment by strongduanmu** [comment]
@tristaZero I have checked the release notes of `antlr`, and there is no incompatibility between the new and old versions, so I think the version can be upgraded.

**Pull request merged**
