### PR TITLE
24811 readwrite splitting data source router tests

### LINKED ISSUE #24811: Add test cases for ReadwriteSplittingDataSourceRouter

### PR DESCRIPTION
**Pull request by kvaithin**
Fixes #24811 

Added test cases for `ReadwriteSplittingDataSourceRouter` class.

---

Before committing this PR, I'm sure that I have checked the following options:
- [X] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [X] I have self-reviewed the commit code.
- [X] I have (or in comment I request) added corresponding labels for the pull request.
- [X] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [X] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Comment by kvaithin** [comment]
Could I get some help with this. 

I am running the following command. 

`./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`

Which returns following check style alert. 

`org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (validate) on project shardingsphere-readwrite-splitting-core: You have 4 Checkstyle violations.
`

But I do not see any result generated. 

The checkstyle-result.xml file only has the following: 

```
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="8.19">
</checkstyle>
```

Is this expected or any further steps needed to generate the report? Thanks.

**Comment by terrymanu** [comment]
Please just fix the checkstyle warning

**Comment by kvaithin** [comment]
> Please just fix the checkstyle warning

Hi @terrymanu , updated.

**Comment by strongduanmu** [comment]
Hi @kvaithin, the ci is still error, can you update latest code and fix it?

**Comment by strongduanmu** [comment]
Since this pr has long time no response, I will close it.

**Pull request closed without merging**
