### PR TITLE
Incorrect HINT_INLINE algorithm expression in RDL tests

### LINKED ISSUE #25131: Incorrect `HINT_INLINE` algorithm expression in RDL tests
Hint inline sharding algorithm only accepts property named `value`, but `user_id` is used in test statement, which is incorrect.

image

```sql
'algorithm-expression'='t_order_${user_id % 2}')
```

https://github.com/apache/shardingsphere/blob/2c1bdd26cf3d163ef5fdc2615590325bc67ec867/test/it/parser/src/main/resources/sql/supported/rdl/alter.xml#L46

It should be noted that this is the case in both CREATE and ALTER statements.

### PR DESCRIPTION
**Pull request by ZJJ087**
Fixes  #25131.

Changes proposed in this pull request:
  -

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [x] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [x] I have made corresponding changes to the documentation.
- [x] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Comment by ZJJ087** [comment]
@RaigorJiang please review it

**Comment by RaigorJiang** [comment]
Hi @ZJJ087 , Can you update this PR?

**Comment by ZJJ087** [comment]
> Hi @ZJJ087 , Can you update this PR?

OK，I will update it in these two days. I have been busy recently.

**Comment by RaigorJiang** [comment]
> OK，I will update it in these two days. I have been busy recently.

@ZJJ087 Well, thank you!

**Pull request closed without merging**
