### PR TITLE
#13033 close connection after get source of information_schema

### LINKED ISSUE #13033: select information_schema didn't release connection cause connection pool exhausted
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0-RC1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
execute such sql multiple times should be ok
```
select `column_name` as `column_name`, `column_comment` as `column_comment`, `column_default` as `column_default`, `data_type` as `data_type` from information_schema.columns limit 1;
```

### Actual behavior
after ```maxPoolSize``` times, SQL will be hang until connection timeout.

### Reason analyze (If you can)
getSourceData of AbstractSelectInformationExecutor.java didn't close connection.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
execute such sql for ```maxPoolSize``` times 
```
select `column_name` as `column_name`, `column_comment` as `column_comment`, `column_default` as `column_default`, `data_type` as `data_type` from information_schema.columns limit 1;
```

### PR DESCRIPTION
**Pull request by roodkcab**
Fixes #13033 .

Changes proposed in this pull request:
- close connection after get source of information_schema

### CODE REVIEW

**Comment by tristaZero** [comment]
@roodkcab Hey thanks @lanchengx Please review again

**Comment by tristaZero** [comment]
@roodkcab I found there are a few failed CI tests. Could you check them again?

**Comment by roodkcab** [comment]
> @roodkcab I found there are a few failed CI tests. Could you check them again?

sure, I'll have a check

**Comment by lanchengx** [comment]
> @lanchengx @RaigorJiang @tristaZero it seems everything is ok, do I need to squash all commits into one? and any other thing to do?

Thank you for your work, but we still have some requirements on the format and capitalization,
You still need to deal with the issue of my previous comment.

such as

image

image

**Comment by RaigorJiang** [comment]
Hi @tristaZero, please take a review, thank you!

**Pull request merged**
