### PR TITLE
Add test case for ContextManager.alterSchema

### PR DESCRIPTION
**Pull request by hjj5258**
#18686

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
Please fix CI

**Comment by hjj5258** [comment]
> 请修复 CI



> Please fix CI
I'm not sure if I'm doing it correctly?

**Review by terrymanu — APPROVED** [review]

**Comment by terrymanu** [comment]
@hjj5258 Hi, your pull request does not include necessary assertions, I have already completed them, please have a look on #19009

**Comment by hjj5258** [comment]
> @hjj5258 Hi, your pull request does not include necessary assertions, I have already completed them, please have a look on #19009

Thank you for the code review,I will learn from it and expect to write the right testcase next time.

**Pull request merged**
