### PR TITLE
Update antlr4 to 4.10.1 close #19990

### LINKED ISSUE #19990: Update antlr4 to 4.10+
Hibernate 6.0.1+ was ues antlr4: 4.10+
when I force to use  antlr4: 4.10+，I got error：
org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version **4** (expected 3).
then when I force to use  antlr4: 4.9.x，I got error
org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version **3** (expected 4).

### PR DESCRIPTION
**Pull request by shanrenxj**
Fixes #19990.
Update antlr4 to 4.10.1
Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Review by linghengqian — COMMENTED** [review]
What do you think of https://github.com/antlr/antlr4/pull/3450?

**Comment by linghengqian** [comment]
I noticed the magic https://github.com/antlr/antlr4/pull/3748.  Maybe you can try setting to 4.10.0 locally to edit.

**Comment by shanrenxj** [comment]
> I noticed the magic [antlr/antlr4#3748](https://github.com/antlr/antlr4/pull/3748). Maybe you can try setting to 4.10.0 locally to edit.

Since antlr4 4.10, antlr4 has started to use Java 11 for source code compilation.
--------------------------------------------------------------------------------
Going forward, we are using Java 11 for the source code and the compiled .class files for the ANTLR tool. The Java runtime target, however, and the associated runtime tests use Java 8 (bumping up from Java 7).
--------------------------------------------------------------------------------

**Comment by linghengqian** [comment]
4.10.1 is "Going forward", but 4.10.0 is not.  You need to reprocess dynamically generated files for the breaking changes of anltr 4.10.0.  This is the first step in fixing CI.

**Comment by shanrenxj** [comment]
> 4.10.1 is "Going forward", but 4.10.0 is not. You need to reprocess dynamically generated files for the breaking changes of antlr 4.10.0. This is the first step in fixing CI.
----------------------------------------------------------------------------
I looked at the pom file for ANTLR 4.10 and it has started using java11

**Comment by linghengqian** [comment]
I pointed out a fun PR.  Although `maven.compiler.source` and `maven.compiler.target` are set to 11, the rebase of `maven-compiler-plugin` for all subprojects is 8.  This is also why the ShardingSphere project can use Groovy 4.0.3, even though the master branch of Groovy requires JDK 16 builds.

**Comment by shanrenxj** [comment]
It seems that shardingsphere needs to do the same

**Comment by shanrenxj** [comment]
> > * What do you think of [use src 11 for tool, but 8 for plugin/runtime antlr/antlr4#3450](https://github.com/antlr/antlr4/pull/3450)?
> > * Does ShardingSphere have to do this too?  At least JDK8 compatibility must be guaranteed before the Minor Version changes.
> 
> * I pointed out a fun PR.  Although `maven.compiler.source` and `maven.compiler.target` are set to 11, the release of `maven-compiler-plugin` for all subprojects is 8.  This is also why the ShardingSphere project can use Groovy 4.0.3, even though the master branch of Groovy requires JDK 16 builds.

It seems that shardingsphere needs to do the same

**Comment by linghengqian** [comment]
> > > * What do you think of [use src 11 for tool, but 8 for plugin/runtime antlr/antlr4#3450](https://github.com/antlr/antlr4/pull/3450)?
> > > * Does ShardingSphere have to do this too?  At least JDK8 compatibility must be guaranteed before the Minor Version changes.
> > 
> > * I pointed out a fun PR.  Although `maven.compiler.source` and `maven.compiler.target` are set to 11, the release of `maven-compiler-plugin` for all subprojects is 8.  This is also why the ShardingSphere project can use Groovy 4.0.3, even though the master branch of Groovy requires JDK 16 builds.
> 
> It seems that shardingsphere needs to do the same
> 
> 

I don't think so.  I'm currently working on some other PR preparations, so I can't test my ideas right away.  If you think there are some easy ideas to deal with it, it's a good idea to submit a new commit to be verified by CI.

**Comment by shanrenxj** [comment]
> > > * What do you think of [use src 11 for tool, but 8 for plugin/runtime antlr/antlr4#3450](https://github.com/antlr/antlr4/pull/3450)?
> > > * Does ShardingSphere have to do this too?  At least JDK8 compatibility must be guaranteed before the Minor Version changes.
> > 
> > 
> > 
> > * I pointed out a fun PR.  Although `maven.compiler.source` and `maven.compiler.target` are set to 11, the release of `maven-compiler-plugin` for all subprojects is 8.  This is also why the ShardingSphere project can use Groovy 4.0.3, even though the master branch of Groovy requires JDK 16 builds.
> 
> It seems that shardingsphere needs to do the same

org.hibernate.orm:hibernate-core:6.0.0.Final

> > > > * What do you think of [use src 11 for tool, but 8 for plugin/runtime antlr/antlr4#3450](https://github.com/antlr/antlr4/pull/3450)?
> > > > * Does ShardingSphere have to do this too?  At least JDK8 compatibility must be guaranteed before the Minor Version changes.
> > > 
> > > 
> > > 
> > > * I pointed out a fun PR.  Although `maven.compiler.source` and `maven.compiler.target` are set to 11, the release of `maven-compiler-plugin` for all subprojects is 8.  This is also why the ShardingSphere project can use Groovy 4.0.3, even though the master branch of Groovy requires JDK 16 builds.
> > 
> > 
> > It seems that shardingsphere needs to do the same
> 
> I don't think so. I'm currently working on some other PR preparations, so I can't test my ideas right away. If you think there are some easy ideas to deal with it, it's a good idea to submit a new commit to be verified by CI.



> > > > * What do you think of [use src 11 for tool, but 8 for plugin/runtime antlr/antlr4#3450](https://github.com/antlr/antlr4/pull/3450)?
> > > > * Does ShardingSphere have to do this too?  At least JDK8 compatibility must be guaranteed before the Minor Version changes.
> > > 
> > > 
> > > 
> > > * I pointed out a fun PR.  Although `maven.compiler.source` and `maven.compiler.target` are set to 11, the release of `maven-compiler-plugin` for all subprojects is 8.  This is also why the ShardingSphere project can use Groovy 4.0.3, even though the master branch of Groovy requires JDK 16 builds.
> > 
> > 
> > It seems that shardingsphere needs to do the same
> 
> I don't think so. I'm currently working on some other PR preparations, so I can't test my ideas right away. If you think there are some easy ideas to deal with it, it's a good idea to submit a new commit to be verified by CI.

As the project is in a hurry, our team currently uses hibernate core: 6.0.0 (ANTLR 4.9.1) to avoid ANTLR conflicts. Looking forward to shardingsphere update

**Comment by shanrenxj** [comment]
> > > > * What do you think of [use src 11 for tool, but 8 for plugin/runtime antlr/antlr4#3450](https://github.com/antlr/antlr4/pull/3450)?
> > > > * Does ShardingSphere have to do this too?  At least JDK8 compatibility must be guaranteed before the Minor Version changes.
> > > 
> > > 
> > > 
> > > * I pointed out a fun PR.  Although `maven.compiler.source` and `maven.compiler.target` are set to 11, the release of `maven-compiler-plugin` for all subprojects is 8.  This is also why the ShardingSphere project can use Groovy 4.0.3, even though the master branch of Groovy requires JDK 16 builds.
> > 
> > 
> > It seems that shardingsphere needs to do the same
> 
> I don't think so. I'm currently working on some other PR preparations, so I can't test my ideas right away. If you think there are some easy ideas to deal with it, it's a good idea to submit a new commit to be verified by CI.

As the project is in a hurry, our team currently uses hibernate core: 6.0.0 (ANTLR 4.9.1) to avoid ANTLR conflicts. Looking forward to shardingsphere update,  thanks!

**Comment by linghengqian** [comment]
This PR actually drops ShardingSphere JDBC support for versions of hibernate < 6.0.1, the description of the PR should be changed to reflect this. I'm not sure if you are still working on this PR, as this PR is still marked for review and has unfixed CI bugs.

**Comment by linghengqian** [comment]
Synchronous comments: I suggest you open a new issue to discuss the point in time to migrate the base JDK version of ShardingSphere to JDK11. This issue will be blocked before the new issue is resolved, so I suggest closing this PR.

**Comment by terrymanu** [comment]
Does anyone still focus this PR?

**Comment by linghengqian** [comment]
This PR has no point of continuing to resolve unless https://github.com/apache/shardingsphere/issues/20935 is resolved.

**Comment by chenzhenjia** [comment]
my project upgrade to 4.10.1 not working


```
ANTLR Tool version 4.9.2 used for code generation does not match the current runtime version 4.10.1
ANTLR Runtime version 4.9.2 used for parser compilation does not match the current runtime version 4.10.1

jakarta.servlet.ServletException: Handler dispatch failed: java.lang.ExceptionInInitializerError
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1095)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:973)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1003)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:895)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:880)
    .....
Caused by: java.lang.UnsupportedOperationException: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version 3 (expected 4).
	at org.antlr.v4.runtime.atn.ATNDeserializer.deserialize(ATNDeserializer.java:56)
	at org.antlr.v4.runtime.atn.ATNDeserializer.deserialize(ATNDeserializer.java:48)
	at org.apache.shardingsphere.sql.parser.autogen.MySQLStatementLexer.<clinit>(MySQLStatementLexer.java:4533)
	... 246 common frames omitted
Caused by: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version 3 (expected 4).
	... 249 common frames omitted

```

**Comment by linghengqian** [comment]
@chenzhenjia I'm assuming you have a PR that goes through CI to fix the issue.

**Comment by chenzhenjia** [comment]
@linghengqian I use spring boot3 rc2 and hibernate 6.1.5

**Comment by linghengqian** [comment]
@chenzhenjia 
- You can fix this by temporarily explicitly configuring hibernate's dependency version to `6.0.0` in either `pom.xml` or `build.gradle`. 

- To completely solve this problem, you need according to the requirement of the https://github.com/apache/shardingsphere/issues/20935#issuecomment-1273994076 , initiate a discussion on the ShardingSphere maillist about raising the minimum JDK compiled version. I did not intend to initiate such a discussion at this point in time, so I did not follow the topic.

**Comment by chenzhenjia** [comment]
I am not willing to downgrade hibernate to 5.x or 6.x, I provide a gradle solution:
1. copy [antlr4 dir](https://github.com/apache/shardingsphere/tree/master/sql-parser/dialect/mysql/src/main/antlr4) all file to project `src/main/antlr` dir
```
// my project tree
project/src/
├── main
│   ├── antlr
│   ├── java
│   ├── resources
```
2. Modify build.gradle.kts
```
//build.gradle.kts
plugins {
    idea
    antlr
    id("org.springframework.boot") 
}
dependencies {
    antlr("org.antlr:antlr4:4.10.1")
    compileOnly("org.antlr:antlr4-runtime:4.10.1")
}
tasks.generateGrammarSource {
    exclude("imports/**")
    arguments = listOf(
        "-lib",
        project.file("/src/main/antlr/imports/mysql").absolutePath,
        "-package",
        "org.apache.shardingsphere.sql.parser.autogen",
        "-visitor"
    )
}
```
4. run project

**Comment by linghengqian** [comment]
- As a reminder, for anyone who wants to bypass the master branch to solve this problem, they can directly modify the master branch according to the content of https://github.com/apache/shardingsphere/pull/20119 , and then compile with jdk11+ to generate a new shardingsphere jdbc distribution containing new antlr4 runtime file. Until someone is ready to initiate a poll on the maillist.

**Comment by zhfeng** [comment]
I have a same issue
- https://github.com/quarkiverse/quarkus-shardingsphere-jdbc/issues/84

**Comment by zhfeng** [comment]
@terrymanu @linghengqian should we start a thread on mailing list to discuss this topic? I think it is a formal way and maybe we need a voting?

**Comment by linghengqian** [comment]
@zhfeng I'm assuming you'll go to the maillist and open a new thread, since I'm not at all sure how big of a backlash there is to raising the JDK version. If we don't initiate a vote, everything is unknown.

**Comment by zhfeng** [comment]
@linghengqian yeah, I will open a thread on the mailing list for this topic soon. And for sure, the voting is definitely helpful.

@terrymanu WDYT?

**Comment by zhfeng** [comment]
https://lists.apache.org/thread/kgtfx5vnw73o61lkvdshyfvjfvvzk3js

**Comment by zhfeng** [comment]
@linghengqian It seems that only `org.antlr:antlr` is `JDK 11`, the `org.antlr:antlr4-runtime` is still compatitable with `JDK 1.8`. I just try to build `master` branch with `antlr-4.10.1` by using `Java 11` and swith to use `JDK 1.8` to run a `examples/shardingsphere-parser-example`. It works !

So is it possible to just change the CI to build with `JDK 11` and run all the tests & examples by `JDK 8`?

**Comment by linghengqian** [comment]
@zhfeng 

- I wanted to do this from the beginning, but I don't know how to change the Github Actions files. The unit tests are always with the generated class files, and it seems difficult to stand alone test files.

**Comment by zhfeng** [comment]
Please review https://github.com/apache/shardingsphere/issues/20935

**Comment by zhfeng** [comment]
Well, `antlr.skip` is no useful for our case. It needs to load the ExecuteMojo which has dependency of `org/antlr/v4/Tool` targeting for 11. So there is still throwing `java.lang.UnsupportedClassVersionError` at build time.

The only way is to have `antlr4-maven-plugin` in the `jdk-11` profile. I will take care of upgrading `antlr4` if
- https://github.com/apache/shardingsphere/pull/23550 get merged.

**Comment by linghengqian** [comment]
@zhfeng Hi, I was wondering if you are preparing a PR to change the version of Antlr4? I'm trying to confirm the Antlr4 version of the GraalVM reachability metadata I need to submit at https://github.com/oracle/graalvm-reachability-metadata/issues/198 .

**Comment by zhfeng** [comment]
It should be suppressed https://github.com/apache/shardingsphere/pull/23937

**Comment by linghengqian** [comment]
- Since https://github.com/apache/shardingsphere/pull/23937 was merged, this PR can be closed directly.

**Pull request closed without merging**
