### PR TITLE
support mysql database create, alter and drop statement

### PR DESCRIPTION
**Pull request by strongduanmu**
Ref #6498 .

Changes proposed in this pull request:
- support mysql database create, alter and drop statement

### CODE REVIEW

**Comment by meiyouxiaojianpan** [comment]
hello, I have a question
shardingsphere version: 4.0.0-RC3
`
alter table w_test_f_0
add column test1 varchar(10) null default null comment 'test';
// This statement can be executed normally

alter table w_test_f_0
add column test1 amount null default null comment 'test';
// This statement throw NPE
`
Can this merge solve this problem?

**Comment by strongduanmu** [comment]
> hello, I have a question
> shardingsphere version: 4.0.0-RC3
> `
> alter table w_test_f_0
> add column test1 varchar(10) null default null comment 'test';
> // This statement can be executed normally
> 
> alter table w_test_f_0
> add column test1 amount null default null comment 'test';
> // This statement throw NPE
> `
> Can this merge solve this problem?

@meiyouxiaojianpan Hi, can you provide the sharding configuration and the schema of the table `w_test_f_0`?

**Comment by meiyouxiaojianpan** [comment]
My configuration only configures the mysql view, example: `w_test_v_0`
`w_test_f_0` is not configured but processed by  shardingsphere method `org.apache.shardingsphere.core.parse.core.extractor.impl.ddl.column.ColumnDefinitionExtractor#extract`
image
getChild(0) is null
Thank you for answering my question

**Comment by strongduanmu** [comment]
> My configuration only configures the mysql view, example: `w_test_v_0`
> `w_test_f_0` is not configured but processed by shardingsphere method `org.apache.shardingsphere.core.parse.core.extractor.impl.ddl.column.ColumnDefinitionExtractor#extract`
> image
> getChild(0) is null
> Thank you for answering my question

@meiyouxiaojianpan I am very sorry that I can not get your point. Can you provide the sharding configuration and the structure of the `w_test_f_0` table —— like `create table w_test_f_0 ...` ? I need a case to reproduce the bug.

**Pull request merged**
