### PR TITLE
Optimize change history of ShardingSphere-JDBC Spring Namespace Configuration (Chinese)

### LINKED ISSUE #10986: [Doc] Optimize change history of ShardingSphere-JDBC Spring Namespace Configuration (Chinese)
Hi community,

This issue is for [#10887](https://github.com/apache/shardingsphere/issues/10887).

### Background

Refor to #10972

### Aim

Optimize change history of ShardingSphere-JDBC Spring Namespace Configuration. (Chinese version). 

### How to

1. Migrate `Spring Namespace Configuration` change history from

   `4.1.2.Configuration Manual`->`Spring Namespace Configuration`->`Change History` to

   `7.2.API Change History`->`7.2.1.ShardingSphere-JDBC`->`Spring Namespace Configuration`;

2. Refer to the documents of each version on the official website, check whether the change history is correct, and fill in the missing parts.

3. The content organization of the change history is as follows:

   - ShardingSphere-5.0.0-beta
     - Sharding
     - Readwrite-splitting
     - Encryption
     - Shadow DB
     - Governance
   - ShardingSphere-4.x
     - Sharding
     - Readwrite-splitting
     - Data Masking
     - Orchestration
   - ShardingSphere-3.x
     - Sharding
     - Readwrite-splitting
     - Orchestration
   - ShardingSphere-2.x
     - Sharding
     - Readwrite-splitting
     - Orchestration

### Reference

- [Apache ShardingSphere website](https://shardingsphere.apache.org/)

- [Spring Namespace Configuration change history](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/configuration/spring-namespace/change-history/)

### PR DESCRIPTION
**Pull request by sydgeek**
Optimize change history of ShardingSphere-JDBC Spring Namespace Configuration (Chinese)
Fixes #10986 .

There has a problem in this document.
- The following 2 namespaces in the document are inaccessible:
    http://shardingsphere.apache.org/schema/shardingsphere/readwrite-splitting/readwrite-splitting-5.0.0.xsd
    http://shardingsphere.apache.org/schema/shardingsphere/governance/governance-5.0.0.xsd

It seems that the directory /governance and /read write-splitting does not exist in the index of /schema/shardingsphere,
needs additional repair.

### CODE REVIEW

**Comment by sydgeek** [comment]
It looks like shardingsphere-proxy-backend cannot be built on unix.
How to check and solve this problem? I just added a Markdown file to the document.🤔

**Comment by RaigorJiang** [comment]
> It looks like shardingsphere-proxy-backend cannot be built on unix.
> How to check and solve this problem? I just added a Markdown file to the document.🤔

Yes, your modification does not affect the CI results, thanks for your PR!

**Review by RaigorJiang — APPROVED** [review]

**Review by tristaZero — APPROVED** [review]
Hi @sydgeek  welcome join here, please take fun.

**Comment by tristaZero** [comment]
@RaigorJiang Thanks for the review.

**Pull request merged**
