### PR TITLE
Optimize the message of `DatabaseServerInfo`

### LINKED ISSUE #28421: Logging: optimize the message of database name.
There are now two database names with different meanings in the log, which should be optimized.

image

### PR DESCRIPTION
**Pull request by 134130**
Fixes #28421.

`in: proxy` `type: refactor`

Changes proposed in this pull request:
  - The "Database name" is ambiguous; It can be DBMS's product name or It's inner schema's name.
  - In normally, we don't call `MySQL` as "DBMS product name" or "DBMS name". Just "DBMS" is `MySQL`.
  - Just `DBMS` is clear.
  - Not changing inner field's naming; Since it is already clear that `DatabaseServer`'s name means DatabaseProduct's name

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [x] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [x] ~I have made corresponding changes to the documentation.~
- [x] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Comment by RaigorJiang** [comment]
Hi @134130 
Thank you for your serious reply.

In ShardingSphere, we use `database type` to describe the type of database. 
Do you think it is okay to change the log to `Database type is xx`?

Please refer to:
- [DatabaseType](https://github.com/apache/shardingsphere/blob/master/infra/database/core/src/main/java/org/apache/shardingsphere/infra/database/core/type/DatabaseType.java)
- [MySQLDatabaseType](https://github.com/apache/shardingsphere/blob/master/infra/database/type/mysql/src/main/java/org/apache/shardingsphere/infra/database/mysql/type/MySQLDatabaseType.java)

**Comment by 134130** [comment]
@RaigorJiang Yeah, I've considered using `database type` since many fields and arguments are named with it.
But when we saying `database type`, It means such as type of DBMSs which like `RDBMS`, `NoSQL`, `Hierarchical DB`, `Data Warehouse` and somethings...
So I thought using `DBMS` is better for on message case.

But I am open to changing message to Database type ;)

**Comment by RaigorJiang** [comment]
> @RaigorJiang Yeah, I've considered using `database type` since many fields and arguments are named with it. But when we saying `database type`, It means such as type of DBMSs which like `RDBMS`, `NoSQL`, `Hierarchical DB`, `Data Warehouse` and somethings... So I thought using `DBMS` is better for on message case.
> 
> But I am open to changing message to Database type ;)

In ShardingSphere's [Design Philosophy](https://shardingsphere.apache.org/document/current/en/overview/), `SQL`/`NoSQL`/`NewSQL` are considered heterogeneous databases, so can they be collectively called databases?

image

**Comment by 134130** [comment]
Since ShardingSphere uses `Database Product name` as `Database type` in many codes, I also agree concentrate 
 to `Database type`.

> In ShardingSphere's [Design Philosophy](https://shardingsphere.apache.org/document/current/en/overview/), SQL/NoSQL/NewSQL are considered heterogeneous databases, so can they be collectively called databases?

Are you saying database only means Relational databases? I think "Heterogeneous databases" contains all of `SQL` `NoSQL` and `Others` which can stores data.
And I suggests `Database kind` or `Database class` to dividing `SQL` and `NoSQL` later; `Haskell` uses `Kind` as a type of type 😃

**Comment by 134130** [comment]
Do this common class really used in 3 cases(including 2 tests)?? 😂

**Comment by RaigorJiang** [comment]
> Do this common class really used in only 3 cases(including 2 tests)?? 😂 

It seems so.
Some ci failed, please merge the master branch to solve the problem, thank you!

**Review by RaigorJiang — APPROVED** [review]

**Comment by RaigorJiang** [comment]
@134130  Mergerd, thank you!

**Pull request merged**
