### PR TITLE
add EncryptAlgorithm SM3 & SM4

### PR DESCRIPTION
**Pull request by cheese8**
Ref #12912  @strongduanmu 

SubTask1

Changes proposed in this pull request:
- add SM3EncryptAlgorithm & SM4EncryptAlgorithm
- add testcases

### CODE REVIEW

**Comment by strongduanmu** [comment]
@cheese8 I seem to have found the cause of the exception. The bcprov-jdk15to18 you use can only support jdk8, so I think you can try bcprov-jdk15on.

**Review by terrymanu — CHANGES_REQUESTED** [review]
Hi, does the license compatible with Apache 2.0?

**Comment by cheese8** [comment]
@terrymanu bcprov-jdk15on is MIT license, I think it's compatible with Apache 2.0.

**Comment by terrymanu** [comment]
Could you give me a link for MIT license?

I found it in maven repository, the license is `BouncyCastle`

https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15on

image

**Comment by cheese8** [comment]
I think the license is here.
https://bouncycastle.org/licence.html @terrymanu

**Comment by terrymanu** [comment]
> I think the license is here. https://bouncycastle.org/licence.html @terrymanu

Fine. Could you fix the CI failure? And then we can merge it.

**Comment by cheese8** [comment]
Yes, I am try to fix it.

**Comment by cheese8** [comment]
The CI failure was fixed by excluding signature files such as SF / RAS / DSA, and I do not know & test whether it has affected with uber agent-bootstrap. @terrymanu

**Comment by terrymanu** [comment]
@cheese8 Thank you very much. 
I will create a new issue for add document of SM3 & SM4, please pick up it  if you are interested.

**Comment by terrymanu** [comment]
The document issue is #13986

**Comment by tristaZero** [comment]
@cheese8 Hi, thanks for this contribution, we recently found many guys are interested in this algorithm and want to use it online in their cases. good job to the whole community!

**Comment by tristaZero** [comment]
BTW, are you interested in becoming the committer of this Apache community? I could see your lots of effort here. We are looking forward to inviting you to be part of ShardingSphere. Maybe more commits are more convincing for other PMCs. You could learn more on https://github.com/apache/shardingsphere/graphs/contributors

**Comment by cheese8** [comment]
@tristaZero Yes, I am very interested,  my honor and very happy to be a committer of Apache ShardingSphere community. I will continue to make contributions on this community.

**Pull request merged**
