### PR TITLE
Correct Oracle unreservedWord

### PR DESCRIPTION
**Pull request by Liangda-w**
Relates #9604 

Changes proposed in this pull request:
- deleted [Oracle SQL Reserved Words](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Oracle-SQL-Reserved-Words.html#GUID-55C49D1E-BE08-4C50-A9DD-8593EB925612) from `unreservedWord`

Could you please review it :) @wgy8283335

### CODE REVIEW

**Comment by wgy8283335** [comment]
> Relates #9604
> 
> Changes proposed in this pull request:
> 
> * deleted [Oracle SQL Reserved Words](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Oracle-SQL-Reserved-Words.html#GUID-55C49D1E-BE08-4C50-A9DD-8593EB925612) from `unreservedWord`
> 
> Could you please review it :) @wgy8283335

Yes, I could. @tristaZero

**Comment by wgy8283335** [comment]
I'm a little curious about how did you find these reserved words in the unreservedWord rule, by manual or by script? 
Are you sure that all of the reserved words in the unreservedWord rule are cleared?
@Liangda-w

**Comment by Liangda-w** [comment]
> I'm a little curious about how did you find these reserved words in the unreservedWord rule, by manual or by script?
> Are you sure that all of the reserved words in the unreservedWord rule are cleared?
> @Liangda-w

Hi @wgy8283335, I did it manually, by searching each reserved word in `unreservedWord`, it didn't take much time actually. Therefore, I'm quite sure that all of the reserved words in the `unreservedWord` rule are cleared.

**Review by wgy8283335 — APPROVED** [review]

**Comment by wgy8283335** [comment]
> > I'm a little curious about how did you find these reserved words in the unreservedWord rule, by manual or by script?
> > Are you sure that all of the reserved words in the unreservedWord rule are cleared?
> > @Liangda-w
> 
> Hi @wgy8283335, I did it manually, by searching each reserved word in `unreservedWord`, it didn't take much time actually. Therefore, I'm quite sure that all of the reserved words in the `unreservedWord` rule are cleared.

Hi @Liangda-w, the CI still fails, could you have a look? Make sure that the commit could pass on your local computer, and rerun the GitHub CI.

**Pull request merged**
