### PR TITLE
Adding the api-change-history folder inside others folder

### LINKED ISSUE #10974: [Doc] Adjust Others and FAQ chapters
Hi community,

This issue is for [#10887](https://github.com/apache/shardingsphere/issues/10887).

### Background

Refor to #10972

### Aim

Add `Others` chapter and adjust the `FAQ` , `Change History` chapters.

### How to

1. Modify the `7.FAQ` in the document to `7.Others`, the original `FAQ` chapter is sunk to `7.1.FAQ`;

2. Add directory `7.2.API Change History`;

3. Add directory `7.2.1.ShardingSphere-JDBC`;

4. Create `_index.en.md` and `_index.cn.md`, write some descriptions for the directory;

   (If you are not familiar with Chinese, please mark `_index.cn.md` as `TODO`)

### LINKED ISSUE #10990: [Doc] add configuration change history of ShardingSphere-Proxy. (English)
Hi community,

This issue is for [#10887](https://github.com/apache/shardingsphere/issues/10887).

### Background

Refor to #10972

### Aim

add  configuration change history of ShardingSphere-Proxy (English version). 

### How to

1. Add  `7.2.2.ShardingSphere-Proxy` in the `7.2.API Change History` directory;
2. create file `_index.en.md` and write the configuration change history of proxy's `server.yaml`.

### Reference

- [Apache ShardingSphere website](https://shardingsphere.apache.org/)

- [ShardingSphere-Proxy Configuration Manual](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/configuration/)

### PR DESCRIPTION
**Pull request by Swastyy**
Fixes #10974

Changes proposed in this pull request:
-Added the other folder and the faq folder is sunk inside others in documents.

We will need others folder in order to fix #10990 also.

### CODE REVIEW

**Comment by RaigorJiang** [comment]
Hi @Swastyy 
Thank you for your contribution, I have some suggestions:
1. Do not use uppercase for the name of the directory, you can refer to other directories;
2. There should be some content in `_index_*.md`, please refer to https://github.com/apache/shardingsphere/blob/master/docs/document/content/user-manual/_index.en.md;
3. `_index_*.md` of `FAQ` has been moved to the lower-level directory, so the chapter number in the file header should be changed to 7.1;
4. The new directory `others` should also contain the description files `_index.cn.md` & `_index.en.md`.

**Comment by Swastyy** [comment]
> Hi @Swastyy
> Thank you for your contribution, I have some suggestions:
> 
> 1. Do not use uppercase for the name of the directory, you can refer to other directories;
> 2. There should be some content in `_index_*.md`, please refer to https://github.com/apache/shardingsphere/blob/master/docs/document/content/user-manual/_index.en.md;
> 3. `_index_*.md` of `FAQ` has been moved to the lower-level directory, so the chapter number in the file header should be changed to 7.1;
> 4. The new directory `others` should also contain the description files `_index.cn.md` & `_index.en.md`.

Done 👍 
@RaigorJiang Please review it. And I have a doubt that the variable `weight` we are using what it shows?

**Comment by RaigorJiang** [comment]
@Swastyy 
`weight` is a parameter used to control the order of content.  please refer to [hugo](https://discourse.gohugo.io/t/sort-order-only-bydate-or-byweight/6961).

Do we need to adjust the weight value?

**Comment by Swastyy** [comment]
> @Swastyy
> `weight` is a parameter used to control the order of content. please refer to [hugo](https://discourse.gohugo.io/t/sort-order-only-bydate-or-byweight/6961).
> 
> Do we need to adjust the weight value?

Yeah, I think so.

**Comment by Swastyy** [comment]
@strongduanmu @tristaZero Please review this PR.

**Comment by RaigorJiang** [comment]
> > @Swastyy
> > `weight` is a parameter used to control the order of content. please refer to [hugo](https://discourse.gohugo.io/t/sort-order-only-bydate-or-byweight/6961).
> > Do we need to adjust the weight value?
> 
> Yeah, I think so.

OK, I have no other suggestions, thanks for your efforts.  👍

**Review by tristaZero — APPROVED** [review]
@Swastyy Thanks for your contribution. ;-)
@RaigorJiang Thanks for the kind pointer.

**Pull request merged**
