### PR TITLE
Update mode.en.md

### PR DESCRIPTION
**Pull request by puneetjakhar**
related to https://github.com/apache/shardingsphere/issues/21477

### CODE REVIEW

**Comment by puneetjakhar** [comment]
@strongduanmu could you please help review and merge this and also please add the label **hacktoberfest **. Thanks

**Comment by puneetjakhar** [comment]
@Swastyy / @strongduanmu can someone please help review and merge this?

**Review by strongduanmu — APPROVED** [review]
@puneetjakhar Sorry for late reply, merged.

**Comment by puneetjakhar** [comment]
Thanks @strongduanmu, can you please add label **hacktoberfest **.

**Comment by strongduanmu** [comment]
@puneetjakhar Done.

**Pull request merged**
