### PR TITLE
Add test for LocalTransactionManager 

### LINKED ISSUE #10493: Add test for LocalTransactionManager
## Test

Add unit test for `org.apache.shardingsphere.proxy.backend.communication.jdbc.transaction.LocalTransactionManager`

### PR DESCRIPTION
**Pull request by huangdx0726**
Fixes #10493

Changes proposed in this pull request:

- Add test for LocalTransactionManager

### CODE REVIEW

**Review by TeslaCN — CHANGES_REQUESTED** [review]
Hi @huangdx0726 
The test case failed, please fix it.
You may refer to https://travis-ci.org/github/apache/shardingsphere/builds/773767662#L15448-L15456

**Comment by TeslaCN** [comment]
```
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.033 s <<< FAILURE! - in org.apache.shardingsphere.proxy.backend.communication.jdbc.transaction.LocalTransactionManagerTest
[ERROR] unnecessary Mockito stubbings(org.apache.shardingsphere.proxy.backend.communication.jdbc.transaction.LocalTransactionManagerTest)  Time elapsed: 0.022 s  <<< ERROR!
org.mockito.exceptions.misusing.UnnecessaryStubbingException: 
Unnecessary stubbings detected in test class: LocalTransactionManagerTest
Clean & maintainable test code requires zero unnecessary code.
Following stubbings are unnecessary (click to navigate to relevant line of code):
  1. -> at org.apache.shardingsphere.proxy.backend.communication.jdbc.transaction.LocalTransactionManagerTest.setUp(LocalTransactionManagerTest.java:57)
Please remove unnecessary stubbings or use 'silent' option. More info: javadoc for UnnecessaryStubbingException class.
```

**Comment by huangdx0726** [comment]
ok，I'll fix it

**Comment by TeslaCN** [comment]
Hi @huangdx0726 
```
[INFO] There is 1 error reported by Checkstyle 8.19 with src/resources/checkstyle_ci.xml ruleset.
[ERROR] src/test/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/transaction/LocalTransactionManagerTest.java:[25,8] (imports) UnusedImports: Unused import - org.apache.shardingsphere.transaction.core.TransactionType.
```

The checkstyle failed, please fix it.

**Review by TeslaCN — APPROVED** [review]
Thanks for your contribution! @huangdx0726

**Comment by huangdx0726** [comment]
My pleasure. I hope to make more contributions in the future.




---Original---
From: ***@***.***&gt;
Date: Tue, Jun 8, 2021 20:18 PM
To: ***@***.***&gt;;
Cc: "Da Xiang ***@***.******@***.***&gt;;
Subject: Re: [apache/shardingsphere] Add test for LocalTransactionManager  (#10701)




 
@TeslaCN approved this pull request.
 
Thanks for your contribution! @huangdx0726

**Pull request merged**
