### PR TITLE
Removed useless worker-id props for sharding key generator

### LINKED ISSUE #16302: [OpenForce 2022]  Remove useless `worker-id` props  for sharding key generator
Hi community,

This issue is for [OpenForce 2022](https://github.com/apache/shardingsphere/discussions/12683#discussioncomment-2139441)

### Background
Previously, we needed to specify the `worker-id` when creating a `snowflake` key generator object.
But now that `worker-id` has been changed to a process-level configuration, there is no need to specify this parameter for each key generator.

### Aim
Remove useless `worker-id` props as in #15608.

for example:
- in `ShowShardingTableRulesUsedAlgorithmQueryResultSetTest.java`
```java
private ShardingSphereAlgorithmConfiguration createKeyGeneratorConfiguration() {
        Properties props = new Properties();
        props.put("worker-id", "123");
        return new ShardingSphereAlgorithmConfiguration("SNOWFLAKE", props);
    }
```

change it to 
```java
private ShardingSphereAlgorithmConfiguration createKeyGeneratorConfiguration() {
        return new ShardingSphereAlgorithmConfiguration("SNOWFLAKE", new Properties());
    }
```

You can find similar code in:
- `ShardingKeyGeneratorsQueryResultSetTest.java`
- `UnusedShardingKeyGeneratorsQueryResultSetTest.java`
also please change them.

### Basic Qualifications

- Java
- Maven

### PR DESCRIPTION
**Pull request by abhijeetjejurkar**
Signed-off-by: Abhijeet Jejurkar <abhijeet.jejurkar2@gmail.com>

Fixes #16302 .

Changes proposed in this pull request:
- Removed useless worker-id props for sharding key generator

### CODE REVIEW

**Review by totalo — DISMISSED** [review]
hi @abhijeetjejurkar, Thanks for your nice work, but please fix the ci error first.

**Comment by TeslaCN** [comment]
Hi @abhijeetjejurkar 
Any update here?

**Comment by abhijeetjejurkar** [comment]
Sorry I forgot to work on it, I will let you know till EOD

**Comment by TeslaCN** [comment]
The test cases are not urgent for 5.1.1. I'm going to remove this from milestone 5.1.1.

**Comment by abhijeetjejurkar** [comment]
Okay... I was busy today.. I will try to complete it ASAP.

**Review by RaigorJiang — APPROVED** [review]

**Comment by RaigorJiang** [comment]
Merged, thank you! @abhijeetjejurkar

**Comment by abhijeetjejurkar** [comment]
> Merged, thank you! @abhijeetjejurkar

Welcome

**Pull request merged**
