### PR TITLE
Fixes #24424, support mysql member of grammar

### LINKED ISSUE #24424: sharding-jdbc sql parse mysql json type search grammar ”member of“ casue NoViableAltException
0.sharding-jdbc version:5.2.1
1.mysql sql:
 where lc.app_id = #{param.appId}
      and lc.is_deleted = -1
      and lc.status = -1
      and #{param.platformId} member of(lc.match_json -> '$') 
      and json_contains(lc.match_json -> '$', CAST(#{param.deliveryType} AS JSON))
      and lc.direction = #{param.direction}
      and fti.country_code = #{param.countryCode}
      and (fti.charge_method = 1 or JSON_OVERLAPS(ftig.group_item -> '$', CAST(#{param.groupItem} AS JSON)));

image
ea1094c1-71f8-45f5-a737-1ffe3cfe6909

### PR DESCRIPTION
**Pull request by avalon5666**
Fixes #24424.

Changes proposed in this pull request:
  - support mysql [member of](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#operator_member-of) grammar, 

---

Before committing this PR, I'm sure that I have checked the following options:
- [ ] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [ ] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [ ] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Review by strongduanmu — APPROVED** [review]
Thank you @avalon5666, welcome back.

**Comment by avalon5666** [comment]
@strongduanmu I want to learn parse module, if there is a relevant issue, it can be assigned to me. 😄

**Comment by strongduanmu** [comment]
@avalon5666 That's great. You can modify `sql.parser.external.it.enabled=true`, and then try to run `ExternalSQLParserIT`, it will output the MySQL and PostgreSQL syntax that ShardingSphere does not currently support, and you can try to support these sql syntax.

**Comment by strongduanmu** [comment]
This is the latest result for MySQL database - [MySQL-result.csv](https://github.com/apache/shardingsphere/files/10976212/MySQL-result.csv)

**Pull request merged**
