### PR TITLE
Added unit test for TablesContext#findTableNamesByColumnProjection

### PR DESCRIPTION
**Pull request by abhijeetjejurkar**
Signed-off-by: Abhijeet Jejurkar <abhijeet.jejurkar2@gmail.com>

Fixes: #15815

Changes proposed in this pull request:
Added unit test for TablesContext#findTableNamesByColumnProjection

### CODE REVIEW

**Review by strongduanmu — CHANGES_REQUESTED** [review]
Hi @abhijeetjejurkar, thank you for your contribution, can you solve ci error first?

**Comment by abhijeetjejurkar** [comment]
@strongduanmu  I Guess Error was due to extra line space at Line number 176. I just removed It. I guess It should work now

**Comment by strongduanmu** [comment]
> @strongduanmu I Guess Error was due to extra line space at Line number 176. I just removed It. I guess It should work now

@abhijeetjejurkar Thank you, let's wait ci result.

**Review by strongduanmu — APPROVED** [review]
@abhijeetjejurkar Good job, merged.

**Comment by abhijeetjejurkar** [comment]
> @abhijeetjejurkar Good job, merged.

Thankyou😊

**Pull request merged**
