### PR TITLE
Issue 9416

### PR DESCRIPTION
**Pull request by lmhmhl**
@tristaZero, Please review the code, Thx.

### CODE REVIEW

**Review by tristaZero — CHANGES_REQUESTED** [review]
Hi @lmhmhl 
LGTM, just a minor tip for you.

**Review by tristaZero — APPROVED** [review]
Looks great!

**Comment by tristaZero** [comment]
Hi Could you link the relevant issue when you raise the next PR? Therefore the community will know what this PR is for.

**Comment by lmhmhl** [comment]
> Hi Could you link the relevant issue when you raise the next PR? Therefore the community will know what this PR is for.

I'll pay attention next time.

**Pull request merged**
