### PR TITLE
Add GraalVM Reachability Metadata and corresponding nativeTest for Iceberg table in HiveServer2

### PR DESCRIPTION
**Pull request by linghengqian**
For #29052.

Changes proposed in this pull request:
  - Add GraalVM Reachability Metadata and corresponding nativeTest for Hive. The irrelevant content of the current PR has been split into the following PRs.
    - #31573
    - #31630
    - #31975
    - #32246
    - #32267
    - #32389
    - #32418
    - #32552
  - `shardingsphere-parser-sql-hive` module does not support `CREATE`, `SET`,`TRUNCATE`, `DROP` statements yet. This is marked with a TODO.
  - To execute SQL like `DELETE FROM t_address WHERE address_id=?`, we always need to execute some Hive Session-level SQL in the current `javax.sql.DataSource`. However, since the SQL parsing of `set key=value` is not supported, these SQLs are currently located in `test-native/sql/test-native-databases-hive.sql` and are directly passed through to the actual Hive database for processing.
  - The current PR is disturbed by part of the external issue.
    - ~For https://issues.apache.org/jira/browse/HIVE-28295 and https://issues.apache.org/jira/browse/HIVE-28418 . The current PR is using Remote HiveServer2 in Docker instead of Embedded HiveServer2.~ According to the discussion at https://issues.apache.org/jira/browse/HIVE-28418, the use of embedded HiveServer2 is no longer encouraged and the related documents will be deleted.
    - For https://issues.apache.org/jira/browse/HIVE-28317 and https://issues.apache.org/jira/browse/HIVE-5867 . The `initFile` parameter of HiveServer2 JDBC Driver must be an absolute path. Maybe new properties can be added on the Hive side.
    -  For https://issues.apache.org/jira/browse/HIVE-28316 and https://issues.apache.org/jira/browse/HIVE-28322 . **Locally, after executing Insert SQL, 10 rows of data in Hive Database can be queried normally. However, in Github Actions, after executing Insert SQL, only part of the data can be queried.** I tend to think this is a transaction bug on the apache/hive 4.0.0 side, because this phenomenon can always be observed on a single hive database regardless of whether shardingsphere is used to shard multiple hive databases.
    - ~For https://issues.apache.org/jira/browse/hive-28308 . Because the unknown Commit on the Hive side, `org.apache.hive:hive-jdbc:4.0.0` does not contain any compile scope dependence.~ The hive contributors said this was intentional and related to a bug with incorrect display of Maven Central.
    - ~For https://issues.apache.org/jira/browse/HIVE-28429 , https://github.com/apache/spark/pull/30250 and https://github.com/apache/hive/pull/5313 . The shaded class `org.apache.hadoop.shaded.com.ctc.wstx.io.InputBootstrapper` from `org.apache.hadoop:hadoop-client-api` should not be excluded internally within `org.apache.hive:hive-service:4.0.0`, which necessitates excluding its internal dependency on `org.apache.hadoop:hadoop-client-api` and manually adding `org.apache.hadoop:hadoop-client-api:3.3.5`.~ See #32552 .
    - It is currently not convenient to operate on the `t_order` and `t_order_item` tables because `org.apache.hive.jdbc.HiveStatement` does not implement `java.sql.Statement#getGeneratedKeys()`.
    - ~~For https://github.com/oracle/graalvm-reachability-metadata/issues/377 and https://github.com/grpc/grpc-java/issues/10601 . Since  `io.grpc:grpc-netty-shaded:1.58.0` in `org.apache.hive:hive-service:4.0.0` shades Netty, this shaded package requires additional `native-image.properties`. If the HiveServer2 JDBC Driver can remove the use of `grpc-netty-shaded`, it will obviously make the current PR less difficult to understand.~~ It seems that the use of grpc-netty can lead to a larger range of dependencies.
    - ~For https://issues.apache.org/jira/browse/HIVE-28417 . HiveServer2 JDBC Driver uses a log4j2 version that is incompatible with the GraalVM Native Image.~ Resolved by https://github.com/apache/logging-log4j2/issues/1539#issuecomment-2267307774.
    - For https://github.com/apache/hive/pull/5187 . Hive does not support Hadoop 3.4.0.

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [x] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [x] I have made corresponding changes to the documentation.
- [x] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Review by linghengqian — COMMENTED** [review]
- The current PR actually needs to wait for the release of `org.apache.hive:hive-jdbc:4.0.1`. See https://lists.apache.org/thread/74m4bps5n2hjcmkyz7jktw4kot7yz7qz .

**Review by linghengqian — COMMENTED** [review]
- Let's continue to wait for the resolution of https://github.com/apache/shardingsphere/issues/32377 .
- By the way, using HiveServer2 JDBC Driver under GraalVM Native Image does involve a lot of external discussions. 🤗Perhaps we will have to wait for external discussions to be completed. 🦒
    - https://issues.apache.org/jira/browse/HIVE-28295
    - https://issues.apache.org/jira/browse/HIVE-28308
    - https://issues.apache.org/jira/browse/HIVE-28316
    - https://issues.apache.org/jira/browse/HIVE-28317
    - https://issues.apache.org/jira/browse/HIVE-28322
    - https://issues.apache.org/jira/browse/HIVE-28417
    - https://issues.apache.org/jira/browse/HIVE-28418
    - https://issues.apache.org/jira/browse/HIVE-28420
    - https://issues.apache.org/jira/browse/HIVE-28423
    - https://issues.apache.org/jira/browse/HIVE-28424
    - https://issues.apache.org/jira/browse/HIVE-28429
    - https://issues.apache.org/jira/browse/HIVE-28430
    - https://issues.apache.org/jira/browse/HIVE-28432
    - https://github.com/apache/shardingsphere/issues/32377
    - https://github.com/oracle/graalvm-reachability-metadata/issues/377
    - https://github.com/grpc/grpc-java/issues/10601
    - https://github.com/apache/logging-log4j2/issues/1539
    - https://github.com/apache/spark/pull/30250
    - https://github.com/apache/hive/pull/5313
    - https://github.com/apache/hive/pull/5187
    - https://github.com/apache/logging-log4j2/issues/2791
    - https://github.com/apache/logging-log4j2/issues/2794
    - https://github.com/apache/shardingsphere/pull/31573
    - https://github.com/apache/shardingsphere/pull/31630
    - https://github.com/apache/shardingsphere/pull/31975
    - https://github.com/apache/shardingsphere/pull/32246
    - https://github.com/apache/shardingsphere/pull/32267

**Review by linghengqian — COMMENTED** [review]
- Let's import https://github.com/linghengqian/hive-server2-jdbc-driver to shield thousands of lines of dependency management.

**Review by linghengqian — COMMENTED** [review]
- Non-focus of the current PR has been moved to the following external issues or PRs.
    - https://issues.apache.org/jira/browse/HIVE-28295
    - https://issues.apache.org/jira/browse/HIVE-28308
    - https://issues.apache.org/jira/browse/HIVE-28316
    - https://issues.apache.org/jira/browse/HIVE-28317
    - https://issues.apache.org/jira/browse/HIVE-28322
    - https://issues.apache.org/jira/browse/HIVE-28417
    - https://issues.apache.org/jira/browse/HIVE-28418
    - https://issues.apache.org/jira/browse/HIVE-28420
    - https://issues.apache.org/jira/browse/HIVE-28423
    - https://issues.apache.org/jira/browse/HIVE-28424
    - https://issues.apache.org/jira/browse/HIVE-28429
    - https://issues.apache.org/jira/browse/HIVE-28430
    - https://issues.apache.org/jira/browse/HIVE-28432
    - https://issues.apache.org/jira/browse/HIVE-28437
    - https://issues.apache.org/jira/browse/HIVE-28444
    - https://issues.apache.org/jira/browse/HIVE-28445
    - https://github.com/apache/spark/pull/30250
    - https://github.com/dbeaver/dbeaver/issues/22777
    - https://github.com/apache/logging-log4j2/issues/1539
    - https://github.com/grpc/grpc-java/issues/10601
    - https://github.com/oracle/graalvm-reachability-metadata/issues/377
    - https://github.com/apache/hive/pull/5313
    - https://github.com/apache/hive/pull/5187
    - https://github.com/apache/logging-log4j2/issues/2794
    - https://github.com/apache/logging-log4j2/issues/2791
    - https://github.com/apache/hive/pull/5375
    - https://github.com/apache/hive/pull/5381

**Review by linghengqian — COMMENTED** [review]
- We needed a transactional HiveServer2 for our unit tests, but the options provided by apache/hive were a bit overkill. Compared to manually creating ACID tables,
```sql
set metastore.compactor.initiator.on=true;
set metastore.compactor.cleaner.on=true;
set metastore.compactor.worker.threads=5;

set hive.support.concurrency=true;
set hive.exec.dynamic.partition.mode=nonstrict;
set hive.txn.manager=org.apache.hadoop.hive.ql.lockmgr.DbTxnManager;

CREATE TABLE IF NOT EXISTS t_order
(
    order_id   BIGINT,
    order_type INT,
    user_id    INT    NOT NULL,
    address_id BIGINT NOT NULL,
    status     VARCHAR(50),
    PRIMARY KEY (order_id) disable novalidate
) CLUSTERED BY (order_id) INTO 2 BUCKETS STORED AS ORC TBLPROPERTIES ('transactional' = 'true');
```
- I prefer to create Iceberg tables directly. Although apache/hive does not support full transactions, iceberg provides a way forward for apache/hive, making it possible to use local transactions, XA transactions, and Seata AT transactions on iceberg tables of HiveServer2 in the future. Whether it is an ACID table or an iceberg table, from the perspective of the apache/shardingsphere parser, it only provides support for DML statements, and any transaction rollback operations are not supported.
```sql
set iceberg.mr.schema.auto.conversion=true;

CREATE TABLE IF NOT EXISTS t_order
(
    order_id   BIGINT,
    order_type INT,
    user_id    INT    NOT NULL,
    address_id BIGINT NOT NULL,
    status     VARCHAR(50),
    PRIMARY KEY (order_id) disable novalidate
) STORED BY ICEBERG STORED AS ORC TBLPROPERTIES ('format-version' = '2');
```
- It is worth mentioning that apache/iceberg seems to have dropped support for JDK8, but apache/hive still supports JDK8 like apache/shardingsphere. See https://github.com/apache/iceberg/pull/10518 and https://github.com/apache/iceberg/issues/10940.
However, apache/orc has long dropped support for JDK8, and apache/hive seems to be almost unaffected. See https://github.com/apache/orc/pull/1627. If apache/hive does not make any changes, apache/shardingsphere actually does not need to consider upgrading the jdk runtime to jdk17.

**Review by strongduanmu — APPROVED** [review]

**Pull request merged**
