### PR TITLE
Fixed logical table metadata loading issues.

### PR DESCRIPTION
**Pull request by totalo**
For #11028 .

### CODE REVIEW

**Comment by tristaZero** [comment]
This PR looks fine to me. Also, It is suggested to do some improvement in the following code snippets. At least, the function names, i,e., `appendRemainTables`, `addRuleConfiguredTables` are not appropriate.
```
// SchemaBuilder.java

    public static Map<TableMetaData, TableMetaData> build(final SchemaBuilderMaterials materials) throws SQLException {
        Map<String, TableMetaData> actualTableMetaMap = appendRemainTables(materials);
        Map<String, TableMetaData> logicTableMetaMap = addRuleConfiguredTables(materials, actualTableMetaMap);
        return buildTableMetaDataMap(actualTableMetaMap, logicTableMetaMap);
    }
```

**Review by tristaZero — CHANGES_REQUESTED** [review]
This PR looks fine to me. Also, It is suggested to do some improvement in the following code snippets. At least, the function names, i,e., `appendRemainTables`, `addRuleConfiguredTables` are not appropriate.
```
// SchemaBuilder.java

    public static Map<TableMetaData, TableMetaData> build(final SchemaBuilderMaterials materials) throws SQLException {
        Map<String, TableMetaData> actualTableMetaMap = appendRemainTables(materials);
        Map<String, TableMetaData> logicTableMetaMap = addRuleConfiguredTables(materials, actualTableMetaMap);
        return buildTableMetaDataMap(actualTableMetaMap, logicTableMetaMap);
    }
```

**Comment by totalo** [comment]
> This PR looks fine to me. Also, It is suggested to do some improvement in the following code snippets. At least, the function names, i,e., `appendRemainTables`, `addRuleConfiguredTables` are not appropriate.
> 
> ```
> // SchemaBuilder.java
> 
>     public static Map<TableMetaData, TableMetaData> build(final SchemaBuilderMaterials materials) throws SQLException {
>         Map<String, TableMetaData> actualTableMetaMap = appendRemainTables(materials);
>         Map<String, TableMetaData> logicTableMetaMap = addRuleConfiguredTables(materials, actualTableMetaMap);
>         return buildTableMetaDataMap(actualTableMetaMap, logicTableMetaMap);
>     }
> ```

yeah! let me see.

**Review by tristaZero — APPROVED** [review]
@totalo Hey  It becomes pretty straightforward, doesn't it? Great.

**Pull request merged**
