### PR TITLE
Add drop server for PostgreSQL

### PR DESCRIPTION
**Pull request by Trydamere**
Ref #14015.

Changes proposed in this pull request:
- Add `drop server` for PostgreSQL
- Add test case
- Run tests

### CODE REVIEW

**Review by taojintianxia — APPROVED** [review]

**Review by strongduanmu — CHANGES_REQUESTED** [review]
Hi @Trydamere, can you fix ci error first?

**Comment by Trydamere** [comment]
Sure.

**Comment by strongduanmu** [comment]
@Trydamere Can you sync latest master branch code?

**Comment by Trydamere** [comment]
Sure.

**Comment by Trydamere** [comment]
@strongduanmu It seems there are some errors on project shardingsphere-db-protocol-core.

**Comment by strongduanmu** [comment]
> shardingsphere

Please sync the master branch again 🤣, we have fixed this exception.

**Comment by Trydamere** [comment]
@strongduanmu ok.

**Review by strongduanmu — APPROVED** [review]
Thank you @Trydamere.

**Pull request merged**
