### PR TITLE
Build failed with error Could not find resource 'src/resources/spotless/java.xml' if working dir is not root of ShardingSphere

### LINKED ISSUE #25190: Build failed with error Could not find resource 'src/resources/spotless/java.xml' if working dir is not root of ShardingSphere
### Which version of ShardingSphere did you use?

master - e4d0557d5039dc1dce2c8d8c8fe9eb06b85aa1ac

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Failed:
```bash
% pwd
/home/wuweijie/projects/shardingsphere/sql-parser/dialect/mysql

% mvn clean install -q -DskipTests
```

This worked:
```bash
% pwd
/home/wuweijie/projects/shardingsphere

% mvn clean install -f sql-parser/dialect/mysql/pom.xml -q -DskipTests
```

### Expected behavior

Build specific modules successfully.

### Actual behavior

```
% pwd
/home/wuweijie/projects/shardingsphere/sql-parser/dialect/mysql
% mvn clean install -q -DskipTests
Running `/home/wuweijie/projects/shardingsphere/mvnw`...
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.22.1:apply (default) on project shardingsphere-sql-parser-mysql: Execution default of goal com.diffplug.spotless:spotless-maven-plugin:2.22.1:apply failed: Unable to locate file with path: src/resources/spotless/java.xml: Could not find resource 'src/resources/spotless/java.xml'. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

```

### PR DESCRIPTION
**Pull request by wuxihao01**
Fixes #25190 .

Changes proposed in this pull request:
  -

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [ ] I have (or in comment I request) added corresponding labels for the pull request.
- [ ] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding unit tests for my changes.

### CODE REVIEW

**Comment by TeslaCN** [comment]
Please clarify the PR title and commit log.

**Comment by wuxihao01** [comment]
> Please clarify the PR title and commit log.

Sorry, This is my first attempt to resolve the issue. Do I need to roll back again and write a log in the local commit before uploading and submitting again

**Review by terrymanu — CHANGES_REQUESTED** [review]
The GitHub actions are all passed before the PR merge, is it necessary to merge it?

**Comment by wuxihao01** [comment]
> The GitHub actions are all passed before the PR merge, is it necessary to merge it?

Sorry,I am a first-time contributor，I change the pom.xml to fix the problem(#25190 ) and commit log in the latest commit. Do I need to do anything else?

**Comment by TeslaCN** [comment]
> The GitHub actions are all passed before the PR merge, is it necessary to merge it?

https://github.com/apache/shardingsphere/pull/24927 caused Maven build failure if working dir is not root of ShardingSphere.
Just try `cd` into some modules and execute `mvn install` and you will get it.

**Comment by TeslaCN** [comment]
image

**Review by linghengqian — COMMENTED** [review]
- `${maven.multiModuleProjectDirectory}` is an internal variable defined by `./mvnw`, why not use `${user.dir}`? 🤔

**Comment by TeslaCN** [comment]
> * `${maven.multiModuleProjectDirectory}` is an internal variable defined by `./mvnw`, why not use `${user.dir}`? 🤔

We need the content root of ShardingSphere project, I don't think `user.dir` is what we need.

But, maybe we could try `${maven.projectBasedir}`. https://maven.apache.org/docs/3.3.1/release-notes.html#jvm-and-command-line-options

**Comment by linghengqian** [comment]
> > * `${maven.multiModuleProjectDirectory}` is an internal variable defined by `./mvnw`, why not use `${user.dir}`? 🤔
> 
> We need the content root of ShardingSphere project, I don't think `user.dir` is what we need.
> 
> But, maybe we could try `${maven.projectBasedir}`. https://maven.apache.org/docs/3.3.1/release-notes.html#jvm-and-command-line-options

- `${project.basedir}` is a good idea.

**Comment by wuxihao01** [comment]
> * `${maven.multiModuleProjectDirectory}` is an internal variable defined by `./mvnw`, why not use `${user.dir}`? 🤔

I try to use ${user.dir} to replace ${maven.multiModuleProjectDirectory} and find that if working dir is not root of ShardingSphere，the ${user.dir} could not find the src/resources/spotless/java.xml either.

**Comment by linghengqian** [comment]
> > * `${maven.multiModuleProjectDirectory}` is an internal variable defined by `./mvnw`, why not use `${user.dir}`? 🤔
> 
> I try to use ${user.dir} to replace ${maven.multiModuleProjectDirectory} and find that if working dir is not root of ShardingSphere，the ${user.dir} could not find the src/resources/spotless/java.xml either.

- What about `${project.basedir}`?

**Review by tristaZero — APPROVED** [review]

**Review by terrymanu — APPROVED** [review]

**Comment by wuxihao01** [comment]
> * ${project.basedir}

I try in Windows for` ${project.basedir}` but build failed either. I think it could work in Linux

**Comment by wuxihao01** [comment]
> ${maven.projectBasedir}

I try to use `${maven.projectBasedir}` to replace and build failed
image

**Pull request merged**
