### PR TITLE
#11397 Fix bug of wrong route result

### LINKED ISSUE #11397: route result is wrong
I execute a SQL like this : "select * from demo_db where num=1 or num=2 and count=3"，
I config 2 dataSources : ds_0 and ds_1
table strategy : tb_${num % 2}，
database strategy : ds_${count % 2}
but route result only contains ds_1，following is actual SQL:
Actual SQL: ds_1 ::: select * from tb_1 where num = 1 or num=2 and count =3
Actual SQL: ds_1 ::: select * from tb_0 where num = 1 or num=2 and count =3
Version : 4.1.0

### PR DESCRIPTION
**Pull request by vince7839**
Fixes #11397.

Changes proposed in this pull request:
- fix bug of wrong route result when an "OR" condition before "AND" condition
- Add unit test

### CODE REVIEW

**Comment by vince7839** [comment]
@tristaZero @strongduanmu 
Hi,I've modified code and add unit test in this PR.

**Comment by strongduanmu** [comment]
> @tristaZero @strongduanmu
> Hi,I've modified code and add unit test in this PR.

@vince7839 Please also add rewritten test cases.

**Comment by vince7839** [comment]
> > @tristaZero @strongduanmu
> > Hi,I've modified code and add unit test in this PR.
> 
> @vince7839 Please also add rewritten test cases.

Okay,I'll do it , add in RouteSQLRewriteEngineTest?

**Comment by strongduanmu** [comment]
@vince7839 add in `ShardingSQLRewriterParameterizedTest`

**Pull request closed without merging**
